Таразанов Максим, ИТМО, Stage3
polis-vk/2024-highload-dht pull request #103
Opened 2024-03-13 01:23 UTC by MaxTTG

2024-03-14 08:36 UTC, incubos commented
Вы с DWS или ФИТИП?

2024-03-25 20:56 UTC, atimofeyev requested changes

2024-03-25 20:56 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/tarazanovmaxim/hash/Hasher.java
> +        return ByteBuffer.wrap(hash).getInt();
Не слишком ли раточительно, считаем sha-256, а берем только 4 байта?

2024-03-25 20:56 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/tarazanovmaxim/hash/Hasher.java
> +        final byte[] hash = messageDigest.digest(bytes);
MessageDigest не потокобезопасен, лучше пользоваться ThreadLocal или еще каким-нибудь вариантом

2024-03-25 20:56 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/tarazanovmaxim/MyServer.java
> +            Hasher hasher = new Hasher();
все это непотокобезопасно, хоть и использууются final ссылки на объекы, которые далее не изменяются, безопансо это будет если после того как ссылка проинициализируется объект больше не будет изменяться

2024-03-25 20:56 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/tarazanovmaxim/hash/ConsistentHashing.java
> +                break;
если бы тут сделать ретурн, то ниже не пришлось бы писать if-else

2024-03-25 20:56 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/tarazanovmaxim/MyServer.java
> +        executorService.close();
не очень удачный метод, лучше закрывать экзекутер через shutdown + shutdownNow

2024-03-25 20:56 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/tarazanovmaxim/MyServer.java
> +            response = httpClients.get(shards.getShardByKey(id)).invoke(redirect, 500);
на каждый запрос по два раза считаем хеш от id

2024-03-25 20:56 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/tarazanovmaxim/stages/stage3/report.md
> +В новой версии уходит очень много процессорного времени при поиске узла.
пробовали ли как-то уменьшить затрачиваемое время?

2024-03-26 19:27 UTC, MaxTTG commented on src/main/java/ru/vk/itmo/test/tarazanovmaxim/hash/Hasher.java
> +        return ByteBuffer.wrap(hash).getInt();
Мне было интересно, насполько ресурсозатратно на фоне всего получится подход с sha-256, потому что я сталкивался с этим алгоритмом и хотелось сравнить именно от него (в первую очередь)
В отчете забыл указать, что занимает ~1.4% от CPU
Для скорости, конечно, можно было использовать не криптостойкие, но так мы чуть больше защищены от DDoS

2024-03-26 19:27 UTC, MaxTTG commented on src/main/java/ru/vk/itmo/test/tarazanovmaxim/hash/Hasher.java
> +        final byte[] hash = messageDigest.digest(bytes);
Исправил

2024-03-26 19:27 UTC, MaxTTG commented on src/main/java/ru/vk/itmo/test/tarazanovmaxim/MyServer.java
> +            Hasher hasher = new Hasher();
Исправил

2024-03-26 19:28 UTC, MaxTTG commented on src/main/java/ru/vk/itmo/test/tarazanovmaxim/hash/ConsistentHashing.java
> +                break;
Исправил

2024-03-26 19:28 UTC, MaxTTG commented on src/main/java/ru/vk/itmo/test/tarazanovmaxim/MyServer.java
> +        executorService.close();
Исправил

2024-03-26 19:28 UTC, MaxTTG commented on src/main/java/ru/vk/itmo/test/tarazanovmaxim/MyServer.java
> +            response = httpClients.get(shards.getShardByKey(id)).invoke(redirect, 500);
Исправил

2024-03-26 19:37 UTC, MaxTTG commented on src/main/java/ru/vk/itmo/test/tarazanovmaxim/stages/stage3/report.md
> +В новой версии уходит очень много процессорного времени при поиске узла.
Честно говоря нет, потому что предположил, что это делается другой системой и там нагрузка будет соизмерима той, что вышла

2024-03-26 20:02 UTC, MaxTTG commented
done

2024-03-26 20:52 UTC, MaxTTG commented
и можно ли баллы узнать, пожалуйста?

2024-03-30 13:48 UTC, atimofeyev requested changes

2024-03-30 13:48 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/reference/ReferenceServer.java
> +import one.nio.http.Path;
надо бы убрать изменения из ReferenceServer

2024-03-30 13:48 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/reference/ReferenceService.java
> +import java.util.concurrent.ExecutorService;
надо бы убрать изменения из ReferenceServer

2024-03-30 17:36 UTC, MaxTTG commented on src/main/java/ru/vk/itmo/test/reference/ReferenceServer.java
> +import one.nio.http.Path;
немного не понимаю, о чем идет речь

просто убрать импорты?

2024-04-04 17:44 UTC, atimofeyev requested changes

2024-04-04 17:44 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/reference/ReferenceServer.java
> -}
все еще остались изменения, поправьте и тут пожалуйста

2024-04-04 17:44 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/reference/ReferenceService.java
> -}
все еще остались изменения, поправьте и тут пожалуйста

2024-04-18 15:24 UTC, atimofeyev approved these changes

2024-04-18 16:07 UTC, merged