Emelyanov Vitaliy, SPbSTU, 3rd stage
polis-vk/2024-highload-dht pull request #107
Opened 2024-03-13 16:05 UTC by GenryEden

2024-03-17 20:29 UTC, Marashov-Alexander requested changes
Накинул несколько пожеланий. Удачи в исправлениях и составлении отчетов!

2024-03-17 20:29 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/emelyanovvitaliy/DhtServer.java
> +        dao = new ReferenceDao(new Config(config.workingDir(), 1 << 24));
константу бы вынести и пояснить, сколько это, чтоб читающий код не считал

2024-03-17 20:29 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/emelyanovvitaliy/DhtServer.java
> +                    httpClient.close();
а если воркеры экзекьютера отправили запрос на другую ноду и ожидают ответ, то если я правильно понял, вызовом метода close мы же отменим ожидание ответа и последующее ожидание выполнения уже будет бессмысленно?
Если это так, то может лучше сначала дождаться выполнения (через закрытие экзекьютера), а уже потом закрывать http-клиентов?

2024-03-17 20:29 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/emelyanovvitaliy/DhtServer.java
> +            threadPoolExecutor.execute(
во всех трех методах виден похожий шаблон кода. Можно ли как-то вынести отдельно, чтоб не дублировать код?

2024-03-20 19:35 UTC, GenryEden commented on src/main/java/ru/vk/itmo/test/emelyanovvitaliy/DhtServer.java
> +                                httpSession.sendResponse(new Response(Response.PAYMENT_REQUIRED, EMPTY_BODY));
это такая шутка была на лекции, что можно кидать 402, мол, вы нам доплатите, и мы вам приоритет по очереди сделаем

2024-03-20 19:41 UTC, GenryEden commented on src/main/java/ru/vk/itmo/test/emelyanovvitaliy/DhtServer.java
> +            threadPoolExecutor.execute(
лучшее, что придумал - вынести отдельный метод по отправке BAD_REQUEST

2024-03-24 19:28 UTC, Marashov-Alexander approved these changes
Готов поставить 9 из 15 баллов, 
Из проблем - в качестве хеша выбран hashCode, не задано максимальное время ожидания ответа от ноды, есть пара вопросиков к отчету. 
В остальном норм

2024-03-24 19:28 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/emelyanovvitaliy/DhtServer.java
> +        return httpClients[Math.abs(key.hashCode()) % httpClients.length];
согласно заданию: "Реализуйте один из алгоритмов распределения данных между узлами, например, [consistent hashing](https://en.wikipedia.org/wiki/Consistent_hashing), [rendezvous hashing](https://en.wikipedia.org/wiki/Rendezvous_hashing) или что-то другое по согласованию с преподавателем."

Было ли согласование key.hashCode вместо приведенных алгоритмов хеширования?

2024-03-24 19:28 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/emelyanovvitaliy/DhtServer.java
> +            clients[cnt++] = url.equals(thisUrl) ? null : new HttpClient(new ConnectionString(url));
правильно понял, что при отправке запроса на другую ноду явный таймаут не задан и мы можем ждать ответа очень долго? Кажется, что это плохая тактика, особенно если запрашиваемой ноде поплохело

2024-03-24 19:28 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/emelyanovvitaliy/reports/3/3.md
Ощущение, что не хватает сравнения результатов нагрузочного тестирования с предыдущим этапом прям в числах: сколько выдерживали и сколько выдерживаем теперь, почему, ожидаемо ли это, можно ли с этим что-то сделать. Наглядный график по перцентилям с новой и старой реализацией был бы очень в тему

2024-03-25 14:07 UTC, GenryEden commented on src/main/java/ru/vk/itmo/test/emelyanovvitaliy/DhtServer.java
> +            Runtime.getRuntime().availableProcessors() * THREADS_PER_PROCESSOR,
если речь про threadsInPool - этот счетчик нужен, чтобы последовательно проименовать потоки

2024-03-25 14:07 UTC, GenryEden commented on src/main/java/ru/vk/itmo/test/emelyanovvitaliy/DhtServer.java
> +    private boolean tryForward(HttpSession session, Request request, String key) throws IOException {
согласен, но убирать не буду - мне оч понравилось, как я его вкрутил) даже баллами за это готов пожертвовать

2024-03-25 14:10 UTC, GenryEden commented on src/main/java/ru/vk/itmo/test/emelyanovvitaliy/DhtServer.java
> +        return httpClients[Math.abs(key.hashCode()) % httpClients.length];
переделал на rendezvous hashing на основе murmur3 и нумерации кантора (для того, чтобы равномерно превращать отдельные хэши ключа и клиента в один общий хэш без прибегания к конкатенации строк)

2024-03-25 14:10 UTC, GenryEden commented on src/main/java/ru/vk/itmo/test/emelyanovvitaliy/DhtServer.java
> +            clients[cnt++] = url.equals(thisUrl) ? null : new HttpClient(new ConnectionString(url));
исправил, выставил 100 мс в константе

2024-04-06 13:59 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/emelyanovvitaliy/DhtServer.java
> +            Runtime.getRuntime().availableProcessors() * THREADS_PER_PROCESSOR,
Речь про TASK_QUEUE_SIZE )

2024-04-06 14:07 UTC, merged