Далбеев Георгий / ИТМО DWS / Stage 3
polis-vk/2024-highload-dht pull request #108
Opened 2024-03-13 16:05 UTC by goshadalbeev

2024-03-23 20:45 UTC, atimofeyev requested changes

2024-03-23 20:45 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/georgiidalbeev/NewServer.java
> +        HttpClient httpClient = httpClients.get(clusterUrls.indexOf(node));
вот тут было бы красивее доставать из мапы по строке. Из списка тогда уж по индексу доставать.

2024-03-23 20:46 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/georgiidalbeev/results/stage3.md
> +- Также в Lock добавились локи `~27%` httpClient, а лок тредов занимает `~1.8%`.
Пробовали как-то увеличить пропускную способность на основании полученного профиля?

2024-03-24 18:06 UTC, goshadalbeev commented on src/main/java/ru/vk/itmo/test/georgiidalbeev/results/stage3.md
> +- Также в Lock добавились локи `~27%` httpClient, а лок тредов занимает `~1.8%`.
Пробовал увеличить количество реплик, но это не помогло, а только ухудшило, поэтому решил не вносить в отчет.

2024-03-26 16:49 UTC, goshadalbeev commented on src/main/java/ru/vk/itmo/test/georgiidalbeev/ConsistentHashing.java
> +        for (T node : nodes) {
Исправил

2024-03-26 16:49 UTC, goshadalbeev commented on src/main/java/ru/vk/itmo/test/georgiidalbeev/NewServer.java
> +        HttpClient httpClient = httpClients.get(clusterUrls.indexOf(node));
Исправил

2024-03-30 13:24 UTC, atimofeyev approved these changes

2024-03-30 13:24 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/georgiidalbeev/NewService.java
> +        httpClients = config.clusterUrls().stream()
интересно было бы еще посмотреть что было бы с одним httpClient-ом

2024-03-30 13:25 UTC, merged