DWS | Task 3 | Ершов Вадим
polis-vk/2024-highload-dht pull request #115
Opened 2024-03-13 21:11 UTC by vadim01er

2024-03-24 15:58 UTC, incubos commented on src/main/java/ru/vk/itmo/test/vadimershov/DaoHttpServer.java
> +        this.dao.close();
Почему мы здесь всё стопаем и закрываем, а не там, где создавали? Это нетипичное поведение.

2024-03-24 16:03 UTC, vadim01er commented on src/main/java/ru/vk/itmo/test/vadimershov/DaoHttpServer.java
> +        this.dao.close();
Да, вероятно, я перенесу создание dao внутрь HttpServer'а, просто проглядел это

2024-03-24 16:38 UTC, incubos requested changes
Есть несколько замечаний и вопросов. Ждём исправлений перед merge.

2024-03-24 16:38 UTC, incubos commented on src/main/java/ru/vk/itmo/test/vadimershov/hash/ConsistentHashing.java
> +            int existingReplicas = countReplicas(currentUrl);
Зачем это считать? Мы ведь каждый `currentUrl` добавляем `VIRTUAL_NODE_COUNT` раз ниже и переходим к следующему. Или я неверно понял идею?

2024-03-24 16:38 UTC, incubos commented on src/main/java/ru/vk/itmo/test/vadimershov/ShardingDao.java
> +                logger.error(e.getMessage());
Принято так (и во всех остальных местах) -- что мы пытались сделать, входные параметры, ошибка:
```suggestion
                logger.error("Can't get value by key={}", key, e);
```

2024-03-24 16:38 UTC, incubos commented on src/main/java/ru/vk/itmo/test/vadimershov/ShardingDao.java
> +                throw new NotFoundException();
Имеет смысл сделать исключение checked и добавить в сигнатуру метода, чтобы не нужно было изучать код, чтобы понять, какие исключения могут вылетать. Либо написать JavaDoc и возвращать `null`, чтобы не "платить" за выбрасывание исключения.

2024-03-24 16:38 UTC, incubos commented on src/main/java/ru/vk/itmo/test/vadimershov/ShardingDao.java
> +        try {
```suggestion

        try {
```

2024-03-24 16:38 UTC, incubos commented on src/main/java/ru/vk/itmo/test/vadimershov/ShardingDao.java
> +            case 400 -> throw new RemoteServiceException(DaoResponse.BAD_REQUEST, url);
`RemoteServiceException`, видимо, тоже имеет смысл сделать checked и явно указать в сигнатуре метода.

2024-03-24 16:38 UTC, incubos commented on src/main/java/ru/vk/itmo/test/vadimershov/ShardingDao.java
> +            default -> { /* correct program work */ }
Конструкция выглядит довольно хрупкой в плане будущего развития -- что если потом добавятся новые 5хх коды?

2024-03-24 16:38 UTC, incubos commented on src/main/java/ru/vk/itmo/test/vadimershov/ShardingDao.java
> +            throw new DaoException(e);
Может, тоже сделаем checked exception и добавим сообщение о том, что мы пытались сделать?

2024-03-24 16:38 UTC, incubos commented on src/main/java/ru/vk/itmo/test/vadimershov/ShardingDao.java
> +            throw new DaoException(e);
И во всех остальных местах тоже.

2024-03-24 16:38 UTC, incubos commented on src/main/java/ru/vk/itmo/test/vadimershov/wrk/result3/report.md
> +и мне пришлось изменить количество коннектов wrk до 64, так как не выделялись коннекты к смежным нодам.
Не совсем понял проблему из описания -- может раскрыть подробнее?

2024-03-24 16:38 UTC, incubos commented on src/main/java/ru/vk/itmo/test/vadimershov/wrk/result3/report.md
> +Можно было бы как-то из заголовка запроса вычитывать, что этот запрос пришел из другой ноды, а не из клиента, и сразу начинать поиск
Хорошая идея -- зачем делать ненужную работу.

2024-03-25 14:26 UTC, vadim01er commented on src/main/java/ru/vk/itmo/test/vadimershov/hash/ConsistentHashing.java
> +            int existingReplicas = countReplicas(currentUrl);
да, как то для себя сделал эти подсчеты, убираю. Оставлю только индекс j

2024-03-25 14:48 UTC, vadim01er commented on src/main/java/ru/vk/itmo/test/vadimershov/wrk/result3/report.md
> +и мне пришлось изменить количество коннектов wrk до 64, так как не выделялись коннекты к смежным нодам.
Проблема была в тем что когда шла нагрзука на сервис, у меня коннекты для смежных нод не создавались и выпадала ошибка

2024-03-31 11:09 UTC, incubos approved these changes
Есть несколько небольших замечаний. 13 баллов.

2024-03-31 11:09 UTC, incubos commented on src/main/java/ru/vk/itmo/test/vadimershov/wrk/result3/report.md
> +и мне пришлось изменить количество коннектов wrk до 64, так как не выделялись коннекты к смежным нодам.
Всё равно непонятно -- в чём была причина?

2024-03-31 11:09 UTC, merged