Stage 3, Андрей Чешев, Политех
polis-vk/2024-highload-dht pull request #116
Opened 2024-03-13 22:01 UTC by Queenore

2024-03-17 20:27 UTC, Marashov-Alexander requested changes
Накинул несколько пожеланий. Удачи в исправлениях и составлении отчетов!
Кстати, отпишитесь, пожалуйста, удалось ли вам в итоге добиться улучшения производительности во втором этапе? В чем была ваша проблема и чем удалось ее решить?

2024-03-17 20:27 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/ServiceImpl.java
> +        Collections.sort(clusterUrls);
изменять входную коллекцию - ну такое) С одной стороны её могут подсунуть иммутабельную, а с другой - вызывающий код может не ожидать такой подставы :) Лучше создать новую коллекцию на основе полученной

2024-03-17 20:27 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/ServiceImpl.java
> +    private final Map<Integer, HttpClient> clusterConnections;
нужно ли закрывать httpClient'ы?

2024-03-17 20:27 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/ServiceImpl.java
> +    private final Map<Integer, HttpClient> clusterConnections;
кстати, а можно ли здесь обойтись обычным массивом? Для чего именно мапа? Если нумерацию с нуля сделать, например

2024-03-17 20:52 UTC, Queenore commented on src/main/java/ru/vk/itmo/test/andreycheshev/DataDistributor.java
> +    private int stringToIntKey(String stringKey) {
да, это было ошибкой (в частности для строк "ab" и "ba" получится один и тот же результат)

2024-03-17 20:59 UTC, Queenore commented
По поводу второго этапа я учел все ваши замечания и подправил ![отчет](https://github.com/polis-vk/2024-highload-dht/pull/76). Наилучших результатов удалось добиться изменненными параметрами (для put в частности измененным погом флаша).

2024-03-18 17:47 UTC, Queenore commented
> Накинул несколько пожеланий. Удачи в исправлениях и составлении отчетов! Кстати, отпишитесь, пожалуйста, удалось ли вам в итоге добиться улучшения производительности во втором этапе? В чем была ваша проблема и чем удалось ее решить?
По поводу второго этапа я учел все ваши замечания и подправил https://github.com/polis-vk/2024-highload-dht/pull/76. Наилучших результатов удалось добиться изменненными параметрами (для put, в частности, измененным погом флаша).

2024-03-21 00:45 UTC, Queenore commented
[Отчет](https://github.com/polis-vk/2024-highload-dht/blob/d653a8e9e982611edc4291dfd166929d8a79a850/src/main/java/ru/vk/itmo/test/andreycheshev/lab3/report-3-Cheshev.md)

2024-03-24 19:33 UTC, Marashov-Alexander approved these changes
14/15. Снял балл за пару вопросов к отчету, остальное норм

2024-03-24 19:33 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/lab3/report-3-Cheshev.md
В целом неплохо,
Из пожеланий - было бы круто добавлять выводы по происходящему, например, итоговые выводы по всему третьему этапу: стало ли хуже в сравнении со вторым, в чем стало хуже и почему, ожидаемые ли это результаты

2024-03-24 19:33 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/RequestHandler.java
> +    static {
возможно есть смысл отнести ближе к availableMethods, а еще назвать эту переменную ВОТ_ТАК_ВОТ) 
И в принципе можно использовать например стримы для заполнения, а также сделать коллекцию иммутабельной от греха подальше

2024-03-24 19:33 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/lab3/report-3-Cheshev.md
> +    * Здесь ситуация аналогичная: основная аллокация - массив byte[] для отправки запроса на другую ноду.
можно ли что-то с этим сделать?

2024-03-24 21:18 UTC, Queenore commented
На неделе обязательно внесу правки в код, дополню отчет.

2024-04-03 18:47 UTC, Queenore commented on src/main/java/ru/vk/itmo/test/andreycheshev/lab3/report-3-Cheshev.md
> +    * Здесь ситуация аналогичная: основная аллокация - массив byte[] для отправки запроса на другую ноду.
Я неверно проанализировал. Эта аллокация происходит при чтении ответа при перенаправлении запроса на другую ноду. По этой причине избавиться от этой аллокации не представляется возможным

2024-04-03 19:06 UTC, Queenore commented
Учел ваши замечания, внес правки.

2024-04-06 14:13 UTC, merged