Аленькова Юлия ИТМО DWS Stage3
polis-vk/2024-highload-dht pull request #117
Opened 2024-03-13 23:04 UTC by yulalenk

Отчет в процессе

2024-03-24 18:09 UTC, incubos requested changes
Есть ряд вопросов и замечаний. Ждём исправлений и ответов перед merge.

2024-03-24 18:09 UTC, incubos commented on src/main/java/ru/vk/itmo/test/alenkovayulya/reports/report_stage3.md
> +Попробуем найти точки разладки для put и get нагрузок при тех же размерах пула(32) и очереди(128) и тех же параметрах wrk (64 коннекшена), что и для 2 этапа, и сравним.
Поменяли же параметры, разве нет?

2024-03-24 18:09 UTC, incubos commented on src/main/java/ru/vk/itmo/test/alenkovayulya/reports/report_stage3.md
> +Смотря на семлы, хочется ответить что 10.50% занимаем редирект на другую шарду, а лидирует по съеденному времени, как и в предыдущем этапе, ThreadPoolExecutor.getTask() - 34.95%
Только судя по упоминанию `ForkJoinPool`, `getTask()` выполняет не только наши старые задачи, верно?

2024-03-24 18:09 UTC, incubos commented on src/main/java/ru/vk/itmo/test/alenkovayulya/reports/report_stage3.md
> +Здесь, ожидаемо, можно заметить много аллокаций, связанных с проксированием запросов другой шарде - 48.32% на send из HttpClientImpl
Можете прокомментировать также левую часть flamegraph, где появились новые аллокации? Нужен полный системный анализ.

2024-03-24 18:09 UTC, incubos commented on src/main/java/ru/vk/itmo/test/alenkovayulya/reports/report_stage3.md
> +Согласно полученныи результатам профилирования, узкое место нашего приложение  - сетевое взаимодействие между шардами.
Есть идеи, как соптимизировать сетевое взаимодействие?

2024-03-28 07:24 UTC, yulalenk commented
> Есть ряд вопросов и замечаний. Ждём исправлений и ответов перед merge.

Сделаю все исправления и отвечу на вопросы 29.03

2024-03-30 17:44 UTC, yulalenk commented on src/main/java/ru/vk/itmo/test/alenkovayulya/reports/report_stage3.md
> +Попробуем найти точки разладки для put и get нагрузок при тех же размерах пула(32) и очереди(128) и тех же параметрах wrk (64 коннекшена), что и для 2 этапа, и сравним.
Нет, видимо просто в запушила в какой-то момент другие. 
Опираясь на отчет 2 этапа, сначала были найдены оптимальные параметры для размера пула потоков и очереди(32 и 128 соответсвенно) при нагрузке в 64 коннекшена, а дальше профилирование проводилось с ними.

2024-03-30 18:03 UTC, yulalenk commented on src/main/java/ru/vk/itmo/test/alenkovayulya/reports/report_stage3.md
> +Согласно полученныи результатам профилирования, узкое место нашего приложение  - сетевое взаимодействие между шардами.
Как мне кажется, в первую очередь необходимо избавить от синхронных ожиданий ответа от другой шарды. 
Это можно сделать или редиректом напрямую(то есть чтобы нода с нужными данными возвращала ответ клиенту), или прикрутив асинхронную обработку запросов.

Как альтернатива, можно попробовать для каждой шарды использовать своего http client-а, чтобы не блокировать других воркеров, пока текущий ждет ответа.

Кроме того, есть идея добавить балансировщик перед узлами нашего кластера с алгоритмом определения нужной шарды. 

Еще одно улучшение, которое я реализовала для 4 этапа, заключается в том, чтобы помечать в заголовке redirected запрос, чтобы не активировать процесс определения принадлежности данных шарде и сразу начинать поиск.

2024-03-31 11:18 UTC, incubos approved these changes
Не все замечания исправлены. 10 баллов.

2024-03-31 11:18 UTC, merged