Свистухин Андрей, ИТМО DWS, Stage 3
polis-vk/2024-highload-dht pull request #121
Opened 2024-03-14 10:46 UTC by stormrvge

2024-03-20 20:55 UTC, stormrvge commented
Подмержу мэйн, чтобы конфликты разрезолвить. Пытался только что это сделать, но на мерже зависла идея раза три))

2024-03-24 15:40 UTC, incubos commented
> Подмержу мэйн, чтобы конфликты разрезолвить. Пытался только что это сделать, но на мерже зависла идея раза три))

Попробуйте через консоль или средствами GitHub.

2024-03-24 17:18 UTC, incubos requested changes
Есть ряд замечаний и вопросов. Ждём исправлений и ответов перед merge.

2024-03-24 17:18 UTC, incubos commented on src/main/java/ru/vk/itmo/test/asvistukhin/ProxyRequestHandler.java
> +        return hashRing.get(hash);
Тут прячется несколько (un)boxingов, количество которых хотелось бы минимизировать.

2024-03-24 17:18 UTC, incubos commented on src/main/java/ru/vk/itmo/test/asvistukhin/reports/stage3.md
> +      36.319     0.825000       409850         5.71
`Detailed Percentil spectrum` можно не приводить -- перцентилей выше достаточно.

2024-03-24 17:18 UTC, incubos commented on src/main/java/ru/vk/itmo/test/asvistukhin/reports/stage3.md
> +заголовков для запроса. Также, 28% на потоки чтения запроса. Остальное же не поменялось по сравнению с прошлым этапом.
Жесть, почти все аллокации из-за HTTP клиента...

2024-03-24 17:18 UTC, incubos commented on src/main/java/ru/vk/itmo/test/asvistukhin/reports/stage3.md
> +у нас очень сильно выигрывает операция чтения данных, так как нам не нужно перемалывать кучу таблиц в поиске значения.
Не совсем понятна логика рассуждений -- по сути, ёмкость кластера в 3 раза больше одной ноды, поэтому, может, просто надо больше данных?

2024-03-24 17:18 UTC, incubos commented on src/main/java/ru/vk/itmo/test/asvistukhin/reports/stage3.md
> +В остальном же, значения такие же как и в прошлом этапе.
Остальное -- это что именно?

2024-03-24 17:18 UTC, incubos commented on src/main/java/ru/vk/itmo/test/asvistukhin/reports/stage3.md
> +27% ушло на обработку потоков для чтения ответа другой ноды. Также, 56% теперь ест создание запроса к ноде. И сейчас,
Не "на обработку потоков для чтения ответа", а на аллокации при разборе HTTP ответа, верно?

2024-03-24 17:18 UTC, incubos commented on src/main/java/ru/vk/itmo/test/asvistukhin/reports/stage3.md
> +Остальное - так же, как и в прошлом этапе.
Что именно остальное? Вы прямо сравнивали? :)

2024-03-24 17:18 UTC, incubos commented on src/main/java/ru/vk/itmo/test/asvistukhin/reports/stage3.md
> +случае RPS упал с 40000 до 10000. С чтением же наоборот - это долгая операция, которая перемалывает кучу таблиц в поиске записи. Шардирование
Есть идеи, как соптимизировать запись?

2024-03-25 14:44 UTC, stormrvge commented on src/main/java/ru/vk/itmo/test/asvistukhin/ServiceImpl.java
> +public class ServiceImpl implements ru.vk.itmo.Service {
Изначально назвал класс Service, и потом идея импорт сама вставила при разработке. Исправил.

2024-03-25 14:46 UTC, stormrvge commented on src/main/java/ru/vk/itmo/test/asvistukhin/ServiceImpl.java
> +        server.addRequestHandlers(this);
Хм, думал что наоборот вынести их в отдельный класс будет хорошее решение. А если у нас допустим 10 разных по функциональности сервисов, из которых в каждом по 5 ручек, мы же не будем в сам класс сервера добавлять 50 обработчиков на ручку?

Или всё-таки, лучше перенести их в класс сервера?

2024-03-25 14:47 UTC, stormrvge commented on src/main/java/ru/vk/itmo/test/asvistukhin/ServiceImpl.java
> +        proxyRequestHandler.close();
не заметил, исправил

2024-03-25 14:48 UTC, stormrvge commented on src/main/java/ru/vk/itmo/test/asvistukhin/ServerImpl.java
> +                String response = ex.getClass() == HttpException.class ? Response.BAD_REQUEST : Response.INTERNAL_ERROR;
Исправил

2024-03-25 14:52 UTC, stormrvge commented on src/main/java/ru/vk/itmo/test/asvistukhin/reports/stage3.md
> +у нас очень сильно выигрывает операция чтения данных, так как нам не нужно перемалывать кучу таблиц в поиске значения.
Нет, я к тому, что один кластер отвечает за меньшее количество данных. И независимо от того, сколько данных лежит на самом кластере, мы обрабатываем именно SS-tables, которые относятся к определенной ноде. Например, у нас записано на кластере 10.000.000.000 SS таблиц, и на кластере у нас вшито, что всегда работает 10 нод. В этом случае, определенная нода будет искать не среди 10.000.000.000 нод, а среди 1.000.000.000. Кажется, что такая разница при бинарном поиске незначительна, но при чтении диска, разница ощущается даже на таких небольших объемах, которые были на нагрузочном тестировании (500MB данных)

2024-03-25 14:55 UTC, stormrvge commented on src/main/java/ru/vk/itmo/test/asvistukhin/reports/stage3.md
> +В остальном же, значения такие же как и в прошлом этапе.
https://github.com/stormrvge/2024-highload-dht/blob/lab2/src/main/java/ru/vk/itmo/test/asvistukhin/reports/stage2.md

Я во втором этапе указывал, сколько процессорного времени съедает каждая операция. 

59% времени на метод MemorySegmentUtils.indexOf(). Из которых 34% занимает MemorySegment.mismatch().
9% времени уходит на создание списка итераторов для операции get
8% времени на взятие задачи из очереди
6% времени на процессинг запроса (чтение/парсинг)
6% времени на отправку ответа
0.5% занимал garbage collector

понятное дело, что проценты не один в один как во второй лабораторной, из-за того, что добавились запросы по сети, которые занимают много времени, пропорционально этому и снизились проценты на эти операции. Но если прикинуть на глаз, то они съедают столько же времени, сколько и съедали до этого

2024-03-25 14:59 UTC, stormrvge commented on src/main/java/ru/vk/itmo/test/asvistukhin/reports/stage3.md
> +27% ушло на обработку потоков для чтения ответа другой ноды. Также, 56% теперь ест создание запроса к ноде. И сейчас,
Да, неправильно написал. 27% ушло в целом на поток, в котором мы аллоцировали память на разбор HTTP ответа. 17% ушло на чтение заголовков, 6% на чтение тела ответа, 4%, насколько я понял, на ожидание ответа

2024-03-25 15:01 UTC, stormrvge commented on src/main/java/ru/vk/itmo/test/asvistukhin/reports/stage3.md
> +Остальное - так же, как и в прошлом этапе.
Да, я просто смотрел сколько занимают операции из прошлого этапа сейчас. Пытался прикинуть +- в какой пропорции изменились проценты из-за новых прокси запросов, которые начали съедать много процентов, и уже в зависимости от этого подсчитывал, изменились ли операции, которые были в прошлом этапе

2024-03-25 15:07 UTC, stormrvge commented on src/main/java/ru/vk/itmo/test/asvistukhin/reports/stage3.md
> +Остальное - так же, как и в прошлом этапе.
Это не совсем, чтобы прямо считал.
Пример:
1) В прошлом этапе у нас был всего один метод А который съедал 100% процессорного времени (допустим это 1 секунда)
2) В текущем этапе у нас появился ещё метод B. Теперь метод А съедает 50% процессорного времени, и метод B съедает 50% процессорного времени. Но в любом случае, метод А съедает также 1 секунду времени, и исходя из этого можно посчитать, сильно ли изменилось время выполнения.

На самом деле, пока это писал, я понял, что эти методы тоже могли измениться по времени выполнения. По идее, я считал с немалой погрешностью (если так вообще можно делать). Наверное, в таком случае, лучше считать в сэмплах, нежели в процентах?

2024-03-25 15:30 UTC, stormrvge commented on src/main/java/ru/vk/itmo/test/asvistukhin/reports/stage3.md
> +случае RPS упал с 40000 до 10000. С чтением же наоборот - это долгая операция, которая перемалывает кучу таблиц в поиске записи. Шардирование
Сохранять запись в кеш, чтобы потом батчем разослать на другие инстансы мы не можем, так как при обращении к другой ноде - она по ключу найдет нужную ноду, обратится к ней, а в ней записи не будет.

А как ещё можно оптимизировать сам запрос к другой ноде? Мы же и тратим как раз процессор на то, чтобы отправить запрос и получить ответ. Если честно, придумать как оптимизировать в рамках данной лабораторной - что-то не выходит. Как вариант - делать реплицирование, чтобы у нас на одной ноде также хранились ключи, которые изначально должны лежать на другой ноде. Но при этом мы должны в разы (в зависимости от количества нод и степени реплицирования) увеличить потребление памяти.

А подскажите, как это можно оптимизировать?

2024-03-25 15:31 UTC, stormrvge commented
@incubos конфликты разрезолвил, на вопросы ответил, пофиксил о чем Вы писали. Ещё задал один вопрос по оптимизации, буду благодарен если подскажете или расскажете

2024-03-31 11:24 UTC, incubos commented on src/main/java/ru/vk/itmo/test/asvistukhin/ServiceImpl.java
> +        server.addRequestHandlers(this);
Отдельные классы выглядят норм, а обработка HTTP запросов в сервисе (а не в сервере или отдельных классов) -- сомнительно.

2024-03-31 11:50 UTC, incubos commented on src/main/java/ru/vk/itmo/test/asvistukhin/ProxyRequestHandler.java
> +        hash = tailMap.isEmpty() ? hashRing.firstKey() : tailMap.firstKey();
Предлагаю посмотреть на метод `firstEntry()`, чтобы не платить логарифмическим поиском ещё раз ниже.

2024-03-31 11:50 UTC, incubos commented on src/main/java/ru/vk/itmo/test/asvistukhin/reports/stage3.md
> +Остальное - так же, как и в прошлом этапе.
Да, в сэмплах выглядит разумнее, потому что раньше новых сэмплов просто не было, верно?

2024-03-31 11:52 UTC, incubos commented on src/main/java/ru/vk/itmo/test/asvistukhin/reports/stage3.md
> +случае RPS упал с 40000 до 10000. С чтением же наоборот - это долгая операция, которая перемалывает кучу таблиц в поиске записи. Шардирование
Попробуем оптимизнуть на 5 этапе и вернёмся к этому вопросу. Но без замены HTTP на что-то более эффективное профита будет мало.

2024-03-31 11:54 UTC, incubos approved these changes
14 баллов.

2024-03-31 11:54 UTC, merged