Бандурин Владислав, ИТМО ФИТиП М3332, HW3
polis-vk/2024-highload-dht pull request #125
Opened 2024-03-14 14:31 UTC by vbandurin7

Code refactoring and report in process..

2024-03-17 16:19 UTC, AlexeyShik requested changes
Надо сделать consistent hashing или рандеву.
Предлагаю в анализе посмотреть еще на равномерность распределения данных по узлам в зависимости от функции шардирования.

2024-03-17 16:19 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/test/bandurinvladislav/Server.java
> +        if (client != null) {
Неинтуитивное условие `client != null`. Из кода понятно, что это случай локального вызова метода. Но будет приятнее, если случай удаленного вызова будет отделен от локального, потому что удаленный вызов имеет очень общий код, и он будет нарастать по мере новых дз.

2024-03-17 16:19 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/test/bandurinvladislav/Server.java
> +                return client.get(Constants.ENDPOINT + "?id=" + id);
Что будет, если один шард не отвечает на запросы? Правда, что в таком случае все потоки встанут в бесконечное ожидание и ни один запрос не сможет выполниться?

2024-03-17 16:19 UTC, AlexeyShik commented on src/test/java/ru/vk/itmo/ServiceInfo.java
> -}
Странный дифф, лучше убрать

2024-03-17 16:19 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/test/bandurinvladislav/Server.java
> +        int nodeNumber = key.hashCode() % size;
А еще в дз просили консистент хешинг или рандеву 

"Реализуйте один из алгоритмов распределения данных между узлами, например, [consistent hashing](https://en.wikipedia.org/wiki/Consistent_hashing), [rendezvous hashing](https://en.wikipedia.org/wiki/Rendezvous_hashing) или что-то другое по согласованию с преподавателем."

2024-03-20 17:34 UTC, vbandurin7 commented on src/test/java/ru/vk/itmo/ServiceInfo.java
> -}
убрал

2024-03-20 17:35 UTC, vbandurin7 commented on src/main/java/ru/vk/itmo/test/bandurinvladislav/Server.java
> +        if (client != null) {
Исправил

2024-03-24 16:10 UTC, AlexeyShik approved these changes
Все хорошо, но вопросы обсудить будет полезно.
Поставлю 14 баллов, потому что таймаута не было в изначальном решении, это довольно важно.

2024-03-24 16:10 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/test/bandurinvladislav/results/stage3/report.md
> +В сравнении с прошлыми этапами, большую долю аллокаций теперь составляет выделение _byte[]_ при создании _ResponseReader_.
Как можно уменьшить число этих аллокаций?

2024-04-01 16:19 UTC, AlexeyShik commented
Так как есть конфликты, я pr закрою через close

2024-04-01 16:19 UTC, closed without merging

2024-04-03 14:37 UTC, vbandurin7 commented on src/main/java/ru/vk/itmo/test/bandurinvladislav/Server.java
> +                    client.setTimeout(100);
Из соображений, сколько приемлемо ждать ответ на запрос. Если сервер отвечает в худшем случае 30 мс, то наверное 100 это уже перебор

2024-04-03 14:38 UTC, vbandurin7 commented on src/main/java/ru/vk/itmo/test/bandurinvladislav/results/stage3/report.md
> +В сравнении с прошлыми этапами, большую долю аллокаций теперь составляет выделение _byte[]_ при создании _ResponseReader_.
Подумаю и постараюсь в следующем этапе поправить