Аленькова Юлия ИТМО DWS Stage1
polis-vk/2024-highload-dht pull request #13
Opened 2024-02-18 18:21 UTC by yulalenk

2024-02-25 10:17 UTC, atimofeyev commented
поправьте замечания коде CodeClimate пожаоуйста

2024-02-25 10:26 UTC, atimofeyev requested changes

2024-02-25 10:26 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/alenkovayulya/ServerImpl.java
> +    private final ReferenceDao referenceDao;
лучше использовать более общий тип - интерфейс

2024-02-25 10:26 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/alenkovayulya/ServerImpl.java
> +    public ServerImpl(ServiceConfig serviceConfig, ReferenceDao referenceDao) throws IOException {
надо добавить обработку неожиданных ошибок

2024-02-25 10:26 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/alenkovayulya/ServerImpl.java
> +            case "GET", "PUT", "DELETE" -> session.sendResponse(new Response(Response.BAD_REQUEST, Response.EMPTY));
А для сего тут "GET", "PUT", "DELETE"?

2024-02-25 10:26 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/alenkovayulya/ServerImpl.java
> +            referenceDao.close();
Закрывать referenceDao лучше там же где оно и создается

2024-02-25 10:26 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/alenkovayulya/ServiceImpl.java
> +    public CompletableFuture<Void> start() throws IOException {
старт/стоп лучше сделать synchronized

2024-02-25 11:51 UTC, yulalenk commented
> поправьте замечания коде CodeClimate пожалуйста

Замечания исправлены, CodeClimate проверка проходит

2024-03-01 22:38 UTC, atimofeyev approved these changes

2024-03-01 22:40 UTC, merged