Прокопьев Никита / ИТМО DWS / Stage 4
polis-vk/2024-highload-dht pull request #130
Opened 2024-03-23 19:31 UTC by Nikpro200125

only code

2024-04-07 15:33 UTC, incubos requested changes
Необходимо зарезолвить конфликты перед merge.

2024-04-07 18:16 UTC, incubos requested changes
Есть ряд вопросов и замечаний, в т.ч. существенное несоответствие спецификации -- нужно исправлять и придётся перемерять нагрузочное тестирование :( Также необходимо исправить конфликты перед merge.

2024-04-07 18:16 UTC, incubos commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
> +                session.scheduleClose();
`logIOExceptionAndCloseSession()`?

2024-04-07 18:16 UTC, incubos commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
> +                session.scheduleClose();
`logIOExceptionAndCloseSession()`?

2024-04-07 18:16 UTC, incubos commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
> +        if (body != null && notFoundResponsesCount != responses.size()) {
Зачем второе условие? Разве может быть `body` и при этом все ответы 404?
```suggestion
        if (body != null) {
```

2024-04-07 18:16 UTC, incubos commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
> +        if (body != null && notFoundResponsesCount != responses.size()) {
И нужен ли вообще тогда счётчик `notFoundResponsesCount`?

2024-04-07 18:16 UTC, incubos commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
> +            }
Логика выглядит запутанной -- хотелось бы более прямолинейно без вложенных `if`ов.

2024-04-07 18:16 UTC, incubos commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
> +            }
Эта реализация не соответствует спецификации: мы **обязаны** отправить запросы на `from` нод, а для успеха необходимо собрать `ack` ответов. Сейчас мы не отправляем запросы, если получили `ack` ответов.

2024-04-07 18:16 UTC, incubos commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/analysis/stage4/reports/stage4.md
> +Предполагается, что если установить ack в 1, то производительность увеличится, так как запросы будут ждать только одного успеха и не будут блокировать потоки дальше.
Текущая реализация не соответствует спецификации -- см. комментарии к `MyServer`.

2024-04-07 18:16 UTC, incubos commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/analysis/stage4/reports/stage4.md
> +* Для ускорения работы пула воркеров можно поискать более оптимальную структуру данных для очереди задач воркеров, которая бы затрачивала меньше времени на блокировки, что особенно актуально для get-
Можете пояснить "появление очереди задач" -- очереди раньше разве не было?

2024-04-07 18:21 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/dao/BaseEntry.java
> +        return "{" + key + ":" + value + "}";
Да, функционально не влияло, забыл добавить

2024-04-07 20:26 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/dao/BaseEntry.java
> +        return "{" + key + ":" + value + "}";
Исправил.

2024-04-07 20:26 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/dao/SSTable.java
> +            final long timestamp = getLength(offset);
Исправил.

2024-04-07 20:26 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
> +    private static final String HEADER_TIMESTAMP = "X-Timestamp: ";
Исправил.

2024-04-07 20:26 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/RequestHandler.java
> +        List<HttpRequest> httpRequests = new ArrayList<>();
Исправил.

2024-04-07 20:26 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/RequestHandler.java
> +                httpRequests.add(null);
Исправил. Использую header для пометки внутреннего запроса

2024-04-07 20:27 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/RequestHandler.java
> +    public List<HttpRequest> createRequests(
Исправил.

2024-04-07 20:27 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
> +        } catch (IllegalArgumentException e) {
Исправил.

2024-04-07 20:27 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
> +        } catch (Exception e) {
Исправил. Видимо осталось от предыдущей реализации

2024-04-07 20:27 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
>      private static final long MAX_RESPONSE_TIME = TimeUnit.SECONDS.toMillis(1);
Исправил.

2024-04-07 20:27 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/RequestHandler.java
> +            Request request, String key, List<String> targetNodes, ServiceConfig serviceConfig) {
Исправил.

2024-04-07 20:28 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
> +        if (responses.isEmpty() || responses.size() < ack) {
Исправил.

2024-04-07 20:28 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
> +        List<Response> responses = new ArrayList<>();
Исправил.

2024-04-07 20:28 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
> +        }
Исправил.

2024-04-07 20:28 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/RequestHandler.java
> +        Entry<MemorySegment> entry = new BaseEntry<>(msKey, null, System.currentTimeMillis());
Исправил. Вычисляю при подготовке запросов и отправляю в header timestamp

2024-04-07 20:29 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/RequestHandler.java
> +        Entry<MemorySegment> entry = new BaseEntry<>(msKey, MemorySegment.ofArray(body), System.currentTimeMillis());
Исправил.

2024-04-07 20:29 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
> +            log.error("Exception while sending request", e);
Исправил.

2024-04-07 20:29 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
> +        long timestamp = response.headers().map().containsKey("x-timestamp")
Исправил.

2024-04-07 20:29 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
> +                .collect(Collectors.toList());
Исправил. Удаляю последний, если количество больше from

2024-04-07 20:30 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
> +                session.scheduleClose();
Исправил.

2024-04-07 20:30 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
> +                session.scheduleClose();
Исправил.

2024-04-07 20:30 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
> +        if (body != null && notFoundResponsesCount != responses.size()) {
Исправил. Убрал, не нужен

2024-04-07 20:30 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
> +            }
Исправил. Упростил

2024-04-07 20:31 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
> +            }
Исправил. Убрал проверку на успешные результаты, но оставил на неудачи, вроде это не ломает логику

2024-04-09 11:10 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/analysis/stage4/reports/stage4.md
> +Предполагается, что если установить ack в 1, то производительность увеличится, так как запросы будут ждать только одного успеха и не будут блокировать потоки дальше.
Исправил. Перемерил wrk , значения теперь выравнились при любом ack, что логично.

2024-04-09 11:15 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/analysis/stage4/reports/stage4.md
> +* Для ускорения работы пула воркеров можно поискать более оптимальную структуру данных для очереди задач воркеров, которая бы затрачивала меньше времени на блокировки, что особенно актуально для get-
Все верно, очередь была и раньше, это предложение относится не конкретно к данному этапу, а в целом к нашей системе

2024-04-09 14:09 UTC, vladimir-bf approved these changes
15

2024-04-14 15:25 UTC, incubos approved these changes

2024-04-14 15:25 UTC, merged