HW4 Чеботин Александр (ITMO DWS)
polis-vk/2024-highload-dht pull request #133
Opened 2024-03-24 17:00 UTC by axothy

Пока еще не делал нагрузочное тестирование и профилирование

2024-04-08 20:35 UTC, atimofeyev requested changes

2024-04-08 20:35 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/chebotinalexandr/StorageServer.java
> +            if (enough && httpMethod == Request.METHOD_GET) {
зачем вы разнесли логику из метода compareReplicasResponses?
пост и пут там, а гет тут

2024-04-08 20:35 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/chebotinalexandr/StorageServer.java
> +            String timestampHeader = response.getHeaders()[response.getHeaderCount() - 1];
а почему вы считаете что в этом месте будет лежать timestamp header?

2024-04-08 20:35 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/chebotinalexandr/StorageServer.java
> +        Pattern pattern = Pattern.compile("\\d+");
слишком тяжелое оружие для того чтобы распарсить число, лучше бы было просто сделать parseLong()

2024-04-08 20:35 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/chebotinalexandr/report/stage4.md
> +А сейчас, чем больше задач приходит воркерам, тем больше локов.
а если сделать больше воркеров? Можно же попробовать как-то улучшить производительность и без асинхронных запросов, если не хватает воркеров - можно попробовать увеличить число воркеров

2024-04-23 19:39 UTC, axothy commented on src/main/java/ru/vk/itmo/test/chebotinalexandr/StorageServer.java
> +        long timestamp = System.currentTimeMillis();
Исправлено

2024-04-23 19:40 UTC, axothy commented on src/main/java/ru/vk/itmo/test/chebotinalexandr/StorageServer.java
> +                remote(request, timestamp, nodeIndex, responses);
Исправил, теперь список не передается

2024-04-23 19:40 UTC, axothy commented on src/main/java/ru/vk/itmo/test/chebotinalexandr/StorageServer.java
> +        this.httpClient = HttpClient.newHttpClient();
Попробовал подтюнить

2024-04-23 19:40 UTC, axothy commented on src/main/java/ru/vk/itmo/test/chebotinalexandr/StorageServer.java
> +            if (enough && httpMethod == Request.METHOD_GET) {
Исправлено

2024-04-23 19:41 UTC, axothy commented on src/main/java/ru/vk/itmo/test/chebotinalexandr/StorageServer.java
> +            String timestampHeader = response.getHeaders()[response.getHeaderCount() - 1];
Да, это может поломаться. Исправил, теперь header достаю через `getHeader(String key)`

2024-04-23 19:41 UTC, axothy commented on src/main/java/ru/vk/itmo/test/chebotinalexandr/StorageServer.java
> +        Pattern pattern = Pattern.compile("\\d+");
Исправил, теперь нет `Pattern` и нет `Matcher`

2024-04-28 17:31 UTC, axothy commented
@atimofeyev Можете пожалуйста оценить работу ? Замечания исправил по коду

2024-04-29 20:49 UTC, atimofeyev approved these changes

2024-04-29 20:53 UTC, atimofeyev approved these changes

2024-04-29 20:53 UTC, merged