HW 4 Шишигин Степан DWS ITMO
polis-vk/2024-highload-dht pull request #140
Opened 2024-03-27 19:52 UTC by sshishigin

2024-04-09 13:20 UTC, atimofeyev requested changes

2024-04-09 13:20 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/shishiginstepan/profiling/profiling4.MD
> +1. Интересно и не просто было спустя столько времени залезть в Dao и добавить поддержку сохранения временных меток на диск
но не в memtable, что привело к бесполезности всей заети

2024-04-09 13:20 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/shishiginstepan/profiling/profiling4.MD
> +Поддерживать абстракцию в виде интерфейса Dao стало невозможно из-за появившихся параметров и мой код к сожалению стал больше похож на спагетти. В основном считаю что справился неплохо.
полностью согласен, такой код тяжело будет дальше развивать, я бы рекомендовал подумать над другими абстракциями.
DAO - управляет своими данными
Уровень выше - управляет репликами и зппросами к ним, обработкой ответов

2024-04-09 13:20 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/shishiginstepan/profiling/profiling4.MD
> +Репликация заметно повлияла как на цпу нагрузку, так как теперь ноды в n раз чаще должны искать в dao записи (где N это коеф. репликации выбранный клиентом). Очевидной становится потребность в асинхр
как асинхронные вызовы помогут нам снизить нагрузку на CPU?

2024-04-09 20:06 UTC, sshishigin commented on src/main/java/ru/vk/itmo/test/shishiginstepan/dao/InMemDaoImpl.java
> +    public void upsert(EntryWithTimestamp<MemorySegment> entry) {
Почему не учитываю? В этом энтри есть таймстемп, время будет учтено. Или речь идет о том что в мемтейбле уже может быть более свежий ключ?

2024-04-09 20:13 UTC, sshishigin commented on src/main/java/ru/vk/itmo/test/shishiginstepan/server/Server.java
> +            @Param(value = "ack") String ack,
Не досмотрел. Но сделал интами, думаю лонг будет лишним.

2024-04-09 20:20 UTC, sshishigin commented on src/main/java/ru/vk/itmo/test/shishiginstepan/profiling/profiling4.MD
> +Репликация заметно повлияла как на цпу нагрузку, так как теперь ноды в n раз чаще должны искать в dao записи (где N это коеф. репликации выбранный клиентом). Очевидной становится потребность в асинхр
Нагрузку действительно снизить не получится, тут я не совсем корректно выразился. Но можно уменьшить время нахождения в блокирующем IO, что позволит понизить latency.

2024-04-09 20:21 UTC, sshishigin commented on src/main/java/ru/vk/itmo/test/shishiginstepan/profiling/profiling4.MD
> +Поддерживать абстракцию в виде интерфейса Dao стало невозможно из-за появившихся параметров и мой код к сожалению стал больше похож на спагетти. В основном считаю что справился неплохо.
Думаю придется пересмотреть абстракции, но боюсь что уже к следующему этапу.

2024-04-09 20:21 UTC, sshishigin commented on src/main/java/ru/vk/itmo/test/shishiginstepan/profiling/profiling4.MD
> +1. Интересно и не просто было спустя столько времени залезть в Dao и добавить поддержку сохранения временных меток на диск
Вопрос ранее задавал, если коротко - считаю что в мем таблице все-таки хранится таймстемп

2024-04-09 20:23 UTC, sshishigin commented on src/main/java/ru/vk/itmo/test/shishiginstepan/server/DistributedDao.java
> +            tokensOfChosenNodes.add(node.realNodeKey);
Не очень понимаю как я могу повлиять на расположение нод в кольце. На них влияет то как поведет себя хеш функция.

2024-04-09 20:27 UTC, sshishigin commented on src/main/java/ru/vk/itmo/test/shishiginstepan/server/DistributedDao.java
> +            if (tokensOfChosenNodes.contains(node.realNodeKey)) {
Поправил

2024-04-09 20:28 UTC, sshishigin commented on src/main/java/ru/vk/itmo/test/shishiginstepan/server/RemoteDaoNode.java
> +        String innerRequest = "X-inner-request: " + 1;
Бред написал, исправил)

2024-04-18 16:19 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/shishiginstepan/server/DistributedDao.java
> +            tokensOfChosenNodes.add(node.realNodeKey);
вот именно, вы сейчас чтобы определить N нод, не можете просто взять первую в ринге и взять следующие N - 1, а приходится бегать по кольцу и высчитывать.

Но в целом это не тривиальная задача, и один в один ваш подход на такое не перенести, но в реальных системах так и делается

2024-04-18 16:22 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/shishiginstepan/profiling/profiling4.MD
> +1. Интересно и не просто было спустя столько времени залезть в Dao и добавить поддержку сохранения временных меток на диск
то что он хранится - это да, но хранится то он для того чтобы использоваться )

2024-04-18 16:23 UTC, atimofeyev approved these changes

2024-04-18 16:38 UTC, merged