Коротких Виктор / ИТМО DWS / Stage 4
polis-vk/2024-highload-dht pull request #149
Opened 2024-03-28 13:07 UTC by vitekkor

2024-04-07 19:21 UTC, incubos requested changes
Есть вопросы и замечания. Ждём исправлений.

2024-04-07 19:21 UTC, incubos commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/LSMServerImpl.java
> +            final long requestTimestamp = Instant.now().toEpochMilli();
Лучше выписывать `timestamp` в одном месте (на координаторе) и передавать на все реплики -- что думаете?

2024-04-07 19:21 UTC, incubos commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/LSMServerImpl.java
>              log.info("Entity(id={}) was not found", idString);
Выглядит как `debug()`, а не `info()` -- согласны?

2024-04-07 19:21 UTC, incubos commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/LSMServerImpl.java
>              log.info("Entity(id={}) was not found", idString);
И в других местах тоже.

2024-04-07 19:21 UTC, incubos commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/LSMServerImpl.java
> +        if (clusterSize < 3) return clusterSize;
Зачем этот особый случай? Разве формула ниже не работает?

2024-04-07 19:21 UTC, incubos commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/LSMServerImpl.java
> +        Integer from = null;
Можем обойтись без boxing (и аллокаций)?

2024-04-07 19:21 UTC, incubos commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/LSMServerImpl.java
> +        if (ack == null ^ from == null) {
Исключающее или выглядит очень неидиоматично -- лучше писать явно:
```suggestion
        if (ack == null && from != null || ack != null && from == null) {
```

2024-04-07 19:21 UTC, incubos commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/LSMServerImpl.java
> +                .header(LsmServerUtil.TIMESTAMP_HEADER, String.valueOf(requestTimestamp));
Разве мы читаем этот заголовок на другой стороне?

2024-04-07 19:21 UTC, incubos commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/reports/stage4/report.md
> +реплицирования. При этом в некоторых случаях у нас нет локальной записи на ноду, на которую мы отправили запрос, и есть
У нас же дефолтная репликация 2 из 3, т.е. запросы всегда уходят на 3 ноды, а в кластере как раз 3 ноды, верно?

2024-04-07 19:21 UTC, incubos commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/reports/stage4/report.md
> +На профиле стало видно работу GC - 6.26% от общего числа сэмплов.
Можно раскрыть чуть подробнее -- кто и когда генерирует мусор и нагружает GC?

2024-04-07 19:21 UTC, incubos commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/reports/stage4/report.md
> +  Non-2xx or 3xx responses: 17980
Что это за ошибки?

2024-04-07 19:21 UTC, incubos commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/reports/stage4/report.md
> +Это связано с тем, что поиск по всем sstable осуществляется не на одной ноде, а на 2-х.
Не на двух, а на трёх, разве нет? Мы ведь собираем успешные ответы от всех нод, а затем их мёрджим?

2024-04-07 19:21 UTC, incubos commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/reports/stage4/report.md
> +// TODO
TODO?

2024-04-07 19:21 UTC, incubos commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/reports/stage4/report.md
> +сэмплы, связанные с работой HttpClient, кроме работы с очередью, так как основной пул потоков использует ту же очередь).
Можете пояснить про "ту же очередь"? У `HttpClient` ведь свой `ExecutorService` со своей очередью или я неправильно понял?

2024-04-07 19:21 UTC, incubos commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/reports/stage4/report.md
> +запросы, которые принадлежат другим нодам, уходили только на них, а теперь ещё есть 50% шанс (фактор репликации 2/3,
Разве шанс не 100%, т.е. 3 ноды в кластере и `from == 3`?

2024-04-07 19:21 UTC, incubos commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/reports/stage4/report.md
> +По профилю видно, что сравнение sstable было оптимизированно компилятором путём использования векторизиров. Скорее всего
Почему раньше не было векторизации -- есть идеи?

2024-04-07 19:25 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/reports/stage4/report.md
> +// TODO
Забыл удалить. Выводы по профилям там валидные

2024-04-07 19:48 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/ConsistentHashingManager.java
> +        return List.copyOf(replicas);
Хотелось лист получить тут, а не сет, но в целом судя по всему нам без особой разницы далее по чему итерироваться

2024-04-07 19:48 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/http/ReplicaEmptyResponse.java
> +        return new byte[0];
Согласен

2024-04-07 19:49 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/LSMServerImpl.java
> +        if (clusterSize < 3) return clusterSize;
Согласен, работает

2024-04-07 19:59 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/ConsistentHashingManager.java
> +        final Set<String> replicas = new LinkedHashSet<>(from, 1.f);
Идея была в том, чтобы у нас тут случайно при добавлении в сет очередной реплики не начала расширятся хешмапа. Мы же точно знаем, что больше from туда мы не будем складывать.

Это было чисто интуитивно основано на аналогичном подходе с какими-нибудь ArrayList.

2024-04-07 19:59 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/LSMServerImpl.java
> +            final long requestTimestamp = Instant.now().toEpochMilli();
Изначально был другой подход с локальной выпиской. После я его переделал на единую на координаторе, но видимо при рефакторинге не доглядел :(

2024-04-07 19:59 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/LSMServerImpl.java
> +                .header(LsmServerUtil.TIMESTAMP_HEADER, String.valueOf(requestTimestamp));
Исправил

2024-04-07 20:02 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/reports/stage4/report.md
> +запросы, которые принадлежат другим нодам, уходили только на них, а теперь ещё есть 50% шанс (фактор репликации 2/3,
Да, вы правы. Я тут просто зацепился во всём отчёте за то, что 2/3 значит если 2 ноды ответят, то всё гуд. Хотя конечно же мы отсылаем на все 3. Исправлю отчёт

2024-04-07 20:06 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/reports/stage4/report.md
> +  Non-2xx or 3xx responses: 17980
Иногда промахиваемся по ключу

2024-04-07 20:09 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/reports/stage4/report.md
> +реплицирования. При этом в некоторых случаях у нас нет локальной записи на ноду, на которую мы отправили запрос, и есть
Всё так. Исправил

2024-04-07 20:59 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/reports/stage4/report.md
> +сэмплы, связанные с работой HttpClient, кроме работы с очередью, так как основной пул потоков использует ту же очередь).
Я тут весьма косноязычно выразился. Абсолютно точно, что у нас 2 отдельных `ExecutorService` и очереди у них у каждого своя, это так. Но на профиле они, насколько я понял, схлопываются в один столбик, так как стек вызовов там одинаковый - я поискал по методу `take` и там только одно место, где видно сэмплы этого метода. Но не может быть такого, что один `ExecutorService` данный метод использует у очереди, а другой нет.  Если профилировать с опцией `-t`, то вероятно увидим разные потоки.

И в данном предложении я имел в виду, что складывать % сэмплов очереди, чтобы посчитать % для `HttpClient`, будет некорректно, ведь эти сэмплы принадлежат и  `ExecutorService`, который работает с selector тредами и забирает у них запросы на обработку

2024-04-14 13:32 UTC, vitekkor commented
@incubos Исправил замечания, добавил объяснение различным моментам, по которым возникли вопросы. Также провёл небольшой эксперимент с мульти-нагрузкой PUT и GET запросов

2024-04-14 15:31 UTC, incubos commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/ConsistentHashingManager.java
> +        final Set<String> replicas = new LinkedHashSet<>(from, 1.f);
Почему `LinkedHashSet`, а не просто `HashSet`?

2024-04-14 15:35 UTC, incubos approved these changes
15 баллов.

2024-04-14 15:35 UTC, merged

2024-05-14 07:19 UTC, vitekkor commented
@incubos Добрый день! На портале vk образование не была выставлена оценка за эту работу

2024-05-19 10:37 UTC, incubos commented
> @incubos Добрый день! На портале vk образование не была выставлена оценка за эту работу

Извиняюсь, проставил. Спасибо, что напомнили.