Решетников Алексей, ИТМО DWS, stage 4
polis-vk/2024-highload-dht pull request #150
Opened 2024-03-28 13:25 UTC by lehatheslayer

2024-04-07 20:04 UTC, atimofeyev requested changes
ряд признаков мне указывает на то что этот код вы писали не сами а с помощью помощью постороннего кода (по крайней мере ту часть, что отвечает за обработку нескольких реплик)

2024-04-07 20:04 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/reshetnikovaleksei/HttpServerImpl.java
> +            if (response.getStatus() < 500) {
а как же статус ошибки 429?

2024-04-07 20:04 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/reshetnikovaleksei/reports/stage4/stage4.md
> +В среднем производительность уменьшилась примерно в 15 раз, что в целом очевидно, так как запрос теперь рассылается
вот тут не понятно, реплики 3, а производительность уменьшилась в 15 раз, почему?

2024-04-07 20:13 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/reshetnikovaleksei/RequestRouter.java
> +        long timestamp = httpResponse.headers().firstValueAsLong(HTTP_TIMESTAMP_HEADER_NAME).orElse(0);
для чего мы тут проксируем хедер HTTP_TIMESTAMP_HEADER_NAME?

2024-04-08 10:38 UTC, lehatheslayer commented on src/main/java/ru/vk/itmo/test/reshetnikovaleksei/RequestRouter.java
> +        long timestamp = httpResponse.headers().firstValueAsLong(HTTP_TIMESTAMP_HEADER_NAME).orElse(0);
Для наглядности значения ключей хедеров:

```java
public static final String TIMESTAMP_HEADER_NAME = "X-Request-Timestamp";
public static final String HTTP_TIMESTAMP_HEADER_NAME = "x-request-timestamp";
public static final String REDIRECTED_REQUEST_HEADER_NAME = "X-Redirected-Request";
```

`TIMESTAMP_HEADER_NAME ` проставляется для передачи таймстемпа создания key-value записи у проксированных запросов (таймстемп используется для получения самой актуальной записи). Т.к. ручки орудуют при отправке ответа классом `one.nio.http.Response`, нужно распарсить полученный от `HttpClient` класс `java.net.http.HttpResponse`. Внутри объекта класса  `java.net.http.HttpResponse` все хедеры хранятся в lower-case представлении, из-за чего была создана константа `HTTP_TIMESTAMP_HEADER_NAME `. Соответственно, `HTTP_TIMESTAMP_HEADER_NAME` используется при парсе хедеров из `java.net.http.HttpResponse`

Наличие хедера `REDIRECTED_REQUEST_HEADER_NAME` в запросе говорит о том, что запрос проксирован на другую ноду

2024-04-08 10:44 UTC, lehatheslayer commented on src/main/java/ru/vk/itmo/test/reshetnikovaleksei/HttpServerImpl.java
> +                            Long.parseLong(r.getHeader(TIMESTAMP_HEADER_NAME + ": "))));
не думаю, что вытягивание хедера и парс в лонг прям много ресурсов будет забирать (что в принципе и видно в результатах профайлера)
в совокупности с вытягиванием хедера и парсом лонга, думаю, больше всего должно смущать именно сортировка. можно было линейно в цикле поискать свежайший ответ

2024-04-08 18:27 UTC, atimofeyev commented
Как прокомментируете плагиат? откуда брали код/идеи? с кем вместе делали?

2024-04-08 18:36 UTC, lehatheslayer commented
> Как прокомментируете плагиат? откуда брали код/идеи? с кем вместе делали?

смотрел разные решения ребят, не отрицаю, что почерпнул какие-либо идеи, но решение все равно мое, можете спросить что угодно - отвечу. в своем коде я ориентируюсь, знаю, что и как работает

2024-04-08 19:15 UTC, atimofeyev commented
> > Как прокомментируете плагиат? откуда брали код/идеи? с кем вместе делали?
> 
> смотрел разные решения ребят, не отрицаю, что почерпнул какие-либо идеи, но решение все равно мое, можете спросить что угодно - отвечу. в своем коде я ориентируюсь, знаю, что и как работает

К сожалению "смотрел решения ребят" и повторение ряда уникальных ошибок буквально слово в слово - не похоже на правду. В целом,  заимствование идеи уже у нас cчитается плагиатом

2024-04-08 19:24 UTC, atimofeyev commented
за первое попадание - 0 баллов, в следующий раз отчисление

2024-04-18 16:22 UTC, atimofeyev approved these changes

2024-04-18 16:25 UTC, merged