Свистухин Андрей, ИТМО DWS, stage 4
polis-vk/2024-highload-dht pull request #155
Opened 2024-03-28 15:25 UTC by stormrvge

2024-03-28 15:28 UTC, stormrvge commented
Тесты прошли, codeclimate упал. Сейчас быстро исправлю

2024-03-28 16:20 UTC, stormrvge commented
@incubos у code-climate слишком много неочевидных правил стиля. Но я ведь реализацию не менял, тесты пройдены до пары, решение рабочее. Из-за лишних пробелов вся лабораторная мимо?

2024-03-28 17:29 UTC, incubos commented
> @incubos у code-climate слишком много неочевидных правил стиля. Но я ведь реализацию не менял, тесты пройдены до пары, решение рабочее. Из-за лишних пробелов вся лабораторная мимо?

Правила едины для всех. Могу только предложить начинать работать над решением раньше.

2024-04-07 17:39 UTC, atimofeyev requested changes

2024-04-07 17:39 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/asvistukhin/reports/stage4.md
> +Аллокации практически не изменились. 22% аллокаций занимает локальная вставка, всё остальное - сетевые операции с другими хостами. А именно, формирование и чтение
если не поменялась, то посему же ГЦ в два раза стал больше?

2024-04-07 19:17 UTC, stormrvge commented on src/main/java/ru/vk/itmo/test/asvistukhin/reports/stage4.md
> +Аллокации практически не изменились. 22% аллокаций занимает локальная вставка, всё остальное - сетевые операции с другими хостами. А именно, формирование и чтение
Ой, кажется это я ошибся. Аллокаций стало больше из-за того, что мы используем ack - следовательно, мы строим больше запросов/ответов. Из-за этого аллокаций стало больше, и ГЦ вырос в два раза

2024-04-07 19:56 UTC, atimofeyev commented
ряд признаков мне указывает на то что этот код вы писали не сами, а с пользуясь помощью постороннего кода

2024-04-07 20:12 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/asvistukhin/ProxyRequestHandler.java
> +            long timestamp = httpResponse.headers().firstValueAsLong(RequestWrapper.NIO_TIMESTAMP_HEADER).orElse(0);
для чего мы тут проксируем хедер NIO_TIMESTAMP_HEADER?

2024-04-08 18:28 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/asvistukhin/ProxyRequestHandler.java
> +            long timestamp = httpResponse.headers().firstValueAsLong(RequestWrapper.NIO_TIMESTAMP_HEADER).orElse(0);
Как прокомментируете плагиат? откуда брали код/идеи? с кем вместе делали?

2024-04-08 18:46 UTC, stormrvge commented on src/main/java/ru/vk/itmo/test/asvistukhin/ProxyRequestHandler.java
> +            long timestamp = httpResponse.headers().firstValueAsLong(RequestWrapper.NIO_TIMESTAMP_HEADER).orElse(0);
Ой, да, хедер отсюда можно выпилить, он не имеет никакого смысла

Под конец выполнения уже часть этого метода скопипастил у кого-то, точно не помню, потому что у меня был баг с бесконечным прокидыванием запросов между нод. Это не помогло, конечно, но код выпилить забыл.
Баг решил правильным указанием selfUrl, так как в джаве он подгружает url с портом, а в конфиге порта не было, он не мог понять что отправляет запросы на собственный инстанс и просто всё падало по таймауту.

Делал сам, не в паре. Обработчик запросов подкопипастил и забыл выпилить.

2024-04-08 19:11 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/asvistukhin/ProxyRequestHandler.java
> +            long timestamp = httpResponse.headers().firstValueAsLong(RequestWrapper.NIO_TIMESTAMP_HEADER).orElse(0);
дело в том что копипаст не только этого метода, есть и другие места которое точно не ваши.
А здесь вы утверждаете что скопипастили только этот кусок кода.

Сам плагиат сам по себе уже плохо, мы предупреждали о последствиях, слушать же явно неправду - еще более не приятно.

2024-04-08 19:24 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/asvistukhin/ProxyRequestHandler.java
> +            long timestamp = httpResponse.headers().firstValueAsLong(RequestWrapper.NIO_TIMESTAMP_HEADER).orElse(0);
за первое попадание - 0 баллов, в следующий раз отчисление

2024-04-18 16:07 UTC, atimofeyev approved these changes

2024-04-18 16:12 UTC, merged