Далбеев Георгий / ИТМО DWS / Stage 4
polis-vk/2024-highload-dht pull request #156
Opened 2024-03-28 17:05 UTC by goshadalbeev

решил заменить consistenthashing на randezvous

2024-03-31 10:47 UTC, incubos requested changes
Нужно разрешить конфликты перед merge. Поскольку после soft deadline, то максимум 5 баллов по результатам ревью.

2024-04-23 11:37 UTC, urbanchef commented
5 баллов

2024-04-23 11:37 UTC, urbanchef approved these changes

2024-04-23 11:38 UTC, urbanchef approved these changes

2024-05-28 15:35 UTC, closed without merging