stage 1, Чешев, Политех
polis-vk/2024-highload-dht pull request #16
Opened 2024-02-19 16:26 UTC by Queenore

2024-02-19 16:55 UTC, Queenore commented
[Отчет](https://github.com/polis-vk/2024-highload-dht/blob/1fbe9c6c442b549fda4087f7da5ed81b90bc033e/src/main/java/ru/vk/itmo/test/andreycheshev/lab1/report-1-Cheshev.md)

2024-02-28 07:17 UTC, lamtev requested changes
В решении есть серьёзные недочёты, такие как отсутствие обработки исключений и некорректная остановка сервиса. И, похоже, профилировалось приложение с "холодной" jvm (прошу учесть в следующих этапах)

Тем не менее, судя по отчёту, по результатам профилирования первого решения были выполнены оптимизации, направленные на уменьшение генерации мусора. Хотя, флеймграфы неинтерактивные, проверить отдельные выводы нельзя (прошу учесть в следующих этапах, чтобы не терять баллы)

Поэтому 8 баллов

И перед мержем необходимо откатить лишние изменения

2024-02-28 23:43 UTC, Queenore commented
Исправил замечания.

2024-02-29 08:56 UTC, lamtev commented on src/main/java/ru/vk/itmo/test/andreycheshev/ServerImpl.java
> +        this.dao = new PersistentReferenceDao(daoConfig);
Dao, в принципе, тоже можно было бы инстанцировать в сервисе и в сервер просто инжектить

2024-02-29 08:59 UTC, lamtev approved these changes

2024-02-29 09:00 UTC, merged