Прокопьев Никита / ИТМО DWS / Stage 5
polis-vk/2024-highload-dht pull request #163
Opened 2024-04-05 15:23 UTC by Nikpro200125

2024-04-07 12:39 UTC, incubos requested changes
Нужно зарезолвить конфликты перед merge и ревью.

2024-04-20 14:14 UTC, atimofeyev requested changes

2024-04-20 15:06 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
> +        workerPool.execute(() -> cfResponse.complete(handleInternalRequest(request)));
Согласен, исправил.

2024-04-20 15:06 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
> +                                        cfResponse.completeExceptionally(new IllegalArgumentException());
Согласен, исправил.

2024-04-20 15:06 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/MyServer.java
> +                                result.completeExceptionally(new NotEnoughReplicasException());
Так и есть - это разрешеное количество ошибок, которое еще можно получить. При ошибке я это число уменьшаю и если количество разешенных ошибок стало 0 - значит мы не можем больше их получать. Переименовал его в leftErrorsToFail - осталось ошибок до неудачи.

2024-04-20 15:11 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/analysis/stage5/reports/stage5.md
> +`RPS` увеличился, так как теперь все запросы отправляются паралелльно и не ждут друг друга. Значительное увеличение произошло при ack=1 и from=3, так как при первом успешном ответе отправляется ответ
Согласен, но насколько я помню говорили на лекции этого не нужно было делать, или я не прав и это нужно реализовать?

2024-04-20 15:21 UTC, Nikpro200125 commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/analysis/stage5/reports/stage5.md
> +При использовании CompletableFuture, мы увеличили немного производительность в случае использования ack < from и уменьшили latency, так как запросы отправляются параллельно и не ждут друг друга.
Все таки в худшем случае с ack=3/from=3 произошло ускорение на 250 rps, что примерно 7%. Скорее всего это связано с произодительностью моего компьютера и в целом низким rps 3500-5500. А значительная разница ack/from 1/3 и 3/3 связано с тем, что когда у нас ack=1, то он не тратит "ресурсы сети", а быстро обрабатывается локально.

2024-04-29 04:02 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/nikitaprokopev/analysis/stage5/reports/stage5.md
> +`RPS` увеличился, так как теперь все запросы отправляются паралелльно и не ждут друг друга. Значительное увеличение произошло при ack=1 и from=3, так как при первом успешном ответе отправляется ответ
все верно, это не обязательно

2024-04-30 20:01 UTC, atimofeyev approved these changes

2024-05-05 13:56 UTC, atimofeyev approved these changes

2024-05-05 14:04 UTC, atimofeyev approved these changes

2024-05-15 09:31 UTC, incubos approved these changes

2024-05-15 18:51 UTC, merged