Пронин Валентин / ИТМО DWS / Stage 5
polis-vk/2024-highload-dht pull request #165
Opened 2024-04-07 13:50 UTC by GonarchX

2024-04-13 12:44 UTC, incubos requested changes
Необходимо зарезолвить конфликты.

2024-05-13 10:41 UTC, urbanchef commented on src/main/java/ru/vk/itmo/test/proninvalentin/Server.java
> +            positiveResponses.sort(Comparator.comparingLong(r ->
Для чего тут используется сортировка? Кажется, можно обойтись без сортировки для нахождения минимальных/максимальных значений.

2024-05-13 10:45 UTC, urbanchef commented
14 баллов

2024-05-13 10:45 UTC, urbanchef approved these changes

2024-05-13 12:59 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/Server.java
> +            positiveResponses.sort(Comparator.comparingLong(r ->
В принципе, да. Можно было просто сохранять наиболее актуальный ответ и не тратить время и память на сортировку массива ответов

2024-05-13 14:12 UTC, urbanchef commented on src/main/java/ru/vk/itmo/test/proninvalentin/reports/stage5/report.md
> +  видно, что ForkJoinPool связан с commonPool ![img.png](visualVM-forkJoinPool.png)
Можно ли избавиться от ForkJoinPool? И каким образом?

2024-05-13 16:44 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/reports/stage5/report.md
> +  видно, что ForkJoinPool связан с commonPool ![img.png](visualVM-forkJoinPool.png)
Помню, что на лекции мы обсуждали возможность добавить в селекторы логику, когда они все такие задачи, которые пришли от воркеров, обратно отсылают воркерам, а не обрабатывают сами

2024-05-28 15:35 UTC, closed without merging