Stage 5, Андрей Чешев, Политех
polis-vk/2024-highload-dht pull request #167
Opened 2024-04-07 22:33 UTC by Queenore

2024-04-13 12:45 UTC, incubos requested changes
Необходимо зарезолвить конфликты.

2024-04-14 23:45 UTC, Queenore commented
> Необходимо зарезолвить конфликты.

Зарезолвил конфиликты.

2024-04-21 20:26 UTC, Marashov-Alexander approved these changes
11/15
Выглядит неплохо. Из замечаний - маловато аналитики по отчёту при профилировании, а если про код - сильно расплылась ответственность за отправку ответа, еще есть несколько вопросов к лишним выделениям

2024-04-21 20:26 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/ResponseCollector.java
> +        responseCount.incrementAndGet();
не может такого быть, что здесь инкрементим responseCount, потом случается исключение - и мы попадаем в exceptionallyAsync, где вновь инкрементим responseCount?

2024-04-21 20:26 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/AsyncActions.java
> +        return withSendingErrorProcessing(future);
можете, пожалуйста, рассказать идею метода withSendingErrorProcessing?

2024-04-21 20:26 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/RequestHandler.java
> +        List<Integer> nodesIndices = distributor.getQuorumNodes(id, from);
а почему метод называется getQuorumNodes, если он возвращает ноды не по количеству кворумов, а столько, сколько запрошено через параметр from?)

2024-04-21 20:26 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/lab5/report-5-Cheshev.md
> +  * Distributor - для распределения задач по CompletableFuture (6 потоков core, 6 потоков максимум);
А почему было использовано именно такое кол-во потоков на каждом из экзекьюторов? Было бы здорово пояснить, почему было выбрано именно так, поскольку на первый взгляд кажется, что у Distributor'а может быть меньше работы, чем у некоторых из ниже указанных

2024-04-21 20:26 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/lab5/report-5-Cheshev.md
> +И get и put запросы выдали меньшую задержку, чем ранее, но для get запросов после 99го персентиля замечен тренд резкого увеличения задержки.
с чем он может быть связан?

2024-04-21 20:26 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/lab5/report-5-Cheshev.md
> +    * Поскольку решение было переведено на использование java.net.HttpClient, то появились сопутствующие аллокации.
Маловато аналитики будет)

2024-04-21 20:26 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/lab5/report-5-Cheshev.md
> +    * LocalCall, Distributor потоки занимают в среднем от 0.5 до 1 проценту процессорного времени.
Тоже маловато)

2024-05-02 21:24 UTC, Queenore commented on src/main/java/ru/vk/itmo/test/andreycheshev/AsyncActions.java
> +        return withSendingErrorProcessing(future);
Суть в том, чтобы "навесить" на `CompletableFuture` логирование того, что произошла ошибка. Передаем  `CompletableFuture` и возвращаем ее же, но только с обработчиком.

2024-05-02 22:13 UTC, Queenore commented
Завтра смогу прислать дополненный отчет и исправления.

2024-05-03 23:20 UTC, Queenore commented on src/main/java/ru/vk/itmo/test/andreycheshev/ResponseElements.java
> +        return Arrays.copyOf(body, body.length); // CodeClimate requirement.
В стандартной библиотеке Java не нашел прямого способа сделать массив read-only без копирования.

2024-05-03 23:22 UTC, Queenore commented
Внес правки.

2024-05-03 23:23 UTC, Queenore commented on src/main/java/ru/vk/itmo/test/andreycheshev/WorkerThreadFactory.java
> +        this.prefix = prefix + "-";
WorkerThreadFactory до сих пор используется мною для конфигурирования executor`ов.

2024-05-03 23:24 UTC, Queenore commented on src/main/java/ru/vk/itmo/test/andreycheshev/ResponseElements.java
> +        return Arrays.copyOf(body, body.length); // CodeClimate requirement.
Сделал с использованием обертки ByteBuffer, но копирование все равно осталось при получении.

2024-05-15 21:03 UTC, Queenore commented
> Необходимо зарезолвить конфликты.

Конфликты были зарезолвлены.

2024-05-19 11:24 UTC, incubos approved these changes
Добавляю approve после merge upstream.

2024-05-19 12:02 UTC, merged