Тузиков Александр, ИТМО DWS, Stage 5
polis-vk/2024-highload-dht pull request #170
Opened 2024-04-09 18:30 UTC by alexBlack01

2024-04-30 19:36 UTC, incubos requested changes
Есть существенные замечания и вопросы.

2024-04-30 19:36 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/ServerImpl.java
> +                .thenApplyAsync(this::processingResponse);
Может, явно указать `Executor`?

2024-04-30 19:36 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/ServerImpl.java
> +        String statusCode = Constants.HTTP_CODE.getOrDefault(response.statusCode(), null);
Кода может не быть?

2024-04-30 19:36 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/ServerImpl.java
> +                    .firstValueAsLong(Constants.HTTP_TIMESTAMP_HEADER).orElse(0);
Зачем `orElse()`? Т.е. либо мы ожидаем заголовок и его отсутствие -- это ошибка, или нет, верно?

2024-04-30 19:36 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/ServerImpl.java
> +                    CompletableFuture.supplyAsync(() -> requestHandler.handle(request, paramId))
Почему здесь не указан `Executor`?

2024-04-30 19:36 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/ServerImpl.java
> +            responseFuture.whenCompleteAsync((response, throwable) -> {
Почему не указан `Executor`?

2024-04-30 19:36 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/ServerImpl.java
> +                    result.complete(getResult(request, successResponses));
`complete()` может вызываться несколько раз, верно? Выглядит как ошибка.

2024-04-30 19:36 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/ServerImpl.java
> +            return new Response(Response.INTERNAL_ERROR, Response.EMPTY);
Залоггировать?

2024-04-30 19:36 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/ServerImpl.java
> +            return new Response(Response.INTERNAL_ERROR, Response.EMPTY);
Залоггировать?

2024-04-30 19:36 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/ServerImpl.java
> +            sortResponses(successResponses);
Зачем сортировать за `O(n log n)`, если нас интересует `max` за `O(n)`?

2024-04-30 19:36 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/results/stage5/report.md
> +100.000%    9.33s       25.54s
**Секунды** вообще нет смысла анализировать -- здесь что-то не так.

2024-04-30 19:36 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/results/stage5/report.md
> +Отмечу еще, что при увеличении количества соединений возникали проблемы с тестированием. Все улетало в таймаут.
В чём причина?

2024-04-30 19:36 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/results/stage5/report.md
> +- Добавился ForkJoinWorkerThread.run 16.40%;
Откуда он взялся? Есть объяснения?

2024-04-30 19:36 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/results/stage5/report.md
> +При работе с CompletableFuture появилась новая аллокация ForkJoinWorkerThread.run.
В чём причина?

2024-04-30 19:36 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/results/stage5/report.md
> +как сам я их не создавал. Но этого не нашел.
Непонятно. Можете прояснить?

2024-04-30 19:36 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/results/stage5/report.md
> +100.000%   28.57s       26.35s
Секунды нет смысла анализировать. Система явно перегружена.

2024-04-30 19:36 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/results/stage5/report.md
> +Аналогично, как и в случае с PUT запросами. Только немного другие пропорции.
Как можно объяснить изменение пропорций? Согласен, что наша система выполняет те же функции, но как объяснить изменение распределения ресурсов?

2024-04-30 19:36 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/results/stage5/report.md
> +Аналогично, как и в случае с PUT запросами. Только немного другие пропорции.
Хотелось бы увидеть объяснение изменения пропорций.

2024-04-30 19:36 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/results/stage5/report.md
> +Соответсвенно, самыми показательными были LOCK фреймы.
Можно конкретнее, пожалуйста? В чём показательны LOCK фреймы?

2024-04-30 22:17 UTC, alexBlack01 commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/results/stage5/report.md
> +как сам я их не создавал. Но этого не нашел.
Я подходил с этим вопросом после окончания дедлайна. Говорил, что если мы не даем екзекьюторы, то они должны создаваться дефолтные у задачи (как я понял). А этого обнаружить не смогу. Вы мне потом пояснили, что там надо было через флаг смотреть. Что догадка верна моя

2024-05-04 10:43 UTC, alexBlack01 commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/ConsistentHashing.java
> +        if (key != null && from > 0) {
В контексте системы такой случай быть не может. Спасибо за замечание, в будущем будет исправлено.
Когда писал этот метод рассматривал общий случай, что в принципе может прийти пустой ключ

2024-05-04 10:54 UTC, alexBlack01 commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/ServerImpl.java
> -            if (paramId == null || paramId.isEmpty()) {
Сначала даже и правда не понял, зачем убрал. Потом вспомнил, что не убрал, а объединил. На 93 строке. Когда проверяем параметры `ack` и `from` сразу проверяем и `paramId`.

2024-05-04 10:57 UTC, alexBlack01 commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/ServerImpl.java
> -            if (paramId == null || paramId.isEmpty()) {
```java
if (ack == 0 || from > clusterSize || ack > from || paramId == null || paramId.isEmpty()) {
        sendResponse(session, new Response(Response.BAD_REQUEST, Response.EMPTY));
        return;
}
```

2024-05-04 11:00 UTC, alexBlack01 commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/results/stage5/report.md
> +100.000%   28.57s       26.35s
В случае с виртуалкой для меня было проблематично определять эти показатели, потому что и на секундах как-то пахало и на этом спасибо

2024-05-04 11:15 UTC, alexBlack01 commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/ServerImpl.java
> +                .thenApplyAsync(this::processingResponse);
Да, согласен, что такой способ тоже хорош. Когда делал этап, очень много думал над этим. Что если мы не указываем явно, то тратим ресурсы на создание дефолтных каждый раз. И на лекции говорили, что, вроде, лучше делать пул экзекьюторов и потом отдавать их задачам.

2024-05-04 11:15 UTC, alexBlack01 commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/ServerImpl.java
> +                .thenApplyAsync(this::processingResponse);
Но, если пул будет переполнен, то тоже не очень хорошо же получится

2024-05-04 11:22 UTC, alexBlack01 commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/ServerImpl.java
> +        String statusCode = Constants.HTTP_CODE.getOrDefault(response.statusCode(), null);
Нет, код будет всегда. Исправлю на 
```java
String statusCode = Constants.HTTP_CODE.get(response.statusCode());
```

2024-05-04 11:31 UTC, alexBlack01 commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/ConsistentHashing.java
> +        return res;
В контексте нашей реализации такого случая в приницпе быть не может, чтоб from был не указан. Все равно есть дефолтные значения. Если я правильно понял замечание

2024-05-04 12:37 UTC, alexBlack01 commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/results/stage5/report.md
> +Соответсвенно, самыми показательными были LOCK фреймы.
Так как выросло количество блокировок. У сэмплов на 4 этапе в принципе не были видны `java/util/concurrent/CompletableFuture$AsyncSupply.run`, `java/util/concurrent/ThreadPoolExecutor.getTask`, `jdk/internal/net/http/common/SequentialScheduler$SchedulableTask.run`. А на 5 этапе, так как были добавлена работа с асинхронностью, мы видим, какие блокировки срабатывают на ожидание задач, на их получение. Также, что они занимают хоть и не большую, но все равно весомую часть нагрузки

2024-05-04 13:00 UTC, alexBlack01 commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/results/stage5/report.md
> +Аналогично, как и в случае с PUT запросами. Только немного другие пропорции.
Если в контексте с предыдущим этапом, то изменение пропорций произошло из-за появления новых асинхронных операций, ну и соответственно новые сэмплы также появились, как я понимаю. 
Также если мы и добавили работы воркерам, именно что работу с фьючерами.

А если говорить именно между get и put, то думаю, что несколько причин может быть. Например, насколько была заполнена база при get запросах, насколько быстро они отрабатывали.

2024-05-05 08:05 UTC, alexBlack01 commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/results/stage5/report.md
> +Аналогично, как и в случае с PUT запросами. Только немного другие пропорции.
Тут также как и с предыдущим комментарием, все идет вокруг добавления работы с асинхронными задачами. Соответственно и появление новых сэмплов, которые отражают это.

2024-05-10 16:36 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/ConsistentHashing.java
> +        return res;
Да, проглядел -- извиняюсь.

2024-05-10 16:37 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/ServerImpl.java
> +                .thenApplyAsync(this::processingResponse);
Я про то, что без явного указания `Executor` непонятно, где исполняются callback'и, а мы точно не хотим исполняться на дефолтном, который используется для других сторонних нужд.

2024-05-10 16:41 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/results/stage5/report.md
> +как сам я их не создавал. Но этого не нашел.
Не смог осознать ответ. Если мы не указываем `Executor`, то исполняться код может на разных (в т.ч. на дефолтном) в зависимости от готовности `CompletableFuture`. Аллокация -- это про память, а здесь речь о чём-то другом, видимо?

2024-05-10 16:42 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/results/stage5/report.md
> +100.000%   28.57s       26.35s
Но здесь нечего анализировать и сравнивать в режиме перегрузки.

2024-05-10 16:44 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/results/stage5/report.md
> +Аналогично, как и в случае с PUT запросами. Только немного другие пропорции.
Хотелось бы увидеть больше конкретики по результатам анализа профилей вместо общих рассуждений про future.

2024-05-10 16:45 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/results/stage5/report.md
> +Аналогично, как и в случае с PUT запросами. Только немного другие пропорции.
Нужна конкретика -- что за методы появились, какую работу они выполняют, можно ли её устранить или она обоснована и т.д.

2024-05-10 16:45 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/results/stage5/report.md
> +Соответсвенно, самыми показательными были LOCK фреймы.
Это всё достойно попадания в отчёт.

2024-05-10 16:46 UTC, incubos approved these changes
10 баллов.

2024-05-10 16:47 UTC, merged