Тимофеев Кирилл, ИТМО DWS, Stage 5
polis-vk/2024-highload-dht pull request #171
Opened 2024-04-10 18:46 UTC by NoGe4Ek

code only

2024-05-01 17:11 UTC, incubos requested changes
Есть существенные замечания и вопросы, в т.ч. к отчёту -- ждём исправлений.

2024-05-01 17:11 UTC, incubos commented on src/main/java/ru/vk/itmo/test/timofeevkirill/results/task5/readme.md
> +Добавилась обработка ConcurrentLinkedQueue (36 + 116 сэмплов, 0.06 %+ 0.18%).
Почему мы говорим про очередь, которая занимает крошечное количество сэмплов? Особенно на фоне HTTP клиента.

2024-05-01 17:11 UTC, incubos commented on src/main/java/ru/vk/itmo/test/timofeevkirill/results/task5/readme.md
> +HttpClientFacade.send для синк подхода ~1_300_000 сэмплов (37.37%), для асинк подхода HttpClientFacade.sendAsync ~1_130_000 (25.29%).
Как можно объяснить различие в количестве сэмплов?

2024-05-01 17:11 UTC, incubos commented on src/main/java/ru/vk/itmo/test/timofeevkirill/results/task5/readme.md
> +В целом для cpu/alloc изменения такие же как и на put флейм графе.
Флеймграфы отличаются кардинально -- вы их открывали? В асинхронной версии `processHttpBuffer()` занимает почти 40% CPU сэмплов, а в синхронной -- меньше 4%. Как это можно объяснить?

2024-05-01 17:11 UTC, incubos commented on src/main/java/ru/vk/itmo/test/timofeevkirill/results/task5/readme.md
> +Для локов тоже нет особого отличия от put.
Флеймграфы синхронной и асинхронной версий совершенно разные -- откройте вкладки рядом и попереключайтесь. Анализ очень поверхностный и вводит в заблуждение.

2024-05-02 14:41 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/reference/MergeHandleResult.java
> +        resultFuture.whenComplete((result, e) -> {
fixed

2024-05-02 14:53 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/reference/ReferenceServer.java
> +                .thenApply(httpResponse -> {
fixed

2024-05-02 15:03 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/reference/ReferenceServer.java
> +                HandleResult local = localFuture.get();
fixed

2024-05-02 15:09 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/reference/ReferenceServer.java
> +                            timestamp = 0;
Взято из референса.

2024-05-02 15:09 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/reference/ReferenceServer.java
> +                        timestamp = 0;
Взято из референса.

2024-05-02 15:12 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/reference/ReferenceServer.java
> +                        timestamp = 0;
fixed

2024-05-02 15:13 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/reference/ReferenceServer.java
> +        assert count < 5;
потерялось. fixed

2024-05-02 15:16 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/reference/ReferenceServer.java
> +                .timeout(Duration.ofMillis(500))
fixed

2024-05-02 15:20 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/reference/ReferenceServer.java
> +        long currentTimeMillis = System.currentTimeMillis();
fixed

2024-05-02 15:23 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/reference/ReferenceService.java
> +    public static void shutdownAndAwaitTermination(ExecutorService pool) {
Из референса. Не досмотрел. fixed

2024-05-02 15:26 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/results/task5/readme.md
> +### 14 thds - предыдущая точка разладки
Да, это тысячи. Не знаю, почему не "k". Начал так, решил также и продолжить

2024-05-02 16:07 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/results/task5/readme.md
> +![put](https://github.com/NoGe4Ek/2024-highload-dht/blob/feature/task5/src/main/java/ru/vk/itmo/test/timofeevkirill/results/task5/asprof/put/cpu/png/async_4.png)
Насколько понял, в MultiExchange.responseAsyncImpl есть логика, завязанная на retries & redirect. Внутри много регистраторов таймера и его остановок в случае timeout'а. Думаю, в нем проблема, можно попробовать увеличить timeout.
SchedulableTask.run() раздут по этой же причине.

2024-05-03 14:33 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/results/task5/readme.md
> +![put](https://github.com/NoGe4Ek/2024-highload-dht/blob/feature/task5/src/main/java/ru/vk/itmo/test/timofeevkirill/results/task5/asprof/put/cpu/png/async_4.png)
SchedulableTask.run() - по идее класс отвечает за постановку задач в очередь на потоки. Насколько я понимаю, он помогает в обработке цепочек в completable future. Единственное, чего я не понимаю - это почему он такой же большой для sync флейм графа.

2024-05-03 14:43 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/results/task5/readme.md
> +Добавилась обработка ConcurrentLinkedQueue (36 + 116 сэмплов, 0.06 %+ 0.18%).
Также появился появился ForkJoinWorkerThread, который занимает 1.66%.
Больше различий особо не заметил. Разве что значительная часть сэмплов переехала из PayloadThread.run в Thread.run. Видимо, потому что не указывал кастомный Executor.

2024-05-03 14:59 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/results/task5/readme.md
> +HttpClientFacade.send для синк подхода ~1_300_000 сэмплов (37.37%), для асинк подхода HttpClientFacade.sendAsync ~1_130_000 (25.29%).
MultiExchange.responseAsync переехала в Thread.run и выросла с 22.60% до 29.69%. В сумме стало больше, что логично, тк асинхронных операций стало больше.

2024-05-03 15:16 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/results/task5/readme.md
> +В целом для cpu/alloc изменения такие же как и на put флейм графе.
Аномальный профиль получился.
processRead -> processHttpBuffer -> 22% просидели в HttpSession.closing -> это триггерило exception Bad request. Но я подозреваю, что это также связано с маленьким timeout'ом, для http клиента

2024-05-03 15:32 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/results/task5/readme.md
> +Для локов тоже нет особого отличия от put.
Действительно. Основной проблемой, как мне кажется, является переезд методов из PayloadThread.run. Поэтому пропорции сильно исказились. Думаю, что после внесенных изменений можно было бы еще раз собрать профиль и пропорции встали бы на место. Но анализировать аномалии даже интереснее.

2024-05-03 15:34 UTC, NoGe4Ek commented
> Есть существенные замечания и вопросы, в т.ч. к отчёту -- ждём исправлений.

Исправил замечания. По отчету действительно были проблемы, тк получилось снять аномальные профили и не было достаточно времени, чтобы анализировать проблемы.
Постарался поискать причины аномалий и дополнил отчет анализом

2024-05-10 16:55 UTC, merged