Супрядкина Дарья ИТМО DWS stage 1
polis-vk/2024-highload-dht pull request #18
Opened 2024-02-19 17:51 UTC by SuDarina

Отчет в процессе написания

2024-02-25 10:16 UTC, atimofeyev requested changes

2024-02-25 10:16 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/ServiceIml.java
> +    private ReferenceDao dao;
тот же комментарий про более общий тип - лучше интерфейс

2024-02-25 10:16 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/ServiceIml.java
> +    public CompletableFuture<Void> start() throws IOException {
старт/стоп лучше сделать синхронизированными

2024-02-25 10:20 UTC, atimofeyev commented
надо добавить обработку неожиданных ошибок

2024-02-27 23:08 UTC, SuDarina commented
> надо добавить обработку неожиданных ошибок

исправила

2024-03-01 22:40 UTC, atimofeyev approved these changes

2024-03-01 22:44 UTC, merged