Смирнов Андрей ИТМО КТ Stage 5
polis-vk/2024-highload-dht pull request #181
Opened 2024-04-11 00:49 UTC by sandrew-uj

2024-04-29 13:08 UTC, AlexeyShik requested changes
Есть замечания к корректности многопоточки + в этом дз тоже нужен отчет

2024-04-29 13:08 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/test/smirnovandrew/RendezvousClusterManager.java
> +    public static List<Integer> getSortedNodes(String key, int amount, ServiceConfig config) {
Можно сделать за более быструю асимптотику, но это тема дз4

2024-04-29 13:08 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/test/smirnovandrew/MyServer.java
> +        this.httpClient = HttpClient.newHttpClient();
На каком пуле потоков выполняются запросы к другим репликам?

2024-04-29 13:08 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/test/smirnovandrew/MyServerUtil.java
> +            var responseFuture = completableFuture.whenComplete(whenComplete);
На каком пуле потоков выполняется агрегация ответов от реплик?

2024-05-01 10:50 UTC, sandrew-uj commented on src/main/java/ru/vk/itmo/test/smirnovandrew/MyServer.java
> +        this.httpClient = HttpClient.newHttpClient();
На том же, что задается вот в этой строчке
this.executor = new MyExecutor(corePoolSize, availableProcessors);

2024-05-01 10:50 UTC, sandrew-uj commented on src/main/java/ru/vk/itmo/test/smirnovandrew/MyServerUtil.java
> +            var responseFuture = completableFuture.whenComplete(whenComplete);
На том же, что задается вот в этой строчке
this.executor = new MyExecutor(corePoolSize, availableProcessors);

2024-05-13 18:22 UTC, AlexeyShik approved these changes
С учетом замечаний по многопоточке поставлю 13 баллов.

2024-05-13 18:22 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/test/smirnovandrew/MyServerUtil.java
> +            var responseFuture = completableFuture.whenComplete(whenComplete);
Так как в явном виде не меняется пул потоков (не передается другой executor), то будет выполняться на том же пуле потоков, что и completableResults, то есть на том же пуле, что и sendAsync, на потоках из httpClient.

2024-05-13 18:22 UTC, AlexeyShik commented on build.gradle
> +run {
Надо откатить перед мерджем

2024-05-13 18:22 UTC, AlexeyShik commented on src/main/java/ru/vk/itmo/test/smirnovandrew/readme/stage5/get_cpu.png
JIT видно на профиле

2024-05-13 19:04 UTC, AlexeyShik reviewed
Прошу откатить build.gradle

2024-05-13 20:55 UTC, merged