Свистухин Андрей, ИТМО DWS, Stage 5
polis-vk/2024-highload-dht pull request #186
Opened 2024-04-11 11:54 UTC by stormrvge

2024-04-11 12:11 UTC, stormrvge commented
![image](https://github.com/polis-vk/2024-highload-dht/assets/38988611/57218e44-4ab5-480f-ac13-dabf45bb7900)
только мой package локально

2024-04-25 14:24 UTC, stormrvge commented
Проблему с аллокациями пофиксил в следующей лабораторной. Если нужно, могу изменения подлить сюда.

2024-04-29 20:46 UTC, atimofeyev requested changes

2024-04-29 20:46 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/asvistukhin/ProxyRequestHandler.java
> +        List<CompletableFuture<Response>> futures,
Очень плохой паттерн: передавать в параметрах IN и OUT переменные. Лучше стараться так организовать код, чтобы в пармтерах были только IN, а OUT было в return.
И лучше чтобы это было что-то одно

2024-04-29 20:46 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/asvistukhin/ProxyRequestHandler.java
> +                futures.add(CompletableFuture.completedFuture(null));
тут наверное планировалось поставить return?

2024-04-29 20:46 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/asvistukhin/ProxyRequestHandler.java
> +                if (success && responsesCollected.getAndIncrement() < ack) {
тут что-то не то, на SUCCESS ответ, который будет ack+1 мы почему-то взведем unsuccessfulResponsesCount

2024-04-29 20:46 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/asvistukhin/ProxyRequestHandler.java
> +                    .firstValue(RequestWrapper.NIO_TIMESTAMP_HEADER)
а эта бесполезная штука так и переехала дальше в этот стейдж?

2024-04-29 20:46 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/asvistukhin/RequestHandler.java
> +        futures.add(new CompletableFuture<Response>().completeAsync(() -> {
а тут мы будем использовать commonPool, что плохо, лучше пользоваться своим пулом

2024-04-29 20:46 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/asvistukhin/reports/stage5.md
> +Аллокации убили GC. ~97% аллоков занимает GC, а именно AllocateHeap. Видимо, я не совсем правильно использую CompletableFuture,
ну вообще для этого и есть инструмент, хорошо бы найти проблему и починить

2024-04-29 21:04 UTC, atimofeyev commented
+ тесты не проходят

2024-05-01 14:00 UTC, stormrvge commented on src/main/java/ru/vk/itmo/test/asvistukhin/ProxyRequestHandler.java
> +        List<CompletableFuture<Response>> futures,
Нужно было эти futures возвращать return'ом и дальше записывать их в структуру которая лежит по стеку вызовов выше? Я просто подумал, что может быть из-за этого у меня и сходил с ума GC. Но кажется, проблема была всё-таки не в этом

2024-05-01 14:00 UTC, stormrvge commented on src/main/java/ru/vk/itmo/test/asvistukhin/ProxyRequestHandler.java
> +                futures.add(CompletableFuture.completedFuture(null));
если учитывать Ваш коммент выше, то получается так))

2024-05-01 14:02 UTC, stormrvge commented on src/main/java/ru/vk/itmo/test/asvistukhin/ProxyRequestHandler.java
> +                if (success && responsesCollected.getAndIncrement() < ack) {
Да, проглядел этот момент. Исправлю.

2024-05-01 14:03 UTC, stormrvge commented on src/main/java/ru/vk/itmo/test/asvistukhin/ProxyRequestHandler.java
> +                    .firstValue(RequestWrapper.NIO_TIMESTAMP_HEADER)
Нет, она не бесполезная. В ServerImpl идет проверка, есть ли этот хедер или нет
```
            String timestamp = response.getHeader(RequestWrapper.NIO_TIMESTAMP_STRING_HEADER);
```

2024-05-01 14:04 UTC, stormrvge commented on src/main/java/ru/vk/itmo/test/asvistukhin/RequestHandler.java
> +        futures.add(new CompletableFuture<Response>().completeAsync(() -> {
А нам ведь нужно создать отдельный пул под это, а не использовать пул из ServerImpl?

2024-05-01 14:09 UTC, stormrvge commented on src/main/java/ru/vk/itmo/test/asvistukhin/reports/stage5.md
> +Аллокации убили GC. ~97% аллоков занимает GC, а именно AllocateHeap. Видимо, я не совсем правильно использую CompletableFuture,
Так как тест проходил локально, я подумал что проблема флаков либо у кого-нибудь другого, либо агент подвисает. И только уже при профилировании заметил, что проблема всё-таки у меня. В шестом этапе я пытался исправить логику с CompletableFutures, думал, что они у меня подвисают в памяти, но кажется это не помогло. Тесты на агенте там прошли, и я думал что проблема тоже ушла, ведь профилирование ещё не делал на том этапе. Вот сегодня как сделал профилирование, снова увидел, что проблема никуда не ушла. Пока что не разобрался с чем именно проблема, ведь CompletableFutures, вроде как, попытался исправить.
И странно, ведь именно после этого этапа у меня GC начал занимать все аллокации на JVM. Возможно, имеет смысл проверить через visualvm, посмотреть что в рантайме находится в памяти.

2024-05-01 14:10 UTC, stormrvge commented
@atimofeyev 
> * тесты не проходят

Они не проходят на агенте скорее всего из-за большого потребления памяти. Локально все тесты проходят.

2024-05-01 14:18 UTC, stormrvge commented
@atimofeyev исправил код по комментариям

2024-05-01 14:28 UTC, stormrvge commented
После исправления ошибки с 
```
                if (success && responsesCollected.getAndIncrement() < ack) {
```
тесты начали проходить, я решил проверить профилировщик, подумал что может быть отсюда и утечка, но нет, GC до сих пор ест аллоки

2024-05-05 22:38 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/asvistukhin/RequestHandler.java
> +                collectedResponses.add(response);
здесь идет незащищенное обращение к коллекции из разных потоков, должны быть ошибки

2024-05-05 22:39 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/asvistukhin/ProxyRequestHandler.java
> +                    collectedResponses.add(response);
здесь идет незащищенное обращение к коллекции из разных потоков, должны быть ошибки

2024-05-05 23:24 UTC, stormrvge commented on src/main/java/ru/vk/itmo/test/asvistukhin/RequestHandler.java
> +                collectedResponses.add(response);
а, и правда
я почему-то подумал, что можно и обычный arraylist сделать, так как у нас для каждого запроса будет создаваться свой лист, но проблема будет именно из-за того, что в разных потоках добавляем туда
изначально у меня и было на скиплисте, но что-то я решил поменять на arraylist

2024-05-06 16:57 UTC, stormrvge commented on src/main/java/ru/vk/itmo/test/asvistukhin/RequestHandler.java
> +                collectedResponses.add(response);
А, нет, я на ArrayList не менял
Я передаю List<CompletableFuture<Response>> futures = new CopyOnWriteArrayList<>(); в метод

2024-05-06 16:58 UTC, stormrvge commented on src/main/java/ru/vk/itmo/test/asvistukhin/RequestHandler.java
> +                collectedResponses.add(response);
List<Response> validResponses = new CopyOnWriteArrayList<>();

2024-05-14 18:33 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/asvistukhin/RequestHandler.java
> +                collectedResponses.add(response);
хорошо, значит я проглядел

2024-05-14 18:37 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/asvistukhin/ProxyRequestHandler.java
> +        List<CompletableFuture<Response>> futures,
да, я бы сделал так, хотя понял что вы пробовали уменьшить число аллокаций

2024-05-14 18:39 UTC, atimofeyev approved these changes

2024-05-14 18:42 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/asvistukhin/ProxyRequestHandler.java
> +                    .firstValue(RequestWrapper.NIO_TIMESTAMP_HEADER)
ага, я ошибся

2024-05-14 18:42 UTC, merged