Homework5. Тяпуев Дмитрий. Магистратура. Политех
polis-vk/2024-highload-dht pull request #189
Opened 2024-04-11 12:55 UTC by typuichik123

2024-04-14 12:11 UTC, lamtev requested changes
Есть concurrency баг, синхронная обработка локального запроса, которая может притормаживать обработку клиентского запроса

Жду исправлений и результатов профилирования

2024-04-14 12:11 UTC, lamtev commented on src/main/java/ru/vk/itmo/test/tyapuevdmitrij/ServerImplementation.java
> +        ((ThreadPoolExecutor) proxyExecutor).prestartAllCoreThreads();
Интересный момент. Какой ожидаемый и фактический эффект?

2024-04-14 12:11 UTC, lamtev commented on src/main/java/ru/vk/itmo/test/tyapuevdmitrij/ServerImplementation.java
> +                1,
Достаточно 1 треда на все запросы? Не является ли это узким местом?

2024-04-16 21:58 UTC, typuichik123 commented on src/main/java/ru/vk/itmo/test/tyapuevdmitrij/ServerImplementation.java
> +                responses.add(CompletableFuture.completedFuture(handleNodeRequest(request, id, timeNow)));
Исправил

2024-04-16 21:59 UTC, typuichik123 commented on src/main/java/ru/vk/itmo/test/tyapuevdmitrij/ServerImplementation.java
> +        AtomicInteger completedFuture = new AtomicInteger(0);
Переименовал

2024-04-16 21:59 UTC, typuichik123 commented on src/main/java/ru/vk/itmo/test/tyapuevdmitrij/ServerImplementation.java
> +                if (completedFuture.get() == responses.size() || ack == successResponses.get()) {
Убрал левую часть

2024-04-16 21:59 UTC, typuichik123 commented on src/main/java/ru/vk/itmo/test/tyapuevdmitrij/ServerImplementation.java
> +            if (headerTime >= finalTime.get()) {
Исправил

2024-04-16 21:59 UTC, typuichik123 commented on src/main/java/ru/vk/itmo/test/tyapuevdmitrij/ServerImplementation.java
> +                return;
Исправил

2024-04-16 22:00 UTC, typuichik123 commented on src/main/java/ru/vk/itmo/test/tyapuevdmitrij/ServerImplementation.java
> +    private static void sentFinalResponse(List<CompletableFuture<Response>> responses, int ack,
Переименовал метод

2024-04-16 22:00 UTC, typuichik123 commented on src/main/java/ru/vk/itmo/test/tyapuevdmitrij/ServerImplementation.java
>                  new ThreadPoolExecutor.AbortPolicy());
Изменил политику при переполнении очереди

2024-04-16 22:00 UTC, typuichik123 commented on src/main/java/ru/vk/itmo/test/tyapuevdmitrij/ServerImplementation.java
> +                new ThreadPoolExecutor.AbortPolicy());
Изменил политику при переполнении очереди

2024-04-16 22:01 UTC, typuichik123 commented on src/main/java/ru/vk/itmo/test/tyapuevdmitrij/ServerImplementation.java
> +                1,
Добавил побольше

2024-04-16 22:05 UTC, typuichik123 commented on src/main/java/ru/vk/itmo/test/tyapuevdmitrij/ServerImplementation.java
> +        ((ThreadPoolExecutor) proxyExecutor).prestartAllCoreThreads();
Ожидалось, что потоки будут сразу прогреты и готовы принять задачу быстрей. Фактической разницы не заметил

2024-05-03 14:24 UTC, lamtev approved these changes
Остались некоторые проблемы

10 баллов

Прошу разрешить конфликт, и сольём в апстрим

2024-05-03 14:24 UTC, lamtev commented on src/main/java/ru/vk/itmo/test/tyapuevdmitrij/ServerImplementation.java
> +                new ThreadPoolExecutor.CallerRunsPolicy());
Если запросы в DAO пойдут с SelectorThread, будет не очень хорошо

2024-05-03 14:24 UTC, lamtev commented on src/main/java/ru/vk/itmo/test/tyapuevdmitrij/ServerImplementation.java
> +                finalResponse.compareAndSet(finalResponse.get(), response);
к сожалению, все так же некорректная реализация

по сравнению с прошлым разом пропала проверка на то, что это самый свежий ответ

и все так же нет гарантии, что именно в итоге в finalTime и finalResponse запишутся значения из одного потока, от одного ответа

2024-05-09 14:09 UTC, lamtev commented
@typuichik123 resolve conflicts please

2024-05-25 18:53 UTC, merged