DWS | Task 1 | Ершов Вадим
polis-vk/2024-highload-dht pull request #19
Opened 2024-02-19 20:05 UTC by vadim01er

2024-02-24 14:54 UTC, atimofeyev approved these changes

2024-02-24 14:54 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/vadimershov/DaoHttpServer.java
> +    private final ReferenceDao dao;
В полях лучше использовать как можно более абстрактный класс

2024-02-24 20:20 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/vadimershov/DaoHttpServer.java
> +        byte[] value = toByteArray(entry.value());
тут лишнее копирование, которого можно было бы избежать, но пришлось бы попотеть, чтобы сразу отдавать в ответ из мемори сегмента

2024-02-25 09:21 UTC, atimofeyev requested changes

2024-02-25 09:21 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/vadimershov/ServiceImpl.java
> +    public CompletableFuture<Void> start() throws IOException {
старт и стоп лучше сделать синхронизированными, и сделать защиту всякую

2024-02-25 12:30 UTC, vadim01er commented on src/main/java/ru/vk/itmo/test/vadimershov/DaoHttpServer.java
> +        byte[] value = toByteArray(entry.value());
я посмотрел как реализован write Response до сокета, как я понимаю можно переопределить так чтоб можно было передать сразу buteByffer, но тут тоже будет аллокация, или я не в ту сторону думаю?

2024-03-01 22:46 UTC, atimofeyev approved these changes

2024-03-02 13:31 UTC, merged