Коротких Виктор / ИТМО DWS / Stage 5
polis-vk/2024-highload-dht pull request #190
Opened 2024-04-11 13:02 UTC by vitekkor

- [ ] Асинхронное взаимодействие
- [ ] Отчёт [link](url)

2024-04-29 21:03 UTC, atimofeyev requested changes

2024-05-01 09:43 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/LSMServerImpl.java
> +                clusterResponseMerger.addToMerge(i, processLocal(request, key, id, requestTimestamp));
Согласен. Ошибся. Исправил, отчёт дополнил

2024-05-05 22:23 UTC, atimofeyev approved these changes

2024-05-05 22:32 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/util/ClusterResponseMerger.java
> +    private final NodeResponse[] nodeResponses;
здесь могут быть проблемы в многопоточной среде, чтение/запись в массив идет из разных потоков. В таком случае просто final ссылка не поможет. Нужны какие-то примитивы синхронизации.

Подойдет как какая-нибудь потокобезопасная коллекция, так и AtomicReferenceArray

2024-05-09 21:37 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/util/ClusterResponseMerger.java
> +    private final NodeResponse[] nodeResponses;
Да, действительно. Затмил глаза этот word tearing с гарантиями записи из разных потоков в разным индексам массива. Заменил на AtomicReferenceArray

2024-05-14 07:29 UTC, vitekkor commented
@atimofeyev Добрый день! Так вышло, что Вадим вмерджил мой 6 stage в main раньше, чем 5й, поэтому я замерджил upstream и разрешил конфликты. Также вижу, что аппрув от вас есть, но нет оценки. Подскажите, пожалуйста, нужно ли от меня что-то ещё?

2024-05-14 18:27 UTC, atimofeyev commented
> @atimofeyev Добрый день! Так вышло, что Вадим вмерджил мой 6 stage в main раньше, чем 5й, поэтому я замерджил upstream и разрешил конфликты. Также вижу, что аппрув от вас есть, но нет оценки. Подскажите, пожалуйста, нужно ли от меня что-то ещё?

нет, больше ничего не надо, занесу скоро оценку в ведомость

2024-05-14 18:37 UTC, merged