Плясов Климентий, ИТМО DWS, stage 5
polis-vk/2024-highload-dht pull request #196
Opened 2024-04-11 15:17 UTC by Handiesto

2024-04-29 21:19 UTC, atimofeyev requested changes

2024-04-29 21:19 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/klimplyasov/ChunkGenerator.java
> +public final class ChunkGenerator {
ага, тут сразу в перемешку с 6ым стейджом, хорошо бы конечно разделить эти два PR

2024-04-29 21:19 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/klimplyasov/MergeHandleResult.java
> +            if (handleResult.status() == HttpURLConnection.HTTP_OK
а тут NPE потенциальный, массив может заполняться не по порядку

2024-04-29 21:19 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/klimplyasov/PlyasovServer.java
> +                HandleResult local = local(request, id);
ох мозг взрывается, вроде метод handleRemoteRequest, а внутри local()

2024-04-29 21:19 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/klimplyasov/PlyasovServer.java
> +        return CompletableFuture.supplyAsync(() -> {
тут мы выполняем все в commonPool. Что плохо, лучше задать свой executor

2024-05-05 22:34 UTC, atimofeyev requested changes

2024-05-05 22:34 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/klimplyasov/MergeHandleResult.java
> +    private final HandleResult[] handleResults;
здесь могут быть проблемы в многопоточной среде, чтение/запись в массив идет из разных потоков. В таком случае просто final ссылка не поможет. Нужны какие-то примитивы синхронизации.

Подойдет как какая-нибудь потокобезопасная коллекция, так и AtomicReferenceArray

2024-05-06 16:44 UTC, Handiesto commented on src/main/java/ru/vk/itmo/test/klimplyasov/ChunkGenerator.java
> +public final class ChunkGenerator {
Извините, случайно закоммитил в старый ПР

2024-05-06 16:49 UTC, Handiesto commented on src/main/java/ru/vk/itmo/test/klimplyasov/MergeHandleResult.java
> +            if (handleResult.status() == HttpURLConnection.HTTP_OK
Понял, исправлю

2024-05-06 16:50 UTC, Handiesto commented on src/main/java/ru/vk/itmo/test/klimplyasov/PlyasovServer.java
> +                HandleResult local = local(request, id);
Видимо накосячил с названиями

2024-05-15 19:57 UTC, atimofeyev approved these changes

2024-05-15 20:00 UTC, merged