Кислов Данил ИТМО ФИТиП HW6
polis-vk/2024-highload-dht pull request #203
Opened 2024-04-21 15:55 UTC by HKTRp

2024-04-22 10:11 UTC, incubos requested changes
Необходимо разрешить конфликты.

2024-05-05 08:54 UTC, daniil-ushkov commented on src/main/java/ru/vk/itmo/test/kislovdanil/report/stage6/report.md
> +можно попробовать добавить сжатие данных или как-то ускорить передачу
Непонятно поможет ли сжатие, так как тогда добавится время на компрессию и декомпрессию. 

Из того, что я видел, обычно сжатие используют не для уменьшения latency, а для реализации холодного хранилища. В этом случае о latency как раз не думают, оно напротив увеличивается. Здесь оптимизируется занимаемое место.

2024-05-05 09:24 UTC, daniil-ushkov approved these changes

2024-05-05 09:30 UTC, daniil-ushkov commented
Пробовал все ключи выгрузить из базы одним запросом?

2024-05-05 09:32 UTC, daniil-ushkov commented
@incubos 
Вадим, не сможем смерджить без твоего аппрува, так как ты поставил request changes. Аппрувни пожалуйста, конфликтов тут нет.

2024-05-05 09:38 UTC, daniil-ushkov commented on src/main/java/ru/vk/itmo/test/kislovdanil/service/DatabaseHttpServer.java
> +                ChunkTransformUtility.writeContent(it.next(), session);
Так, а если в какой-то записи лежит очень большое value. Ты будешь его целиком в сокет запихивать?

2024-05-09 17:18 UTC, HKTRp commented on src/main/java/ru/vk/itmo/test/kislovdanil/report/stage6/report.md
> +можно попробовать добавить сжатие данных или как-то ускорить передачу
В целом да, хотя я не уверен что нет алгоритмов которые бы сжимали бы быстрее чем было бы передавать, просто гипотетическое предположение

2024-05-09 17:22 UTC, HKTRp commented on src/main/java/ru/vk/itmo/test/kislovdanil/service/DatabaseHttpServer.java
> +                ChunkTransformUtility.writeContent(it.next(), session);
Да, а какие варианты? Доставать куски из MemorySegment и их по очереди записывать чтобы не переполнить память? Настолько большой value в текущей логике, кажется, просто не получится записать в бд

2024-05-14 19:30 UTC, daniil-ushkov commented on src/main/java/ru/vk/itmo/test/kislovdanil/service/DatabaseHttpServer.java
> +                ChunkTransformUtility.writeContent(it.next(), session);
Поговорил с коллегами. Обработку данного случая, мы от вас требовать не будем.

2024-05-14 19:40 UTC, daniil-ushkov commented on src/main/java/ru/vk/itmo/test/kislovdanil/service/DatabaseHttpServer.java
> +                ChunkTransformUtility.writeContent(it.next(), session);
C `session.write` вроде бы есть еще проблема. Вроде как там внутри неограниченная очередь, из-за чего теоертически клиент может медленнее отправлять чанки, чем твой код их туда пушит. И это в конечном итоге может привести к тому, что мы таки выгрузим много данных в оперативную память.

Однако я считаю, что перебор от вас такое требовать)

2024-05-28 15:43 UTC, closed without merging