Коротких Виктор / ИТМО DWS / Stage 6
polis-vk/2024-highload-dht pull request #211
Opened 2024-04-24 16:35 UTC by vitekkor

2024-05-01 20:59 UTC, incubos requested changes
Есть несколько вопросов и замечаний.

2024-05-01 20:59 UTC, incubos commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/LSMServerImpl.java
> +            log.debug("Bad request: empty id parameter");
Неверный текст. Почему `debug()`?

2024-05-01 20:59 UTC, incubos commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/LSMServiceImpl.java
> +        localProcessor = createExecutorService(16, 1024, "local-processor");
Все эти числа должны быть константами с говорящими именами.

2024-05-01 20:59 UTC, incubos commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/http/LSMCustomSession.java
> +        if (this.lsmRangeWriter.hasChunks()) {
Нет ли здесь ошибки? У нас ещё есть неотправленные чанки, а мы переходим к обработке следующего входящего запроса...

2024-05-01 20:59 UTC, incubos commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/reports/stage6/report.md
> +Запрос: `curl -vvv --location 'http://localhost:8080/v0/entities?start=key'`
Зачем `--location`?

2024-05-01 21:25 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/http/LSMCustomSession.java
> +        if (this.lsmRangeWriter.hasChunks()) {
Да, это меня тоже смутило, когда я рефакторинг кода делал. Но отталкивался я от реализации метода sendResponse - там как раз идёт отправка ответа и переход к обработке следующего. Да, там ситуация другая с той точки зрения того, что мы по сути отправляем весь ответ сразу. Но нам могло не повезти и мы могли записать в сокет не весь ответ.  Ну или же банально - у нас queueHead != null и мы наш Response добавили в очередь. Тогда по сути мы также пойдем дальше обрабатывать запросы.

Поэтому я тут сомневаюсь

2024-05-01 21:25 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/reports/stage6/report.md
> +Запрос: `curl -vvv --location 'http://localhost:8080/v0/entities?start=key'`
По привычке вставил

2024-05-01 21:26 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/LSMServiceImpl.java
> +        localProcessor = createExecutorService(16, 1024, "local-processor");
Исправил

2024-05-01 21:26 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/LSMServerImpl.java
> +            log.debug("Bad request: empty id parameter");
В одном из прошлых PR поменял всё логгирование на уровень debug, кроме error. Текст исправил

2024-05-11 08:56 UTC, incubos commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/http/LSMCustomSession.java
> +        if (this.lsmRangeWriter.hasChunks()) {
В существующей реализации `sendResponse()` мы ставим **весь** готовый `Response` в очередь на отправку в сокет, поэтому можем переходить к обработке следующего запроса, потому что его ответ уйдёт в сокет **после** предыдущего.
В случае streaming всё совсем не так.

2024-05-11 08:58 UTC, incubos approved these changes
10 баллов.

2024-05-11 08:58 UTC, merged