Тузиков Александр, ИТМО DWS, Stage 6
polis-vk/2024-highload-dht pull request #217
Opened 2024-04-24 21:17 UTC by alexBlack01

Без отчета

Хотел реализовать с использованием processWrite, но что-то не работало ничего(

2024-04-30 19:44 UTC, atimofeyev requested changes

2024-04-30 19:44 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/StreamResponse.java
> +public class StreamResponse extends Response {
если были на разборе 6го этапа, то наверное уже поняли что в этом решении вы потенциально все данные можете запихать в память, если с сетью какие-то проблемы

Тут надо обратить внимание на то что под капотом у sesion.write() и попробовать реализовать иенно асинхронную запись

2024-04-30 19:47 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/StreamResponse.java
> +        byte[] resultValue = new byte[keyInBytes.length + valueInBytes.length + Constants.NEW_LINE.length
ну и достаточно много лишних аллокаций, которых можно было бы избежать.
Есть два варианта:
1. Использовать какие-то пулы буфферов
2. Попробовать писать в сокет прямо из MemorySegment-a

2024-04-30 22:14 UTC, alexBlack01 commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/StreamResponse.java
> +        byte[] resultValue = new byte[keyInBytes.length + valueInBytes.length + Constants.NEW_LINE.length
Да, по аллокациям вообще ужас получился, страшно смотреть. Буду пробовать исправлять

2024-05-05 08:07 UTC, alexBlack01 commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/StreamResponse.java
> +public class StreamResponse extends Response {
То есть надо было оставаться на том же алгоритме, что и у one.nio? Что мы можем не до конца сразу все записать, а вернуться к этому потом?

2024-05-14 18:44 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/StreamResponse.java
> +public class StreamResponse extends Response {
да, надо запоминать сколько мы записали, а далее по событию о том что сеть опять готова на запись - записать остальное

2024-05-26 18:55 UTC, atimofeyev approved these changes

2024-05-26 18:56 UTC, atimofeyev commented
поправьте конфликт пожалуйста чтобы смежить

2024-05-28 15:34 UTC, closed without merging