Супрядкина Дарья ИТМО DWS stage 6
polis-vk/2024-highload-dht pull request #218
Opened 2024-04-24 23:53 UTC by SuDarina

Только код

2024-05-02 08:40 UTC, incubos requested changes
Есть существенные замечания и вопросы -- ждём исправлений/ответов.

2024-05-02 08:40 UTC, incubos commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/report/hw6/REPORT.md
> +вероятно, лишнее использование Session.write может привести к затратам на синхронизацию, отчего в конце концов пострадает latency
У нас в сессию пишет один поток, поэтому никакого contention нет и затраты на синхронизацию не изменятся.

2024-05-02 08:40 UTC, incubos commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/report/hw6/REPORT.md
> +    session.write(bb.toBytes(), 0, bb.length());
`toBytes()`, который генерирует больше 16% аллокаций, можно заменить на `buffer()` и устранить аллокации вообще, верно? Это всё видно в профиле `range-alloc-3.html`.

2024-05-02 08:40 UTC, incubos commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/report/hw6/REPORT.md
> +[range-alloc-3.html](data%2Frange-alloc-3.html)
И как указывалось выше, мы вызываем `get...Chunk()` по два раза -- можно срезать количество аллокаций этих методов, верно?

2024-05-02 09:02 UTC, SuDarina commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/SelfRequestHandler.java
> +        }
Попробую

2024-05-11 09:01 UTC, incubos requested changes
Всё ещё ждём исправлений, иначе максимум 7 баллов.
Нужно пофиксить конфликты перед merge.

2024-05-15 19:29 UTC, SuDarina commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/EntryChunkUtils.java
> +                    HTTP/1.1 200 OK\r
Изначально я написала что-то вроде "HTTP/1.1 200 OK\r\n" + "Content-Type: text/plain\r\n...

Но IDEA сама предложила заменить на текстовый блок. Как я понимаю, там учитываются переносы

2024-05-15 19:30 UTC, SuDarina commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/EntryChunkUtils.java
> +        bb.append(EntryChunkUtils.getEntryValueChunk(ee), 0, EntryChunkUtils.getEntryValueChunk(ee).length);
Исправлено

2024-05-15 19:30 UTC, SuDarina commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/SelfRequestHandler.java
> +        }
Переделано

2024-05-15 19:30 UTC, SuDarina commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/report/hw6/REPORT.md
> +    session.write(bb.toBytes(), 0, bb.length());
Исправлено

2024-05-15 19:30 UTC, SuDarina commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/report/hw6/REPORT.md
> +[range-alloc-3.html](data%2Frange-alloc-3.html)
Исправлено

2024-05-19 10:34 UTC, incubos approved these changes
12 баллов.

2024-05-19 10:34 UTC, incubos commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/CustomHttpSession.java
> +        scheduleClose();
Мы могли не всё отправить, но всегда инициируем закрытие сессии, верно?

2024-05-19 10:34 UTC, merged