Далбеев Георгий / ИТМО DWS / Stage 6
polis-vk/2024-highload-dht pull request #227
Opened 2024-04-25 15:21 UTC by goshadalbeev

2024-04-30 19:53 UTC, atimofeyev requested changes

2024-04-30 19:53 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/georgiidalbeev/MyIterableQueueItem.java
> +        builder.append(CRLF);
builder в данном случае не самое удачное решение, он будет создавать лишни аллокации, которых мы могли бы избежать, так как можем посчитать настоящий размер массива

2024-04-30 19:53 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/georgiidalbeev/MyIterableQueueItem.java
> +        return socket.write(builder.toBytes(), 0, builder.length());
здесь в сокет мы можем записать не все или вообще ничего не записать

2024-05-09 13:22 UTC, goshadalbeev commented on src/main/java/ru/vk/itmo/test/georgiidalbeev/MyIterableQueueItem.java
> +        builder.append(CRLF);
Исправил, убрал билдер

2024-05-09 13:22 UTC, goshadalbeev commented on src/main/java/ru/vk/itmo/test/georgiidalbeev/MyIterableQueueItem.java
> +        return socket.write(builder.toBytes(), 0, builder.length());
Исправил, пишу сразу в сокет

2024-05-14 19:40 UTC, atimofeyev requested changes

2024-05-14 19:40 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/georgiidalbeev/MyIterableQueueItem.java
> +            written += socket.write(headers, 0, headers.length);
проблема то не ушла, соке твсе так же может записать не все то передано, а только 1 байт например, и в следующий раз надо начать со второго байта, а не переходит ьк следующему чанку

2024-05-19 18:59 UTC, goshadalbeev commented on src/main/java/ru/vk/itmo/test/georgiidalbeev/MyIterableQueueItem.java
> +            written += socket.write(headers, 0, headers.length);
исправил. в случае, если за один раз удалось записать только часть данных, последующая попытка записи начнется с места, на котором остановилась предыдущая.

2024-05-26 18:52 UTC, atimofeyev approved these changes

2024-05-26 18:53 UTC, atimofeyev commented
поправьте конфликт пожалуйста, чтобы смержить

2024-05-28 15:34 UTC, closed without merging