Плясов Климентий, ИТМО DWS, stage 6
polis-vk/2024-highload-dht pull request #228
Opened 2024-04-25 17:18 UTC by Handiesto

2024-04-28 13:42 UTC, incubos commented
PR открыт после soft deadline, поэтому максимум 5 баллов.

2024-05-02 09:39 UTC, incubos requested changes
Стриминг получился жадным, а не ленивым. Есть вопросы к реализации и результатам профилирования.

2024-05-02 09:39 UTC, incubos commented on src/main/java/ru/vk/itmo/test/klimplyasov/PlyasovServer.java
> +            handleOtherRequest(request, session);
Не очень удачное имя метода.

2024-05-02 09:39 UTC, incubos commented on src/main/java/ru/vk/itmo/test/klimplyasov/PlyasovServer.java
> +        }
В случае медленного клиента мы затянем все данные в память и упадём по OOM, верно? Вся суть задания в том, чтобы этого избежать. Будете переделывать?

2024-05-02 09:39 UTC, incubos commented on src/main/java/ru/vk/itmo/test/klimplyasov/reports_hw6/stage6.md
> +- writeDataChunk - 70%
Откуда на профиле аллокаций `Class.getSimpleName()` с почти 20%?

2024-05-02 09:39 UTC, incubos commented on src/main/java/ru/vk/itmo/test/klimplyasov/reports_hw6/stage6.md
> +- writeDataChunk - 70%
Откуда аллокация `HeapByteBuffer`? Можно её избежать?

2024-05-06 16:54 UTC, Handiesto commented on src/main/java/ru/vk/itmo/test/klimplyasov/PlyasovServer.java
> +        }
Немного не пониманию, я же отправляю в сессию данные, ничего не оставляя в памяти. Подскажите, пожалуйста, что не так?

2024-05-11 09:04 UTC, incubos commented on src/main/java/ru/vk/itmo/test/klimplyasov/PlyasovServer.java
> +        }
Данные не отправляются сразу, с ставятся в очередь на отправку -- см. `Session.write()`. Но в очередь добавляется всё содержимое `Iterator`, т.е. никакого streaming нет.

2024-05-11 09:05 UTC, incubos requested changes
Функционально реализовано неверно, потому что отправка жадная. Будете исправлять? Напоминаю, что максимум 5 баллов, потому что после soft deadline.

2024-05-15 15:06 UTC, Handiesto commented
@incubos Не буду. К сожалению, мне уже не хватает баллов до 50(

2024-05-15 15:12 UTC, Handiesto commented on src/main/java/ru/vk/itmo/test/klimplyasov/PlyasovServer.java
> +        }
Понял, спасибо

2024-05-18 17:19 UTC, incubos commented
Тогда 1 балл за попытку :(

2024-05-18 17:19 UTC, closed without merging