Тузиков Александр, ИТМО DWS, Stage 7
polis-vk/2024-highload-dht pull request #230
Opened 2024-05-15 10:21 UTC by alexBlack01

Read Repair (со множеством недостатков)

2024-05-18 17:22 UTC, incubos requested changes
Нужно бы подмёрджить upstream и зарезолвить конфликты, чтобы ревьюить только по существу.

2024-05-18 17:22 UTC, incubos commented
И CodeClimate остаётся обязательным.

2024-05-19 11:22 UTC, incubos requested changes
Часть тестов сломана:
```java
ReadRepairTest > getValue(List) > [1] [ru.vk.itmo.ServiceInfo@758c83d8, ru.vk.itmo.ServiceInfo@129b4fe2] FAILED
    org.opentest4j.AssertionFailedError at ReadRepairTest.java:21

TwoNodeTest > missedDelete(List) > [1] [ru.vk.itmo.ServiceInfo@2160e52a, ru.vk.itmo.ServiceInfo@29f0802c] FAILED
    org.opentest4j.AssertionFailedError at TwoNodeTest.java:196

TwoNodeTest > missedOverwrite(List) > [1] [ru.vk.itmo.ServiceInfo@5d39f2d8, ru.vk.itmo.ServiceInfo@6ad6fa53] FAILED
    org.opentest4j.AssertionFailedError at TwoNodeTest.java:230

TwoNodeTest > missedWrite(List) > [1] [ru.vk.itmo.ServiceInfo@3c89bb12, ru.vk.itmo.ServiceInfo@48c4245d] FAILED
    org.opentest4j.AssertionFailedError at TwoNodeTest.java:164

TwoNodeTest > missedRecreate(List) > [1] [ru.vk.itmo.ServiceInfo@3e48e859, ru.vk.itmo.ServiceInfo@31ddd4a4] FAILED
    org.opentest4j.AssertionFailedError at TwoNodeTest.java:268

39 tests completed, 5 failed
```

Будете исправлять?

2024-05-19 20:05 UTC, alexBlack01 commented
Поправил тесты прошлых этапов. Падает только собственно написанный тест(

2024-05-25 17:10 UTC, incubos commented
Сложно проверять, потому что в PR каким-то образом также попал 6 этап.

2024-05-25 18:08 UTC, incubos reviewed
Есть ряд существенных замечаний к эффективности реализации и к единственному тесту. 5 баллов за попытку.

2024-05-25 18:08 UTC, incubos commented on src/test/java/ru/vk/itmo/ReadRepairTest.java
> +        HttpResponse<byte[]> responseService0 = serviceInfos.get(0).get(key, 1,1);
```suggestion
        HttpResponse<byte[]> responseService0 = serviceInfos.get(0).get(key, 1, 1);
```

2024-05-25 18:08 UTC, incubos commented on src/test/java/ru/vk/itmo/ReadRepairTest.java
> +        assertEquals(HttpURLConnection.HTTP_CREATED, serviceInfos.get(0).upsert(key, value2, 1, 1).statusCode());
Тест падает на этой строке:
```java
ReadRepairTest > getValue(List) > [1] [ru.vk.itmo.ServiceInfo@758c83d8, ru.vk.itmo.ServiceInfo@129b4fe2] FAILED
    org.opentest4j.AssertionFailedError at ReadRepairTest.java:28
```
Видимо, опущенная нода `1` является владельцем ключа?

2024-05-25 18:08 UTC, incubos commented on src/test/java/ru/vk/itmo/ReadRepairTest.java
> +        responseService1 = serviceInfos.get(1).get(key, 1,1);
Тест концептуально некорректный, потому что `from == 1` -- мы обращаемся ровно к одной ноде.

2024-05-25 18:23 UTC, closed without merging