Решетников Алексей, ИТМО DWS, stage 1
polis-vk/2024-highload-dht pull request #33
Opened 2024-02-21 17:19 UTC by lehatheslayer

2024-02-21 21:11 UTC, lehatheslayer commented
Обернул `dao.upsert(...)` в трай-кетч для обработки `IllegalStateException`, чтобы при `flush` сервер не ломался, из-за чего какой-то тест решил не проходить в ci, хотя локально все ок. В итоге убрал обертку в трай-кетч. По идее эта обертка не нужна для `RPS`, который я выбрал, без него все ок проходит, она нужна была, чтобы попытаться прогнать на `RPS` больше `10 000`

2024-02-25 11:25 UTC, incubos approved these changes
Есть ряд замечаний и вопросов.
12 баллов.

2024-02-25 11:25 UTC, incubos commented on src/main/java/ru/vk/itmo/test/reshetnikovaleksei/HttpServerImpl.java
> +    private ReferenceDao dao;
Почему конкретный класс, а не интерфейс?

2024-02-25 11:25 UTC, incubos commented on src/main/java/ru/vk/itmo/test/reshetnikovaleksei/HttpServerImpl.java
> +        this.daoConfig = createDaoConfig(config);
Гибче создавать DAO снаружи и передавать в конструктор. Ровно для этого и есть `Service`.

2024-02-25 11:25 UTC, incubos commented on src/main/java/ru/vk/itmo/test/reshetnikovaleksei/HttpServerImpl.java
> +        Entry<MemorySegment> result = dao.get(parseToMemorySegment(id));
Здесь и ниже не обрабатываются возможные исключения DAO.

2024-02-25 11:25 UTC, incubos commented on src/main/java/ru/vk/itmo/test/reshetnikovaleksei/HttpServerImpl.java
> +        dao.upsert(new BaseEntry<>(parseToMemorySegment(id), MemorySegment.ofArray(request.getBody())));
Если у запроса нет тела, то мы `PUT`ом делаем `DELETE`? Нехорошо.

2024-02-25 11:25 UTC, incubos commented on src/main/java/ru/vk/itmo/test/reshetnikovaleksei/lua/stage1.md
> +  Non-2xx or 3xx responses: 575
Откуда эти 575 неожиданных ответов?

2024-02-25 11:25 UTC, incubos commented on src/main/java/ru/vk/itmo/test/reshetnikovaleksei/lua/stage1.md
> +- 26% cpu потрачено на `flush`
А остальной CPU на что ушёл?

2024-02-25 11:25 UTC, incubos commented on src/main/java/ru/vk/itmo/test/reshetnikovaleksei/lua/stage1.md
> +Методом проб и ошибок, аналогичный при `PUT TEST`, был выбран `RPS`, равный `300`
Интересно, что 300 rps -- у вас HDD?

2024-02-27 11:52 UTC, incubos requested changes
Один тест не проходит -- надо пофиксить:
```java
15:02:12.354 [NIO Selector #9] ERROR one.nio.net.Session -- Cannot process session from 127.0.0.1
java.lang.IllegalStateException: Can't keep up with flushing!
	at ru.vk.itmo.test.reference.dao.ReferenceDao.upsert(ReferenceDao.java:88)
	at ru.vk.itmo.test.reshetnikovaleksei.HttpServerImpl.delete(HttpServerImpl.java:67)
	at RequestHandler2_delete.handleRequest(Unknown Source)
	at one.nio.http.HttpServer.handleRequest(HttpServer.java:66)
	at one.nio.http.HttpSession.handleParsedRequest(HttpSession.java:137)
	at one.nio.http.HttpSession.processHttpBuffer(HttpSession.java:198)
	at one.nio.http.HttpSession.processRead(HttpSession.java:77)
	at one.nio.net.Session.process(Session.java:222)
	at one.nio.server.SelectorThread.run(SelectorThread.java:70)

java.io.IOException: HTTP/1.1 header parser received no bytes

	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:964)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
	at ru.vk.itmo.ServiceInfo.delete(ServiceInfo.java:45)
	at ru.vk.itmo.SingleNodeTest.lifecycle2keys(SingleNodeTest.java:124)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.io.IOException: HTTP/1.1 header parser received no bytes
	at java.net.http/jdk.internal.net.http.common.Utils.wrapWithExtraDetail(Utils.java:388)
	at java.net.http/jdk.internal.net.http.Http1Response$HeadersReader.onReadError(Http1Response.java:590)
	at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.checkForErrors(Http1AsyncReceiver.java:302)
	at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.flush(Http1AsyncReceiver.java:268)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:182)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.EOFException: EOF reached while reading
	at java.net.http/jdk.internal.net.http.Http1AsyncReceiver$Http1TubeSubscriber.onComplete(Http1AsyncReceiver.java:601)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadSubscription.signalCompletion(SocketTube.java:648)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketTube.java:853)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:181)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:280)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:233)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(SocketTube.java:782)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(SocketTube.java:965)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:253)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:1467)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:1412)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:1412)
```

2024-02-27 17:43 UTC, lehatheslayer commented on src/main/java/ru/vk/itmo/test/reshetnikovaleksei/lua/stage1.md
> +Методом проб и ошибок, аналогичный при `PUT TEST`, был выбран `RPS`, равный `300`
сам в шоке был, вроде бы ссд
все еще подозрения на уставший ноутбук (в целом система очень сильно подтормаживает)

2024-02-29 08:55 UTC, merged