Коротких Виктор / ИТМО DWS / Stage 1
polis-vk/2024-highload-dht pull request #4
Opened 2024-02-18 13:46 UTC by vitekkor

2024-02-25 09:41 UTC, atimofeyev requested changes
Здорово воспользовались результатами профилирования чтобы затюнить респонсы на put/delete

2024-02-25 09:41 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/LSMServiceImpl.java
> +        if (isRunning.getAndSet(true)) return CompletableFuture.completedFuture(null);
лучше сделать start/stop synchronized, а то все равно получилось не безопасно, если будут долюить параллельно

2024-02-25 13:58 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/LSMServerImpl.java
> +        Response response = switch (request.getMethod()) {
Добавил локальную обработку exception в самих методах обработки запроса и глобальный try-catch в переопределённом методе handleRequest

2024-02-25 13:58 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/http/LSMCustomSession.java
> +        String connection = handling.getHeader("Connection:");
Заменил на вызов статического метода из LSMConstantResponse

2024-02-25 13:59 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/LSMServiceImpl.java
> +        if (isRunning.getAndSet(true)) return CompletableFuture.completedFuture(null);
Сделал методы start/stop synchronized

2024-03-01 22:21 UTC, atimofeyev approved these changes
15 баллов

2024-03-01 22:24 UTC, merged