Пронин Валентин / ИТМО DWS / Stage 2
polis-vk/2024-highload-dht pull request #47
Opened 2024-02-24 16:48 UTC by GonarchX

На данный момент только код

2024-02-25 14:17 UTC, incubos requested changes
Есть ряд вопросов и замечаний к реализации. Ждём исправлений.

2024-02-25 14:17 UTC, incubos commented on src/main/java/ru/vk/itmo/test/proninvalentin/Server.java
> +        String responseCode = e.getClass() == HttpException.class
Нужен ли этот метод? Можно заинлайнить в `processRequest()` и явно ловить там `HttpException`.

2024-02-25 14:17 UTC, incubos commented on src/main/java/ru/vk/itmo/test/proninvalentin/Server.java
> +        workerPool.gracefulShutdown();
Освобождать ресурсы лучше там же, где выделяли.

2024-02-25 14:17 UTC, incubos commented on src/main/java/ru/vk/itmo/test/proninvalentin/WorkerPool.java
> +            awaitTermination(20, TimeUnit.SECONDS);
Лучше сделать константой.

2024-02-25 14:17 UTC, incubos commented on src/main/java/ru/vk/itmo/test/proninvalentin/WorkerPool.java
> +        }
Зачем это делать? Может, кинуть исключение наверх, что не смогли мол дождаться останова.

2024-02-25 16:31 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/Server.java
> +        String responseCode = e.getClass() == HttpException.class
IDE'шка просто не знает, что `super.handleRequest(request, session);` может кинуть HttpException и из-за этого warning выдает на `e.getClass() == HttpException.class`, поэтому решил в метод упрятать.

2024-02-25 16:54 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/WorkerPoolConfig.java
> +        int maxQueueSize = 4200;
Пока что не профилировал приложение, оставил случайное значение

2024-02-25 17:08 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/Server.java
> +            sendResponse(session, new Response(ResponseCode.REQUEST_TIMEOUT, Response.EMPTY));
Точно, пропустил, спасибо

2024-02-25 17:20 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/WorkerPool.java
> +        }
Не совсем понял мысль: лучше еще кинуть исключение после остановки потока?

2024-02-25 18:24 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/WorkerPoolConfig.java
> +                new ThreadPoolExecutor.DiscardPolicy());
Перепутал, хотел AbortPolicy, спасибо

2024-03-03 12:34 UTC, incubos commented on src/main/java/ru/vk/itmo/test/proninvalentin/WorkerPool.java
> +        }
В случае `InterruptedException` кинуть наверх своё исключение -- мол, прервались во время ожидания останова. Но можно и так оставить.

2024-03-03 12:49 UTC, incubos commented
Спасибо за исправления. Ждём нагрузочное тестирование, профилирование и анализ результатов.

2024-03-03 12:50 UTC, incubos requested changes
Спасибо за исправления. Ждём нагрузочное тестирование, профилирование и анализ результатов.

2024-03-10 12:25 UTC, incubos requested changes
Необходимо зарезолвить конфликты перед merge.

2024-03-10 13:12 UTC, incubos requested changes
Есть ряд вопросов. Ждём комментариев и резолва конфликтов перед merge.

2024-03-10 13:12 UTC, incubos commented on src/main/java/ru/vk/itmo/test/proninvalentin/reports/stage2/report.md
> +  нагрузки не тратить ресурсы на выделение новых потоков.
Потоки всё равно выделяются по мере надобности, если вы не делаете явно `prestartAllCoreThreads()`. Как исключить влияние на селекторы, которые тоже хотят вычислительные ресурсы?

2024-03-10 13:12 UTC, incubos commented on src/main/java/ru/vk/itmo/test/proninvalentin/reports/stage2/report.md
> +При использовании LinkedBlockingQueue можно увидеть, что общее время на запись в сессию увеличилось,
Не до конца понятно... 2.31% меньше чем 13.33% -- как вы это интерпретируете? Если мы профилируем lock, то:

> In lock profiling mode the top frame is the class of lock/monitor, and the counter is number of nanoseconds it took to enter this lock/monitor.

Можете пояснить мысль?

2024-03-10 13:12 UTC, incubos commented on src/main/java/ru/vk/itmo/test/proninvalentin/reports/stage2/report.md
> +Но, конечно, выбирать стоит `PriorityBlockingQueue` вкупе с ошибкой 'Payment required' для самых медленных запросов (шутка с лекции)
А если серьёзно, в чём видите фундаментальный недостаток `PriorityBlockingQueue`?

2024-03-10 13:12 UTC, incubos commented on src/main/java/ru/vk/itmo/test/proninvalentin/reports/stage2/report.md
> +  мониторинге сервера мы также этого не увидим
Ещё непонятно, что делать с клиентскими соединениями, обработку запроса из которых пул отбросил.

2024-03-10 13:12 UTC, incubos commented on src/main/java/ru/vk/itmo/test/proninvalentin/reports/stage2/report.md
> +Также стоит отметить тот факт, что при текущих lua скриптах все потоки генерируют одинаковые данные, из-за этого
Поправите в следующих этапах?

2024-03-12 18:43 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/reports/stage2/report.md
> +Но, конечно, выбирать стоит `PriorityBlockingQueue` вкупе с ошибкой 'Payment required' для самых медленных запросов (шутка с лекции)
Из предположений: дорого сортировать запросы, когда у нас уже имеется много необработанных запросов в очереди и нам внезапно прилетает запрос, который мы должны обработать быстрее остальных.

2024-03-12 18:44 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/reports/stage2/report.md
> +работы с воркерами и их создание
Неправильно написал, хотел сказать, что работа, связанные с воркерами, в флеймграфе занимает половину семплов от общего количества. 

![image](https://github.com/polis-vk/2024-highload-dht/assets/62358071/f4584ab3-59bc-430e-9b0c-bec946c8d149)

2024-03-12 18:45 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/reports/stage2/report.md
> +| Запуск селекторов                   | 47.7%   | 94%      | В версии с пулом половина общей памяти уходит также на создание воркеров
Аналогичная ошибка, что и выше. В версии с пулом воркеры занимают половину сэмплов, соответственно и работа селекторов теперь занимает вдвое меньше

2024-03-12 18:45 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/reports/stage2/report.md
> +| Поллинг запросов          | 40%     | 27%      | Теперь селектору в версии с пулом можно больше времени тратить на поллинг и скедулинг запросов, т.к. воркер треды забрали часть его работы |
Извиняюсь, неправильно выразился, действительно сэмплы

2024-03-12 18:48 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/reports/stage2/report.md
> +Также стоит отметить тот факт, что при текущих lua скриптах все потоки генерируют одинаковые данные, из-за этого
Самое простое - использовать случайные значения, но, возможно, в wrk уже есть решение для генерации разных данных для разных потоков

2024-03-12 18:52 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/reports/stage2/report.md
> +  мониторинге сервера мы также этого не увидим
Да, при таком подходе им придется, видимо, ожидать таймаута, что не есть хорошо

2024-03-12 19:31 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/reports/stage2/report.md
> +целом, это больше похоже на артефакты, тк профили показывают аналогичную с предыдущими запусками картину
Имел ввиду ситуации, когда у нас запрос долго обрабатывается по причине того, что началась сборка мусора или возникли проблемы с сетью, если бы мы профилировали по честному

2024-03-12 19:46 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/reports/stage2/report.md
> +вместо этого он теперь может сразу заняться обработкой следующего запроса.
Я бы сказал что это из-за того, что профилировать нужно было более продолжительное время и несколько раз, анализируя то, как изменяется время по перцентилям, т.к. периодически между запусками с одними и теми же настройками время скакало.

Но также можно объяснить тем, что мы теперь в среднем тратим чуть больше времени на обработку запроса, т.к. теперь в пайплайн обработки запроса добавляется часть, когда селектору нужно положить запрос в очередь, а воркеру из очереди его взять перед тем непосредственной обработкой запроса.

2024-03-12 20:10 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/reports/stage2/report.md
> +Я связываю это с тем, что 8 селекторов просто не успевают опрашивать такое количество соединений, учитывая тот факт, что
Странно при 512 и 1024 соединениях и при 50 потоках тоже не выдерживает, очередь увеличил, подумал, что в ней проблема. 
Затем увеличил количество селекторов до 16 - аналогичная ситуация.
При этом, при возвращении на 200 соединений уровень максимальной нагрузки повышается.

2024-03-12 20:19 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/reports/stage2/report.md
> +  нагрузки не тратить ресурсы на выделение новых потоков.
Как раз использовал `prestartAllCoreThreads`
"Исключить влияние" имеется ввиду: как мы можем полностью изолировать селектор потоки от воркеров или не тратить ресурсы на выделение новых потоков при достижении пиковой нагрузки?
Если второе, то можем прогреть сервер до запуска в прод

2024-03-12 20:22 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/reports/stage2/report.md
> +### ALLOC Flame Graph
Добавил 
Путь до графа с тредом:
ru/vk/itmo/test/proninvalentin/reports/stage2/aprof/put/profile-put-30000-1t-8c/profile-alloc-put-30000-1t-8c.html

Путь до графа без треда:
ru/vk/itmo/test/proninvalentin/reports/stage1/aprof/put/alloc/profile-alloc-put-30000.html

2024-03-12 20:39 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/reports/stage2/report.md
> +При использовании LinkedBlockingQueue можно увидеть, что общее время на запись в сессию увеличилось,
Хотел сказать, что времени на работу с сессией стало больше с добавлением LinkedBlockingQueue, т.к. теперь у нас меньше времени уходит на ожидание лока для взятия/добавления задачи в очередь. Но описал  я это действительно криво

2024-03-17 12:48 UTC, incubos commented on src/main/java/ru/vk/itmo/test/proninvalentin/reports/stage2/report.md
> +работы с воркерами и их создание
Это ведь тоже не совсем верно: работу теперь выполняют не селекторы, а отдельные потоки -- поэтому флеймграф изменился.

2024-03-17 13:07 UTC, incubos commented on src/main/java/ru/vk/itmo/test/proninvalentin/reports/stage2/report.md
> +целом, это больше похоже на артефакты, тк профили показывают аналогичную с предыдущими запусками картину
Какие проблемы с сетью? Вы же локально делаете запросы.

2024-03-17 13:11 UTC, incubos approved these changes
15 баллов.

2024-03-17 13:11 UTC, merged