HW 2 Шишигит Степан ИТМО DWS
polis-vk/2024-highload-dht pull request #52
Opened 2024-02-26 16:06 UTC by sshishigin

2024-03-02 18:40 UTC, atimofeyev requested changes
Не вижу отчета второго этапа

2024-03-02 18:40 UTC, atimofeyev commented on .codeclimate.yml
> +      channel: "10.13.0"
это для чего?

2024-03-04 15:53 UTC, sshishigin commented on .codeclimate.yml
> +      channel: "10.13.0"
пытался климат починит для определенного синтаксиса, уберу

2024-03-04 21:26 UTC, sshishigin commented
> Не вижу отчета второго этапа

Отчёт подгрузил.

2024-03-09 18:30 UTC, atimofeyev requested changes

2024-03-09 18:30 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/shishiginstepan/profiling/profiling2.MD
> +<img height="500" src="/home/stepan/IdeaProjects/2024-highload-dht/src/main/java/ru/vk/itmo/test/shishiginstepan/profiling/profiling_artifacts_2/cpu-selector-thread.png" width="1280"/>
тут абсолютные пути - не удобно читать ридми, хорошо бы сделать относительные

2024-03-09 18:30 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/shishiginstepan/profiling/profiling2.MD
> +Можно заметить что порядка 10 процентов общего времени селекторы провели в блокировках при постановке в очередь тасков на обработку
можно ли это как-то оптимизировать?

2024-03-10 18:49 UTC, sshishigin commented on src/main/java/ru/vk/itmo/test/shishiginstepan/profiling/profiling2.MD
> +Можно заметить что порядка 10 процентов общего времени селекторы провели в блокировках при постановке в очередь тасков на обработку
Можно проэкспериментировать с неблокирующими очередями

2024-03-10 18:50 UTC, sshishigin commented on src/main/java/ru/vk/itmo/test/shishiginstepan/server/Server.java
> +                        logger.error(exceptionHandlingException.initCause(e));
Если правильно помню, то при запуске запросов в executor'е  сессия перестала у меня справляться с обработкой такого рода ошибок и просто висела незакрытой.

2024-03-12 20:31 UTC, atimofeyev approved these changes

2024-03-12 20:32 UTC, merged