Обновление версии checkstyle (Java21 compatabiliy, ci fails)
polis-vk/2024-highload-dht pull request #53
Opened 2024-02-26 22:14 UTC by sshishigin

Предлагаю свой фикс для починки использования Checkstyle в CI.
Ранее использовавшаяся версия checkstyle:10.3.3 не поддерживала синтаксис строковых шаблонов из JDK 21

ПР с изменениями касающимися этих изменений в честайл:
https://github.com/checkstyle/checkstyle/issues/13830

Так же при сборке новой версии чекстайл (checkstyle:10.13.0) проявляется баг graddle упомянутый в ПР по ссылке:
https://github.com/spotbugs/spotbugs/pull/2798

Фикс предлагаемый в этом ПР применен, сборка проходит

2024-02-26 22:20 UTC, sshishigin commented
@incubos писал в беседе в ВК об этом баге

2024-02-27 08:14 UTC, incubos requested changes
Spring добавлять не хотелось бы. Есть вопрос.

2024-02-27 08:29 UTC, merged

2024-02-27 09:39 UTC, sshishigin commented
@incubos 
Теперь checkstyle проходит при сборке, но code climate не умеет работать с этой версией checkstyle
В документации указано что последняя версия которую климат поддерживает это 9.2 (нам нужно 10.13.0)
https://docs.codeclimate.com/docs/checkstyle

Видимо время забить на строковые шаблоны?

2024-02-27 11:44 UTC, incubos commented
> @incubos Теперь checkstyle проходит при сборке, но code climate не умеет работать с этой версией checkstyle В документации указано что последняя версия которую климат поддерживает это 9.2 (нам нужно 10.13.0) https://docs.codeclimate.com/docs/checkstyle
> 
> Видимо время забить на строковые шаблоны?

Да, придётся забить :( Откачу коммит.