Тузиков Александр, ИТМО DWS, Stage 1
polis-vk/2024-highload-dht pull request #6
Opened 2024-02-18 14:44 UTC by alexBlack01

Отчет доделаю, некоторые диаграммы также поправлю

2024-02-25 12:45 UTC, incubos requested changes
Есть ряд вопросов и замечаний. Анализ результатов профилирования очень поверхностный и абстрактный. Требуются исправления перед merge.
9 баллов.

2024-02-25 12:45 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/results/stage1/report.md
> +- Выделение памяти (ALLOC) в значительной степени происходит при конвертации данных из MemorySegment в байтовые массивы.
А ещё где аллоцируется память? Нужен полноценный анализ.

2024-02-25 12:45 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/results/stage1/report.md
> +Также как и при вставке данных, большая часть - обработка запроса.
Можно конкретнее? Суть нашего сервиса и заключается в обработке запросов. Нет запросов -- нет работы. На что расходуются ресурсы?

2024-02-25 12:45 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/results/stage1/report.md
> +2. Оптимизация настроек сервера: Ревизия и настройка конфигураций сервера может способствовать более эффективной обработке запросов.
Так давайте проведём "ревизию"? Это же ваш код. Что именно предлагается?

2024-02-25 12:45 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/results/stage1/report.md
> +3. Оптимизация работы со строками и данными: Рассмотрение возможности получения и обработки данных сразу в байтовом представлении может уменьшить нагрузку на процессор и время отклика за счет сокраще
Так давайте рассмотрим возможность? Это же ваш код.

2024-02-27 11:50 UTC, incubos requested changes
Один тест не проходит -- надо пофиксить.

2024-02-28 16:30 UTC, alexBlack01 commented on build.gradle
> +
Да, упустил этот момент, поправил

2024-02-28 16:36 UTC, alexBlack01 commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/ServerImpl.java
> +        if (Arrays.asList(METHODS).contains(request.getMethodName())) {
Хм, странно, я читал наоборот, что Arrays.asList() не аллоцирует, поэтому и выбрал такой путь

2024-02-28 17:35 UTC, incubos commented on src/main/java/ru/vk/itmo/test/tuzikovalexandr/ServerImpl.java
> +        if (Arrays.asList(METHODS).contains(request.getMethodName())) {
Как он может не аллоцировать, если принимает на вход объект массив, а возвращает другой объект типа `List`? Возможно, JIT соптимизирует, но это нужно проверять. А лучше сделать сразу очевидно эффективно.

2024-02-28 17:35 UTC, incubos commented
Нужно починить флапающий тест.

2024-02-29 08:50 UTC, merged