Тимофеев Кирилл, ИТМО DWS, Stage 2
polis-vk/2024-highload-dht pull request #60
Opened 2024-02-28 15:01 UTC by NoGe4Ek

code only

2024-03-02 17:56 UTC, atimofeyev requested changes
Не вижу отчета о профилировании многопоточного варианта

2024-03-02 17:56 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/timofeevkirill/TimofeevServer.java
> +                session.sendResponse(new Response(Response.BAD_REQUEST, Response.EMPTY));
было бы красивее сделать:
catch(HttpException e) {
} catch (Exception e) {
}

2024-03-02 17:56 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/timofeevkirill/TimofeevService.java
> +        threadPoolExecutor.close();
close не очень удачные метод, может очень долго завершаться

2024-03-03 10:08 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/TimofeevServer.java
> +                session.sendResponse(new Response(Response.BAD_REQUEST, Response.EMPTY));
Это правда, но я не просто так это сделал. Идея не осознает возможного наличия эксепшена и ругается.
![image](https://github.com/polis-vk/2024-highload-dht/assets/33723502/8da1af47-ea6f-4fc8-a182-ea0719913552)

2024-03-03 10:09 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/TimofeevServer.java
> +                session.sendResponse(new Response(Response.BAD_REQUEST, Response.EMPTY));
А так хотя бы просто ворнинг
![image](https://github.com/polis-vk/2024-highload-dht/assets/33723502/d6ac25ce-a7a7-45a6-96ce-38b4b11eb52b)

2024-03-03 10:10 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/TimofeevService.java
> +        threadPoolExecutor.close();
Поправил

2024-03-03 10:11 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/TimofeevService.java
> +        threadPoolExecutor.close();
Еще с лекции подцепил prestartAllCoreThreads

2024-03-09 21:17 UTC, atimofeyev requested changes

2024-03-09 21:17 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/timofeevkirill/results/task2/readme.md
> +### 900 thds rps
Что здесь значит 900 thds?

2024-03-09 21:17 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/timofeevkirill/results/task2/readme.md
> +Для array  - 12000
Из-за чего же такая разница? Можно ли это понять по профилю?

2024-03-10 09:53 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/TimofeevServer.java
> +                session.sendResponse(new Response(Response.BAD_REQUEST, Response.EMPTY));
Да, можно и так, правда от ворнинга все равно не избавиться
![image](https://github.com/polis-vk/2024-highload-dht/assets/33723502/bc65cfca-75e6-405b-8e0b-cbd26f9214cb)

2024-03-10 10:03 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/TimofeevService.java
> +        shutdownAndAwaitTermination(threadPoolExecutor);
Спасибо, что заметили. Случайно получилось. Потом бы где-нибудь стрельнуло.
Понимаю, что если дао закрыть первым, то запросы еще могут приходить, а состояние дао после его закрытие у нас не определено.

2024-03-10 10:18 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/TimofeevServer.java
> +                    throw new UncheckedIOException(e);
Верно, поправил

2024-03-10 10:23 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/results/task2/readme.md
> +### 900 thds rps
900 000 rps

2024-03-10 12:01 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/results/task2/readme.md
> +Для array  - 12000
После анализа выяснил следующее:
1. В array используется один лок, а в linked два, на за пись и на чтение, вероятно поэтому такая разница на lock профиле
array
![Screenshot from 2024-03-10 14-41-16](https://github.com/polis-vk/2024-highload-dht/assets/33723502/8d0b8bec-c6ab-47b0-9ff4-f6b2501f4c06)
linked
![Screenshot from 2024-03-10 14-41-20](https://github.com/polis-vk/2024-highload-dht/assets/33723502/a792b393-8108-4541-80b7-9cdfd660b528)
На selectorThread уходит меньше времени для linked

2. Методы лока для linked заинлайнены, кажется, что джит не отработал в этом месте для array. Возможно он и не сможет оптимизировать это место. Еще пару раз позапускал нагрузочное, но лучше не стало. В качестве эксперимента можно было бы попробовать ручками запустить джит с указанием степени оптимизации, Кажется, в граль vm нативном образе можно что-то такое сделать. Но не хочется таким сейчас заниматься 
array
![Screenshot from 2024-03-10 14-37-06](https://github.com/polis-vk/2024-highload-dht/assets/33723502/a2176656-409f-4b76-9bf3-ff25b814b290)
linked
![Screenshot from 2024-03-10 14-37-14](https://github.com/polis-vk/2024-highload-dht/assets/33723502/1b640475-9a13-4475-b057-9d7b1cc61098)

2024-03-10 12:08 UTC, NoGe4Ek commented on src/main/java/ru/vk/itmo/test/timofeevkirill/TimofeevServer.java
> +                session.sendResponse(new Response(Response.BAD_REQUEST, Response.EMPTY));
А нет, отмена. В таком случае код климат предлагает заменить это на отдельный catch. А это все еще выглядит как ошибка для ide. Оставил как есть

2024-03-12 20:23 UTC, atimofeyev approved these changes

2024-03-12 20:28 UTC, merged