Ходосова Елена, ИТМО DWS, Stage 2
polis-vk/2024-highload-dht pull request #61
Opened 2024-02-28 15:27 UTC by ImLena

2024-03-03 13:04 UTC, incubos requested changes
Есть замечания к реализации. Ждём исправлений, а также нагрузочного тестирования, профилирования под нагрузкой и анализа полученных результатов, а также возможных оптимизаций.

2024-03-03 13:04 UTC, incubos commented on src/main/java/ru/vk/itmo/test/elenakhodosova/HttpServerImpl.java
> +                    Thread.currentThread().interrupt();
Почему `interrupt()` в случае ошибки? Здесь остаётся только залоггировать ошибку и закрыть сессию.

2024-03-03 13:04 UTC, incubos commented on src/main/java/ru/vk/itmo/test/elenakhodosova/HttpServerImpl.java
> +                    session.sendError(Response.BAD_REQUEST, e.getMessage());
Почему именно `BAD_REQUEST`? Возможно, произошла ошибка в работе DAO или ещё что-то.

2024-03-03 13:04 UTC, incubos commented on src/main/java/ru/vk/itmo/test/elenakhodosova/HttpServerImpl.java
> +        executorService.execute(() -> {
Не обрабатывается `RejectedExecutionException`, т.е. ситуация перегрузки.

2024-03-03 13:04 UTC, incubos commented on src/main/java/ru/vk/itmo/test/elenakhodosova/ServiceImpl.java
> +        executorService.shutdownNow();
Почему сразу `shutdownNow()`? Для чего прерывать запросы в обработке? Можно сделать более graceful?

2024-03-03 13:04 UTC, incubos commented on src/main/java/ru/vk/itmo/test/elenakhodosova/ServiceImpl.java
> +        executorService.shutdownNow();
Почему executor останавливается до останова сервера? Так мы можем продолжать принимать запросы, но их некому обрабатывать.
В `start()` другой порядок, здесь должен быть ровно обратный.

2024-03-10 16:48 UTC, incubos requested changes
Есть ряд вопросов. Ждём комментариев.

2024-03-10 16:48 UTC, incubos commented on src/main/java/ru/vk/itmo/test/elenakhodosova/reports/Stage2.md
> +Как видно из графа, суммарно около 30% времени уходит на работу с потоками
Про какие методы идёт речь?

2024-03-10 16:48 UTC, incubos commented on src/main/java/ru/vk/itmo/test/elenakhodosova/reports/Stage2.md
> +Получаем, что при 64 потоках сервер справляется лучше всего и точка разладки примерно на 153000 RPS.
Выше у нас уже секундные времена ответов и мы выдержали лишь 149К из 153K rps, верно?

2024-03-10 16:48 UTC, incubos commented on src/main/java/ru/vk/itmo/test/elenakhodosova/reports/Stage2.md
> +Около 51% уходит на poll(), около 20% суммарно уходит на работу с потоками (старт,
Не "старт" потока, а выполнение задачи из очереди, видимо?

2024-03-10 16:48 UTC, incubos commented on src/main/java/ru/vk/itmo/test/elenakhodosova/reports/Stage2.md
> +Получается, что в синхронной версии ниже средняя latency, но максимальное время обработки растет почти до 200ms.
Чем можно объяснить повышенные значения высоких перцентилей?

2024-03-10 16:48 UTC, incubos commented on src/main/java/ru/vk/itmo/test/elenakhodosova/reports/Stage2.md
> +По результатам профилирования видно, что время, уходящее на poll() cелектора в асинхронной версии сократилось с на 20%
На профилях (кроме lock) не время, а сэмплы -- интерпретация не совсем верная. Теперь помимо селекторов появились другие потоки, которые выполняются на CPU -- мы видим их сэмплы, а сэмплов селекторов стало пропорционально меньше.

2024-03-10 16:48 UTC, incubos commented on src/main/java/ru/vk/itmo/test/elenakhodosova/reports/Stage2.md
> +  Non-2xx or 3xx responses: 1231930
Вы не по пустой БД стреляли? Не могут все эти ответы быть 404? Распределение latency выглядит вполне достойно.

2024-03-10 16:48 UTC, incubos commented on src/main/java/ru/vk/itmo/test/elenakhodosova/reports/Stage2.md
> +что селекторы закрывают соединение, видимо, не справляясь с нагрузкой. Для сравнения увеличим количество соединений
Можете, пожалуйста, указать на код, где селекторы закрывают соединение, когда не справляются с нагрузкой?

2024-03-10 16:48 UTC, incubos commented on src/main/java/ru/vk/itmo/test/elenakhodosova/reports/Stage2.md
> +Как мы видим, все запросы выполняются успешно, а средняя latency немного снизилась.
Выглядит так, что на предыдущей стрельбе вы дали `wrk2` один поток и счётчик нагенерил IDшки несуществующих ключей (за границей датасета). Здесь у вас 64 потока и они все генерят повторяющиеся (по 64 раза) IDшки. Мы обсуждали это на занятии -- каждый поток wrk2 запускает свой экземпляр скрипта `get.lua`. Можете перепроверить?

2024-03-10 16:48 UTC, incubos commented on src/main/java/ru/vk/itmo/test/elenakhodosova/reports/Stage2.md
> +  Detailed Percentile spectrum:
Detailed spectrum можно не приводить в отчёте для экономии места -- Latency Distribution выше вполне достаточно для анализа.

2024-03-10 16:48 UTC, incubos commented on src/main/java/ru/vk/itmo/test/elenakhodosova/reports/Stage2.md
> +ожидание блокировок) - аналогично с PUT запрросом средняя latency выросла по сравнению с синхронной версией из 1 этапа (с 0,631ms до 1.30ms).
Чем можно объяснить рост средней latency?

2024-03-10 16:48 UTC, incubos commented on src/main/java/ru/vk/itmo/test/elenakhodosova/reports/Stage2.md
> +[CPU flame graph](data/stage2/profile-get-130000.html)
Судя по профилю, у вас сэмплов с `MemTable.get()` больше, чем `SSTable.get()` -- БД была пустой или на диске всего несколько файлов? Нужно нагружать предзаполненную БД.

2024-03-10 16:48 UTC, incubos commented on src/main/java/ru/vk/itmo/test/elenakhodosova/reports/Stage2.md
> +Видимо, сыграло роль время, которое тратится на выделение новых потоков и удержание блокировок в очереди. Также выделение новых потоков
В нашем случае потоки в пуле запускаются единожды и пул держится прогретым -- что вы имели в виду под "выделением новых потоков"? У вас же на руках flamegraph и код JDK -- все исходные данные.

2024-03-10 16:48 UTC, incubos commented on src/main/java/ru/vk/itmo/test/elenakhodosova/reports/Stage2.md
> +приводит к дополнительным аллокациям. Оптимизировать это можно используя разные размеры или реализации очередей. Например, при
Можете сослаться на конкретный метод, где возникают дополнительные аллокации?

2024-03-10 16:48 UTC, incubos commented on src/main/java/ru/vk/itmo/test/elenakhodosova/reports/Stage2.md
> +больше времени уходит на аллокации новых потоков.
Можете указать на метод в коде, где это происходит? Или что вы имеете в виду?

2024-03-11 18:31 UTC, ImLena commented on src/main/java/ru/vk/itmo/test/elenakhodosova/reports/Stage2.md
> +Как видно из графа, суммарно около 30% времени уходит на работу с потоками
Park и unpark, они вызываются в ArrayBlockingQueue (take и offer)

2024-03-11 18:34 UTC, ImLena commented on src/main/java/ru/vk/itmo/test/elenakhodosova/reports/Stage2.md
> +Получаем, что при 64 потоках сервер справляется лучше всего и точка разладки примерно на 153000 RPS.
Когда я профилировала, при 151К rps ответы были менее секунды, поэтому в отчет решила вставить 153К, когда сервер уже точно не справляется. Но в приведенном примере да, прошло всего 149К, так что наверное логичнее было бы взять за точку разладки ~150K rps

2024-03-15 07:01 UTC, ImLena commented on src/main/java/ru/vk/itmo/test/elenakhodosova/reports/Stage2.md
> +ожидание блокировок) - аналогично с PUT запрросом средняя latency выросла по сравнению с синхронной версией из 1 этапа (с 0,631ms до 1.30ms).
Мне кажется, что влияют накладные расходы, связанные с работой потоков, в том числе ожидание блокировок

2024-03-15 07:12 UTC, ImLena commented on src/main/java/ru/vk/itmo/test/elenakhodosova/reports/Stage2.md
> +больше времени уходит на аллокации новых потоков.
Логика была в том, что заранее не выделена память под пул потоков, поэтому должны быть аллокации в процессе работы программы. Но так как сервер был уже прогретый, они не могут влиять и на флейм графе этого не видно. Получается, что рост latency скорее связан с более долгим ужержанием блокировок, возможно еще повлияли какие-то фоновые процессы браузера, открытого параллельно

2024-03-15 07:14 UTC, ImLena commented on src/main/java/ru/vk/itmo/test/elenakhodosova/reports/Stage2.md
> +приводит к дополнительным аллокациям. Оптимизировать это можно используя разные размеры или реализации очередей. Например, при
Так как сервер прогрет, на флейм графе этого не видно, поэтому мое предположение про дополнительные аллокации все-таки неверно

2024-03-15 17:37 UTC, ImLena commented
Исправила замечания в коде и перемерила запросы, которые обращались к незаполненной бд

2024-03-15 17:39 UTC, ImLena commented on src/main/java/ru/vk/itmo/test/elenakhodosova/reports/Stage2.md
> +  Non-2xx or 3xx responses: 1231930
Действительно, не заметила. Здесь и ниже исправила в отчете

2024-03-17 13:19 UTC, incubos approved these changes
15 баллов.

2024-03-17 13:19 UTC, incubos commented on src/main/java/ru/vk/itmo/test/elenakhodosova/reports/Stage2.md
> +почти 19% сэмплов на обращения к sstable, это вероятнее всего запросы, из-за которых выросли 99.9+ перцентили
Профилировщик сэмплирует с фиксированным интервалом. 0.1% запросов на flamegraph мы вряд ли увидим и они не займут 40% сэмплов CPU.

2024-03-17 13:20 UTC, merged