Аленькова Юлия ИТМО DWS Stage2
polis-vk/2024-highload-dht pull request #74
Opened 2024-02-28 22:44 UTC by yulalenk

2024-03-02 17:42 UTC, atimofeyev requested changes
Не вижу отчета о профилировании многопоточного варианта

2024-03-02 17:42 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/alenkovayulya/ExecutorServiceConfig.java
> +        return (value == 0 || value > maxPossibleValue) ? maxPossibleValue : value;
лучше кинуть ошибку если значение выходит за границ

2024-03-02 17:42 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/alenkovayulya/ExecutorServiceFactory.java
> +                    case ARRAY -> new ArrayBlockingQueue<>(config.queueSize);
этот тип - лишняя абстракция, которая только запутывает, лучше сразу в параметрах создать ту очередь которую надо. В месте создания экзекутера будет сразу видно что за очередь используетется.

2024-03-02 17:42 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/alenkovayulya/ServerImpl.java
> +                    Thread.currentThread().interrupt();
а зачем тут ставится флажок interrupt?

2024-03-02 17:42 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/alenkovayulya/ServiceImpl.java
> +        referenceDao = new ReferenceDao(new Config(config.workingDir(), 1024 * 1024 * 1024));
большая таблица получается, а более маленькую тестировали?

2024-03-02 17:42 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/alenkovayulya/ServiceImpl.java
> +        executorService.shutdownNow();
лучше сначала вызывать executorService.shutdown(); чтобы все ткущие таски закончили свое выполнение

2024-03-06 14:55 UTC, yulalenk commented on src/main/java/ru/vk/itmo/test/alenkovayulya/ServerImpl.java
> +                    Thread.currentThread().interrupt();
Согласна, здесь он не нужен, достаточно просто залогировать ошибку и закрыть сессию

2024-03-06 23:10 UTC, yulalenk commented on src/main/java/ru/vk/itmo/test/alenkovayulya/ServiceImpl.java
> +        referenceDao = new ReferenceDao(new Config(config.workingDir(), 1024 * 1024 * 1024));
Так как на первом этапе тестирование происходило с этим размером таблицы, на этом тоже решила не менять

2024-03-09 17:16 UTC, atimofeyev approved these changes

2024-03-09 17:17 UTC, atimofeyev commented
Поправьте конфликты пожалуйста

2024-03-10 20:55 UTC, atimofeyev requested changes
Поправьте конфликты пожалуйста

2024-03-10 21:12 UTC, yulalenk commented on src/main/java/ru/vk/itmo/test/alenkovayulya/report/report_stage2.md
> +При постепенном увеличении размера пула задержка 99 персентиля незначительно увеличивалась, для дальнейшего тестирования было выбрано значение в 32 потока.
Подбирала параметры пулов, запуская wrk c 64 коннекшенами, это отражено в файле wrk_get_pool_size.txt

2024-03-10 21:12 UTC, yulalenk commented
> Поправьте конфликты пожалуйста

Done

2024-03-12 20:07 UTC, atimofeyev approved these changes

2024-03-12 20:08 UTC, merged