Супрядкина Дарья ИТМО DWS stage 2
polis-vk/2024-highload-dht pull request #75
Opened 2024-02-28 23:00 UTC by SuDarina

Отчет в процессе написания

2024-03-03 13:06 UTC, incubos requested changes
Необходимо зарезолвить конфликты.

2024-03-03 13:19 UTC, incubos requested changes
Есть ряд вопросов и замечаний к реализации. Ждём исправлений, нагрузочного тестирования, профилирования, анализа результатов и возможных оптимизаций.

2024-03-03 13:19 UTC, incubos commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/workers/WorkerConfig.java
> +    public static final TimeUnit UNIT = TimeUnit.SECONDS;
Обычно просто называют `KEEP_ALIVE_TIME_SECONDS`.

2024-03-03 13:19 UTC, incubos commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/workers/WorkerThreadPoolExecutor.java
> +    private static final Logger logger = LoggerFactory.getLogger(Server.class.getName());
Не тот класс:
```suggestion
    private static final Logger logger = LoggerFactory.getLogger(WorkerThreadPoolExecutor.class);
```

2024-03-03 13:19 UTC, incubos commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/workers/WorkerThreadPoolExecutor.java
> +                WorkerConfig.KEEP_ALIVE_TIME, WorkerConfig.UNIT, workerConfig.getWorkQueue());
Не хватает кастомной `ThreadFactory`, которая даст потокам говорящие имена и упростит анализ профилей.

2024-03-03 13:19 UTC, incubos commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/Server.java
> +        executorService.execute(() -> {
Не обрабатывается возможный `RejectedExecutionException` в случае перегрузки сервиса.

2024-03-03 13:19 UTC, incubos commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/Server.java
> +                    logger.error("Handling request failed");
Скорее, мы не смогли отправить ответ об ошибке, верно?
Стоит закрыть сессию в такой ситуации.

2024-03-03 13:19 UTC, incubos commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/Server.java
> +            } catch (Exception e) {
Не помешает залоггировать это исключение.

2024-03-05 21:10 UTC, SuDarina commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/Server.java
> +            } catch (Exception e) {
исправлено

2024-03-05 21:11 UTC, SuDarina commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/Server.java
> +                    logger.error("Handling request failed");
исправлено

2024-03-05 21:11 UTC, SuDarina commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/Server.java
> +        executorService.execute(() -> {
исправлено

2024-03-05 21:11 UTC, SuDarina commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/workers/WorkerThreadPoolExecutor.java
> +                WorkerConfig.KEEP_ALIVE_TIME, WorkerConfig.UNIT, workerConfig.getWorkQueue());
исправлено

2024-03-05 21:11 UTC, SuDarina commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/workers/WorkerThreadPoolExecutor.java
> +    private static final Logger logger = LoggerFactory.getLogger(Server.class.getName());
исправлено

2024-03-05 21:11 UTC, SuDarina commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/workers/WorkerConfig.java
> +    public static final TimeUnit UNIT = TimeUnit.SECONDS;
исправлено

2024-03-10 17:25 UTC, incubos requested changes
Есть несколько вопросов. Ждём комментариев.

2024-03-10 17:25 UTC, incubos commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/report/hw2/REPORT.md
> +Точка разладки с 12000 резко упала до ≈4800...
Чем это можно объяснить на рандомных ключах?

2024-03-10 17:25 UTC, incubos commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/report/hw2/REPORT.md
> +#### FanFact
```suggestion
#### FunFact
```

2024-03-10 17:25 UTC, incubos commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/report/hw2/REPORT.md
> +При попытке запустить upsert на ресурсах wrk равных: -t 64 -c 64 лично у меня ни одна таблица не сфлашилась :(
Есть идеи, почему так?

2024-03-12 12:19 UTC, SuDarina commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/report/hw2/REPORT.md
> +При попытке запустить upsert на ресурсах wrk равных: -t 64 -c 64 лично у меня ни одна таблица не сфлашилась :(
Добавила свои предположения в отчет

2024-03-12 12:19 UTC, SuDarina commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/report/hw2/REPORT.md
> +#### FanFact
fix

2024-03-12 12:20 UTC, SuDarina commented on src/main/java/ru/vk/itmo/test/dariasupriadkina/report/hw2/REPORT.md
> +Точка разладки с 12000 резко упала до ≈4800...
Когда мы последовательно заполняем таблице (последовательными ключами), затем читаем также последовательно, то ввиду реализации Dao бинарный поиск осуществляется последовательно по sstable’ам.
Сначала все будет искаться в 1-ом, затем в 2-х, 3-х, …, n (в случае, если мы начинаем не сначала, а с конца таблицы таблицы).
Если же мы случайным образом ищем в среднем мы будем делать n/2 бин-поисков, где n - количество таблиц

2024-03-17 13:23 UTC, incubos approved these changes
15 баллов.

2024-03-17 13:23 UTC, merged