Stage 2, Андрей Чешев, Политех
polis-vk/2024-highload-dht pull request #76
Opened 2024-02-28 23:36 UTC by Queenore

2024-02-28 23:39 UTC, Queenore commented
![Отчет (недописан)](https://github.com/Queenore/2024-highload-dht/blob/stage-2-Cheshev/src/main/java/ru/vk/itmo/test/andreycheshev/lab2/report-2-Cheshev.md)

2024-03-01 11:56 UTC, Queenore commented
Обнаружена вероятная проблема, по которой решение работало не столь эффективно при тестировании, а именно большое максимальное количество потоков (x10 core потоков).

2024-03-02 18:17 UTC, Marashov-Alexander reviewed
Понравилось, что реализация красиво и эффективно разделена на классы. По коду незначительные замечания, а главную проблему вы заметили сами. Жду исправлений до жёсткого дедлайна, результатов профилирования и нагрузочного тестирования. Успехов!

2024-03-02 18:17 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/RequestHandler.java
> +    private static final String ID = "id=";
я бы ещё расширил название для лучшего понимания: ID_PARAMETER или как-то так

2024-03-02 18:17 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/RequestHandler.java
> +    private MemorySegment fromString(String data) {
может быть статическим?

2024-03-02 18:17 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/RequestHandler.java
> +        return (entry == null)
скобочки кажутся лишними

2024-03-02 18:17 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/RequestHandler.java
> +import static one.nio.http.Response.METHOD_NOT_ALLOWED;
и статический импорт произведен, и в некоторых местах обращение по классу используется. Лучше привести к одному виду, мб лучше не в пользу статических импортов

2024-03-02 18:17 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/ServerStarter.java
> +    private static final int THRESHOLD_BYTES = 100000;
"100к байт - а это сколько кб? А мб? А гб?"
Такими вопросами будет задаваться любой, кто прочитает код) Лучше явно показать происхождение константы в виде 1024 * 1024 * 8 для 8 мб, например

2024-03-02 18:17 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/ServerStarter.java
> +        ServerImpl server = new ServerImpl(serverConfig, daoConfig);
мб заиспользовать разработанный сервис? Тогда не потребуется заново константы объявлять и конфиги

2024-03-02 18:17 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/lab2/report-2-Cheshev.md
> +	*  -R 2550 ![](c1-t1-2550-get-cmp.png) Видно, что новая реализация значительно уступает (rps = 2550 является точкой разладки).
если rps=2550 является точкой разладки, то для чего проводятся последующие увеличения нагрузки? 
Кстати, судя по результатам ниже, это не являяется точкой разладки

2024-03-06 20:56 UTC, Queenore commented
[Отчет](https://github.com/Queenore/2024-highload-dht/blob/stage-2-Cheshev/src/main/java/ru/vk/itmo/test/andreycheshev/lab2/report-2-Cheshev.md)

2024-03-10 18:48 UTC, Marashov-Alexander requested changes
Здорово, что у вас в отчёте проведено исследование влияния множества параметров. Чувствуется, что проделана большая работа.

К самому отчёту есть несколько важных вопросов. В первую очередь не хватает анализа проблемы. Как я понимаю, многопоточная реализация должна быть производительнее однопоточной при большом количестве одновременных соединений, однако в данной работе это не так. Было бы круто выяснить, почему и что можно с этим сделать. 
И к некоторым утверждениям в отчёте есть вопросы) 
Готов поставить 10 из 15 с условием, что вы обнаружите проблему и пофиксите её

2024-03-10 18:48 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/lab2/report-2-Cheshev.md
> +* Treshhold bytes = 128 кБайт
Тут и далее выбирается очень низкий порог флага. Мб проблема в нём? Не пробовали его менять?

2024-03-10 18:48 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/lab2/report-2-Cheshev.md
> +## Проведем сравнение реализаций на стабильной нагрузке
Было бы круто в двух словах напоминать о результатах проведения профилирования и нагрузки с прошлого этапа. В данном кейсе было бы здорово хотя бы оставить найденную точку разладки для старой реализации

2024-03-10 18:48 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/lab2/report-2-Cheshev.md
> +    * -R 2500 ![](param-tests/c1-t1-2500-put-cmp.png) Исходя из графика, видно, что результат практически идентичен.
что означает "практически идентичен"? Как пояснение было бы круто указать, что до такого-то перцентиля

2024-03-10 18:48 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/lab2/report-2-Cheshev.md
> +    * -R 2500 ![](param-tests/c64-t1-2500-put-cmp.png)
Не хватает указания выводов при сравнении. Написано "сравним", а приведены лишь графики и нагрузка

2024-03-10 18:48 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/lab2/report-2-Cheshev.md
> +      В новой реализации точка разладки при таких параметрах ниже чем в старой реализации.
Ниже - это какая? Тоже было бы круто указать

2024-03-10 18:48 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/lab2/report-2-Cheshev.md
> +Видим, что старая реализация практически не уступает новой, а зачастую даже превосходит.
Было бы здорово конкретизировать, в каких случаях уступает: в get, в put или же в обоих кейсах

2024-03-10 18:48 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/lab2/report-2-Cheshev.md
> +### Попробуем изменить количество потоков
Хорошо бы перед началом нового абзаца предположить, в чем может быть проблема. И предложить рассмотреть такие-то параметры (в данном случае потоки)

2024-03-10 18:48 UTC, Marashov-Alexander commented on src/main/java/ru/vk/itmo/test/andreycheshev/lab2/report-2-Cheshev.md
> +Проанализировав работу системы, стало очевидно, что такое неудовлетворительное поведение наблюдаемое раньше действительно связано со слишком большим максимальным размером количества потоков. Исходя и
А сколько ядер у вас в процессоре? Эту информацию тоже было бы здорово указать.
По графику и выводу выходит, будто 2) Хотя далее вы используете число 6. Ещё на графике не поместилась легенда для фиолетовой линии - это работа в один поток?

2024-03-10 18:57 UTC, Queenore commented
В ближайшие дни исправлю замечания.

2024-03-12 20:59 UTC, Queenore commented on src/main/java/ru/vk/itmo/test/andreycheshev/lab2/report-2-Cheshev.md
> +Проанализировав работу системы, стало очевидно, что такое неудовлетворительное поведение наблюдаемое раньше действительно связано со слишком большим максимальным размером количества потоков. Исходя и
У меня 8 ядер физических, для виртуальной машины, на которой тестируется сервер, выделены 6. Фиолетования линия как раз соответствует 6и потокам.

2024-03-16 19:10 UTC, Queenore commented
Внес правки.

2024-03-24 19:17 UTC, Marashov-Alexander approved these changes

2024-03-24 19:17 UTC, merged