Пелогейко Макар, ИТМО DWS, Stage 2
polis-vk/2024-highload-dht pull request #77
Opened 2024-02-29 01:26 UTC by makar-pelogeiko

# Stage 2

 - [x] working prototype
 - [ ] tuned prototype
 - [ ] load tests

2024-03-03 14:35 UTC, incubos requested changes
Есть ряд вопросов и замечаний к реализации. Ждём исправления, а также нагрузочное тестирование, профилирование, анализ результатов и возможные оптимизации.

2024-03-03 14:35 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/ExecutorServiceFactory.java
> +    private static final long KEEP_ALIVE_TIME = 2;
В чём измеряется?

2024-03-03 14:35 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/ExecutorServiceFactory.java
> +    public static ExecutorService getExecutorService() {
```suggestion
    public static ExecutorService newExecutorService() {
```

2024-03-03 14:35 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/ExecutorServiceFactory.java
> +    private static final int CAPACITY = 2048;
```suggestion
    private static final int QUEUE_CAPACITY = 2048;
```

2024-03-03 14:35 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/ExecutorServiceFactory.java
> +            return new Thread(r, "ExecutorServiceThread");
У всех тредов будет одно и то же имя. Обычно добавляют счётчик.

2024-03-03 14:35 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/ExecutorServiceFactory.java
> +    public static final class MyThreadFactory implements ThreadFactory {
Это явно singleton.

2024-03-03 14:35 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/ExecutorServiceFactory.java
> +        return new ThreadPoolExecutor(CORE_POOL_SIZE, MAXIMUM_POOL_SIZE, KEEP_ALIVE_TIME, UNIT, QUEUE,
Почему мы все экземплярам TPE передаём общую очередь?

2024-03-03 14:35 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/ServiceImpl.java
> +        daoConfig = new Config(config.workingDir(), 2048L);
Почему такой маленький порог для flush? Это приведёт к большому количеству крошечных файлов.

2024-03-03 14:35 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/DaoHttpServer.java
> +    private ReferenceDaoPel dao;
Почему конкретный класс, а не интерфейс?

2024-03-03 14:35 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/DaoHttpServer.java
> +            dao = new ReferenceDaoPel(daoConfig);
Будет гибче конструировать снаружи и передавать DAO в конструктор -- это позволит абстрагироваться от реализации DAO.

2024-03-03 14:35 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/DaoHttpServer.java
> +    public Response upsertDaoMethod(@Param(value = "id", required = false) String id, Request request) {
Почему `required = false`?

2024-03-03 14:35 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/DaoHttpServer.java
> +            log.error("Exception during upsert: ", e);
Не по формату:
```suggestion
            log.error("Exception during upsert", e);
```

2024-03-03 14:35 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/DaoHttpServer.java
> +        } catch (IllegalStateException e) {
Почему именно ISE, а не просто `Exception`?

2024-03-03 14:35 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/DaoHttpServer.java
> +        } catch (IllegalStateException e) {
Зачем ловить здесь, а не в одном месте для всех запросов?

2024-03-03 14:35 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/DaoHttpServer.java
> +            log.error("Exception during upsert: ", e);
И во всех остальных вызовах логгирования.

2024-03-03 14:35 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/DaoHttpServer.java
> +                        log.error("IOException while sendResponse ExecServer: ", ex);
Стоит закрыть сессию при ошибке отправки ответа.

2024-03-03 14:35 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/DaoHttpServer.java
> +            dao.close();
И деинициализировать тоже стоит снаружи.

2024-03-03 14:35 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/ServiceImpl.java
> +        server.stop();
Забыли остановить `ExecutorService`. Тем более, что там потоки не демоны.

2024-03-06 15:58 UTC, makar-pelogeiko commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/ExecutorServiceFactory.java
> +    private static final long KEEP_ALIVE_TIME = 2;
Секунды

2024-03-06 15:59 UTC, makar-pelogeiko commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/ExecutorServiceFactory.java
> +        return new ThreadPoolExecutor(CORE_POOL_SIZE, MAXIMUM_POOL_SIZE, KEEP_ALIVE_TIME, UNIT, QUEUE,
Ошибка, исправил

2024-03-06 16:01 UTC, makar-pelogeiko commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/DaoHttpServer.java
> +    private ReferenceDaoPel dao;
Исправил, тут должен быть интерфейс

2024-03-06 16:01 UTC, makar-pelogeiko commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/DaoHttpServer.java
> +            dao = new ReferenceDaoPel(daoConfig);
Исправил

2024-03-06 16:02 UTC, makar-pelogeiko commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/DaoHttpServer.java
> +        } catch (IllegalStateException e) {
Это для обработки ситуации, когда мы не можем больше вставлять данные из-за того, что flush еще идет

2024-03-06 16:05 UTC, makar-pelogeiko commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/DaoHttpServer.java
> +            dao.close();
Логично

2024-03-09 22:45 UTC, makar-pelogeiko commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/DaoHttpServer.java
> +    public Response upsertDaoMethod(@Param(value = "id", required = false) String id, Request request) {
В ситуации, когда отправляется запрос по верному пути, но с пустым параметром (тест `absentParameterRequest`). При попытке получить параметр запроса вылетает исключение в `handleRequest`, если `required = true`

2024-03-10 17:27 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/ExecutorServiceFactory.java
> +    private static final long KEEP_ALIVE_TIME = 2;
Нужно отразить в названии константы.

2024-03-10 18:33 UTC, incubos requested changes
Есть ряд вопросов. Ждём комментариев.

2024-03-10 18:33 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +оставшаяся часть у Executor'а SelectorThread'ов
Какого "Executor'а SelectorThread'ов"? У них же его нет.

2024-03-10 18:33 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +- Примерно 28% процессорного времени `sendResponse` обработка запроса
А точнее, запись в сокет, верно?

2024-03-10 18:33 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +(около 20% для `PUT` и до 90% для `GET`) - это происходит из-за с особенности хранилища
Каких именно "особенностей хранилища"? Хочется большей конкретики.

2024-03-10 18:33 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +- Около 31% аллокаций занимает вставка, 3.5% аллокаций очередь и оставшаяся часть в основном занимается
Можете пояснить про аллокации очереди? Какой именно метод вы имели в виду?

2024-03-10 18:33 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +- Около 31% аллокаций занимает вставка, 3.5% аллокаций очередь и оставшаяся часть в основном занимается
Где именно выделяются объекты при вставке? У нас вся текущая нагрузка это PUTы, поэтому другого источника и не может быть. Хочется больше конкретики, чтобы понять, что можно попытаться оптимизировать.

2024-03-10 18:33 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +При connections = 64 и RPS = 21 000 получился следующий результат Requests/sec:  19945.77
Не совсем понимаю -- т.е. 21K rps мы не вытянули, а смогли лишь 20K rps?

2024-03-10 18:33 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +(примерно `queue_size` ≈ `connections` - `pool_size`).
Это предположение или есть подтверждение?

2024-03-10 18:33 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +При изменении количества потоков от 1 до 7 особых изменений замечено не было
Не нашёл закоммиченых результатов.

2024-03-10 18:33 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +и фактическое количетво запросов в сек (Requests/sec) увеличилось до 20687.92.
Т.е. 21K rps всё равно не держим? Мы же обсуждали, что нагружать нужно ниже точки разладки.

2024-03-10 18:33 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +Это связано с тем, что изначальный скрипт строит запросы, начиная с самых "дальних" данных, что приводит
Что значит "дальних данных"?

2024-03-10 18:33 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +  Non-2xx or 3xx responses: 691518
Больше половины запросов это не 200 OK -- почему?

2024-03-10 18:33 UTC, incubos commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +- Как видно из CPU Flame graph большая часть процессорного времени (~72%) расходуется на `mismatch`, что подтверждает
У вас же Mac OS? Если да, то мы не видим стеки ядра. `mismatch()` работает поверх mmap-сегментов и если данные не влезают в page cache, мы бы увидели их подкачку, которая по своей сути IO, а не CPU.

2024-03-12 01:23 UTC, makar-pelogeiko commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +оставшаяся часть у Executor'а SelectorThread'ов
Я не так выразился:
- блокировки `ExecutorService` заняли ~77% и были в `arrayBlockingQueue.take`, которые в свою очередь делятся:
  - ~35% на `await` - по идее тут мы ожидали, когда придет задача (в visualVM было видно, что потоки потоки `ExecutorService`'а много простаивают (писал об этом ниже, где речь идет про изменение количества подключений))
  - ~42% на `acquire`
- В SelectorThread большую часть блокировок (~22.5%) заняли `arrayBlockingQueue.offer` - (собственно это в `DaoHttpServer.handleRequest` передача задачи в `ExecutorService`)

То есть 77 + 22.5 = 99.5% блокировок это блокировки `arrayBlockingQueue`

2024-03-12 01:27 UTC, makar-pelogeiko commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +Cначала был увеличен порог для flush до 16Kb. и был получен следующий результат при
В следующем этапе еще увеличу. Я шел с шагом ~4Кб (с шагом размера страницы виртуальной памяти) и на ~16Кб перестали появлятся ошибки `"Can't keep up with flushing!"`. Идея сделать страницы большего размера звучит логично

2024-03-12 01:28 UTC, makar-pelogeiko commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +- Примерно 28% процессорного времени `sendResponse` обработка запроса
Да

2024-03-12 01:28 UTC, makar-pelogeiko commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +(около 20% для `PUT` и до 90% для `GET`) - это происходит из-за с особенности хранилища
Используется LSM дерево. Вставка происходит быстрее, чем получение данных. Для получения данных в худшем случае надо пройтись по всем `SSTable'ам` бинарным поиском и провести много сравнений (`mismatch`). А для вставки используется только текущий `SSTable` в памяти (который и по размеру будет ~меньше, чем `SSTable` на диске)

2024-03-12 01:28 UTC, makar-pelogeiko commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +- Около 31% аллокаций занимает вставка, 3.5% аллокаций очередь и оставшаяся часть в основном занимается
метод: `ArrayBlockingQueue.take`. Судя по графу и коду, смею предположить, что аллокация кроется в `ReentrantLock`, а точенее в `Condition` и методе `await` где по итогу есть `return new ConditionNode();` в `AbstractQueuedSynchronizer.java`

2024-03-12 01:28 UTC, makar-pelogeiko commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +- Около 31% аллокаций занимает вставка, 3.5% аллокаций очередь и оставшаяся часть в основном занимается
При вставке выделяются объекты при создании `Response` (~8.8%), при преобразовании запроса в `MemorySegment` (~17.2%), при выполнении `upsert` в `ConcurrentSkipListMap` (3.5%)

2024-03-12 01:28 UTC, makar-pelogeiko commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +При connections = 64 и RPS = 21 000 получился следующий результат Requests/sec:  19945.77
Да. Собственно увеличилось фактическое количество запросов в секунду и при этом уменьшилась задержка (latency). Так же рост latency по перцентилям стал более плавный. Я еще с visualVM смотрел на потоки с разным количеством подключений. Потоки `ExecutorService`'а много времени простаивали при малом количетсве подключений, что натолкнуло меня на мысль увеличить количество подключений.

2024-03-12 01:28 UTC, makar-pelogeiko commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +(примерно `queue_size` ≈ `connections` - `pool_size`).
Я эксперементировал с разным количеством потоков в `ExecutorService`  и разным количетсвом подключений. Каждый раз получался такой вывод `queue_size` ≈ `connections` - `pool_size`. На занятии что-то подобное было, я просто хотел убедиться, что оно действительно так работает.

2024-03-12 01:28 UTC, makar-pelogeiko commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +При изменении количества потоков от 1 до 7 особых изменений замечено не было
Не стал добавлять эти результаты, чтоб не раздувать размер pull request'а (в данном случае речь идет о потоках `wrk2`).

2024-03-12 01:28 UTC, makar-pelogeiko commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +и фактическое количетво запросов в сек (Requests/sec) увеличилось до 20687.92.
Да я 07.03.2024 перед занятием спрашивал об этом, но дедлайн уже наступил, поэтому я не стал менять отчет. К тому же для профилирования с `asprof` было 18K rps — меньше, чем 20K.

2024-03-12 01:28 UTC, makar-pelogeiko commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +Это связано с тем, что изначальный скрипт строит запросы, начиная с самых "дальних" данных, что приводит
Имееются в виду данные, которые были фактически добавлены в самом начале работы сервера. То есть они находятся в самом старом `SSTable` и для получения этих данных требуется пройтись по всем более свежим `SSTable`'ам, что близко к  full scan. А после того, как были получены все данные, счетчик продолжает увеличиваться, что приводит к full scan и ошибке `404 Not Found`

2024-03-12 01:28 UTC, makar-pelogeiko commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +  Non-2xx or 3xx responses: 691518
Как описано в ответе к предыдущему комментарию: после того, как были получены все данные, счетчик продолжает увеличиваться, что приводит к full scan и ошибке `404 Not Found`. Получается, что данных было меньше. В процессе тестирования во всех случаях в базе было `~385 000` записей.

2024-03-12 01:28 UTC, makar-pelogeiko commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +- Как видно из CPU Flame graph большая часть процессорного времени (~72%) расходуется на `mismatch`, что подтверждает
Нет, у меня Linux Mint 21. Предположу, что надо сильно больше данных, чтобы было больше  IO операций.

2024-03-12 01:37 UTC, makar-pelogeiko commented on src/main/java/ru/vk/itmo/test/pelogeikomakar/load_tests/stage_2/stage2.md
> +- Около 31% аллокаций занимает вставка, 3.5% аллокаций очередь и оставшаяся часть в основном занимается
Преобразованиее запроса в `MemorySegment` делится на
- `BaseEntry` (~2.11%)
- `MemorySement.ofArray` (~6.05%) - преобразование тела из `byte[]`
-  `MemorySement.ofArray` + `String.getBytes` (~%9.09) - преобразование ключа в `byte[]`, а потом в MemorySegment, по идее промежуточное преобразование из `byte[]` в `String` можно попробовать убрать

2024-03-17 13:32 UTC, incubos requested changes
Нужно зарезолвить конфликты перед merge.

2024-03-24 15:41 UTC, incubos commented
15 баллов.

2024-03-24 15:41 UTC, merged