Коротких Виктор / ИТМО DWS / Stage 2
polis-vk/2024-highload-dht pull request #80
Opened 2024-02-29 11:58 UTC by vitekkor

- [x] Прототип - ThreadPoolExecutor + ArrayBlockingQueue
- [ ] Сравнение реализаций (ThreadPoolExecutor + LinkedBlockingQueue, VirtualThreads)
- [ ] Отчёт - link (TODO)

2024-03-02 17:19 UTC, atimofeyev requested changes
Отчет я так понимаю еще не успели написать по поводу 2 этапа?
А почему не пробовали запускать wrk в несколько потоков?

2024-03-02 17:19 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/LSMServiceImpl.java
> +                0L,
почему выбрали именно 0 для keepalive?

2024-03-02 21:07 UTC, vitekkor commented
> Отчет я так понимаю еще не успели написать по поводу 2 этапа?

Да, отчёт будет позже, возможно я еще проведу другие эксперименты

> А почему не пробовали запускать wrk в несколько потоков?

Побоялся пробовать - что-то неизвестное и было опасение, что wrk будет аффектить lsm, так как машина то одна. Но в целом на это было интересно посмотреть, так что проведу эксперимент

2024-03-02 22:35 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/LSMServiceImpl.java
> +                0L,
Максимальное количество тредов равно начальному количеству -> пул динамически не растёт. Сделано было из тех соображений, что выделение нового потока весьма трудозатратная операция. А если ещё учитывать то, что ThreadPoolExecutor выделит доп поток только в случае полного заполнения очереди (что уже свидетельствует о том, что сервису поплохело или на него прилегла бОльшая нагрузка), то дополнительные затраты на выделение нового потока сделают только хуже с точки зрения latency. Помимо этого, Вадим на крайней лекции говорил, что нам могут быть и недоступны новые запрашиваемые потоки (система не разрешит выделить).

Так как пул динамически не растёт, то параметр keepAlive ни на что не влияет (allowCoreThreadTimeOut(true) я не выставлял, а по умолчанию там false).

Поэтому для keepAlive было выбрано значение 0.

2024-03-09 17:12 UTC, atimofeyev requested changes

2024-03-09 17:12 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/reports/stage2/report.md
> +и мы ключ не находим, то увеличение количества потоков не помогает. Возможно нужно ставить ещё больше, например 1024.
пробовали? почему может быть профит от 1024?

2024-03-09 17:16 UTC, atimofeyev approved these changes

2024-03-09 17:27 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/reports/stage2/report.md
> +ArrayBlockingQueue почему-то не блокируется на сессии, что странно. При повторных попытках снять профиль ситуация была
На очереди локи были и у LinkedBlockingQueue, но там ещё были и локи на synchronized методах у LSMCustomSession (sendResponse). Я ожидал, что при использовании ArrayBlockingQueue они тоже будут, так как по всей логике вещей они не могли куда-то пропасть.

2024-03-09 19:16 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/reports/stage2/report.md
> +и мы ключ не находим, то увеличение количества потоков не помогает. Возможно нужно ставить ещё больше, например 1024.
Нет, не пробовал, но предположение такое было, потому что больший параллелизм => меньше запросов в очереди простаивает, хотя время выполнения одного запроса в чистом виде такое же.

Наверное, тут бы лучше помогло распараллеливание на уровне обхода sstable - чтобы поиск в каждом отдельном файле выполнялся параллельно. Думаю пропускная способность nvme ssd позволит это сделать. Но гораздо проще фильтр блума реализовать для каждого sstable и просто игнорировать те файлы, в которых гарантированно нет ключа.

2024-03-10 20:14 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/reports/stage2/report.md
> +В целом всё как обычно - много времени на mistmatch, так как по всем таблицам делаем бинарный поиск.
но судя по профилю бОльшую часть то мы не на мистмаче тратим, а на чем-то другом в методе getEntryOffset(), на чем же?

2024-03-10 20:39 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/reports/stage2/comparison of implementations.md
> +У виртуальных потоков большую часть времени занимает ожидание задачи. Вероятно это связано с устройством ForkJoinPool,
Не достаточный анализ проблем Virtual Thread, вероятно просто готовились неправильно.
Особенно интересно почему они хуже работают просто в однопоточном режиме по сути, из отчета не понятно совсем

2024-03-10 20:43 UTC, merged

2024-03-10 21:06 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/reports/stage2/comparison of implementations.md
> +У виртуальных потоков большую часть времени занимает ожидание задачи. Вероятно это связано с устройством ForkJoinPool,
Ещё раз обратился к JEP - там пишут, что виртуальные потоки не всегда открепляются от своих носителей, что пагубно сказывается на масштабируемости. Такие ситуации могут возникнуть при выполнении кода внутри synchronized метода (отправка ответа клиенту как раз) или при выполнении нативного кода или вызове foreign функции. Также блокирующие операции с файловой системой. При этом дополнительное количество потоков планировщик выделять не будет.

При PUT запросах у нас как таковых операций над файловой системой нет (флаш в фоне в отдельном потоке идёт), то единственное, что может в данном случае влиять - synchronized методы у HttpSession. Они не долгие, но частые:

> avoid frequent and long-lived pinning by revising synchronized blocks
...
There is no need to replace synchronized blocks and methods that are used infrequently

2024-03-10 21:38 UTC, vitekkor commented on src/main/java/ru/vk/itmo/test/viktorkorotkikh/reports/stage2/report.md
> +В целом всё как обычно - много времени на mistmatch, так как по всем таблицам делаем бинарный поиск.
Да, что-то я слона то и не разглядел. Вообще очень странно, потому что там никаких тяжёлых операций, кроме мисматча и чтения с диска long'ов, нет, а эти операции на профиле видно и они занимают не 100% времени метода getEntryOffset. Но кстати схожая ситуация была и в "однопоточной" реализации в предыдущем этапе - https://github.com/vitekkor/2024-highload-dht/blob/stage-2/src/main/java/ru/vk/itmo/test/viktorkorotkikh/reports/stage1new/GET-cpu-general.png
Тут тоже видно, что mismatch это не 100% и даже не 80% от метода getEntryOffset.

Но и в референсной реализации похоже тоже кто-то крадёт драгоценный cpu time:
![Screenshot_20240311_003026](https://github.com/polis-vk/2024-highload-dht/assets/36002722/f82a9e95-5e6b-4056-a6ca-2b209b331570).

Я честно говоря не знаю, что там может быть не так. Если профилировать каждый отдельный тред, то там картина такая же:
![Screenshot_20240311_003429](https://github.com/polis-vk/2024-highload-dht/assets/36002722/581ed8be-19dd-4454-a611-d08014b69ce2)