Плясов Климентий, ИТМО DWS, stage 2
polis-vk/2024-highload-dht pull request #84
Opened 2024-02-29 14:59 UTC by Handiesto

2024-03-02 13:43 UTC, atimofeyev requested changes

2024-03-02 13:43 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/klimplyasov/PlyasovServer.java
> +        Thread.currentThread().interrupt();
а зачем поток интерраптим?

2024-03-02 13:43 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/klimplyasov/ExecutorConfig.java
> +    public static ExecutorService getExecutorService() {
название обманчиво говорит о том что мы делаем просто get() а на самом деле создаем новый, по мне так лишнее сокрытие парамтеров создания экзекутера, лучше прямо на месте ег ои создать, для читающего код всегда важно понимать какие параметры у экзекутера и приходится куда-то далеко переходить

2024-03-02 13:43 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/klimplyasov/ExecutorConfig.java
> +    private static final int MAXIMUM_POOL_SIZE = 20;
не видно никакого отчета о профилировании, какие параметры пробовали подобрать и к чему это приводило

2024-03-02 13:43 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/klimplyasov/PlyasovServer.java
> +        session.close();
лучше пользоваться по старинке shutdown() + shutdownNow() с нормальным таймаутом, этот метод может на долго зависнуть

2024-03-06 22:35 UTC, Handiesto commented on src/main/java/ru/vk/itmo/test/klimplyasov/PlyasovServer.java
> +        Thread.currentThread().interrupt();
Для корректного завершения потока после экcепшена, но возможно это необязательно.

2024-03-06 22:35 UTC, Handiesto commented on src/main/java/ru/vk/itmo/test/klimplyasov/ExecutorConfig.java
> +    private static final int MAXIMUM_POOL_SIZE = 20;
Добавил

2024-03-06 22:36 UTC, Handiesto commented on src/main/java/ru/vk/itmo/test/klimplyasov/PlyasovServer.java
> +        session.close();
Спасибо, учту.

2024-03-09 14:43 UTC, atimofeyev requested changes

2024-03-09 14:43 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/klimplyasov/reports_hw2/stage2.md
> +
Не вижу тут результатов тестирования с несколькими соединенями, cравнения результатов однопоточной и многопоточной обработки

2024-03-10 20:53 UTC, atimofeyev approved these changes

2024-03-10 20:53 UTC, merged