Осокин Дмитрий Hw2 Политех
polis-vk/2024-highload-dht pull request #95
Opened 2024-03-11 18:26 UTC by osokindm

Вместо [старого](https://github.com/polis-vk/2024-highload-dht/pull/68) реквеста

2024-04-01 11:45 UTC, lamtev requested changes
Есть критические проблемы в реализации (некорректная остановка), плюс фактически задание не выполнено (асинхронность отсутствует)

Разве что в целом проделанную работу и отчет можно оценить...

Предварительно, 0 баллов :(

UPD: 5 баллов за проделанную работу, полученный опыт, отчет

2024-04-01 18:49 UTC, osokindm commented on src/main/java/ru/vk/itmo/test/osokindm/HttpServerImpl.java
> +            if (!requestWorkers.awaitTermination(KEEP_ALIVE_TIME, TimeUnit.SECONDS)) {
При остановке 60 секунд установил, так как при закрытии, вероятно, нет много времени на ожидание, должны постараться быстро завершить текущие задачи. 
keepAliveTime в экзекьюторе поставил тоже 60 секунд, так как по идее должно быть достаточно для сетевых запросов. Плюс, учитывая, что corePoolSize и maximumPoolSize небольшие, простоев у них не будет. Или наоборот стоит из-за небольшого количества потоков в пуле увеличить?

2024-04-01 19:19 UTC, osokindm commented on src/main/java/ru/vk/itmo/test/osokindm/HttpServerImpl.java
> +                new ThreadPoolExecutor.DiscardOldestPolicy());
Да, наверное стоило стандартный AbortPolicy оставить. 
Discarded задача просто не будет выполнена, получается, что клиент не получит ответ от сервера и задача по таймауту на стороне клиента упадет.

2024-04-01 19:25 UTC, osokindm commented on src/main/java/ru/vk/itmo/test/osokindm/results/hw2/result_hw2.md
> +В сравнении с предыдущим этапом мы не получили значительного прироста производительности. Сервер выдерживает те же нагрузки, но в первой реалзиации с большей максимальной задержкой. Однозначно можно
Получается, что в данном случае уменьшенное количество процессорного времени SelectorThread'a скорее совпадение, связанное с небольшой нагрузкой?

2024-04-01 19:27 UTC, osokindm commented on src/main/java/ru/vk/itmo/test/osokindm/results/hw2/result_hw2.md
> +В сравнении с предыдущим этапом мы не получили значительного прироста производительности. Сервер выдерживает те же нагрузки, но в первой реалзиации с большей максимальной задержкой. Однозначно можно
Или, возможно, нагрузка та же, но из-за того, что она небольшая, в процентном соотношении с работой потоков получился сбивающий с толку cpu- флеймграф

2024-04-01 19:35 UTC, osokindm commented
ошибки осознал и исправил

2024-04-02 15:03 UTC, lamtev approved these changes

2024-04-02 15:04 UTC, merged