Пронин Валентин / ИТМО DWS / Stage 3
polis-vk/2024-highload-dht pull request #96
Opened 2024-03-11 18:26 UTC by GonarchX

2024-03-24 20:25 UTC, atimofeyev requested changes

2024-03-24 20:25 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/proninvalentin/failure_limiter/FailureLimiter.java
> +        for (int i = 0; i < nodesNumber; ++i) {
тут те же самые проблемы, final поля можно использовать для безопасной публикации объектов в многопоточной среде, но их нельзя модифицировать, надо их проинициализировать уже готовым объектом

2024-03-24 20:25 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/proninvalentin/failure_limiter/FailureLimiter.java
> +        return failuresPerNode.get(nodeToIndex.get(nodeUrl)) < maxFailureNumber;
вот эти цепочки get-ов очень путают, было бы лучше если бы была одна мапа объектов

2024-03-24 20:25 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/proninvalentin/failure_limiter/FailureLimiter.java
> +            resettingNodes[i] = new AtomicBoolean(false);
не вижу где бы мы выставляли true в resettingNodes

2024-03-24 20:25 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/proninvalentin/failure_limiter/FailureLimiter.java
> +                    Integer nodeIndex = nodeToIndex.get(nodeUrl);
просто так лучше не сбрасывать, нужен какой-то check метод, который подтвердит чо нода жива и тогда ее возвращать в строй

2024-03-24 20:25 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/proninvalentin/workers/WorkerPool.java
> +            pool.awaitTermination(SOFT_SHUT_DOWN_TIME, TimeUnit.SECONDS);
очень пересекается с кодом в Utils

2024-03-24 20:43 UTC, atimofeyev commented on src/main/java/ru/vk/itmo/test/proninvalentin/reports/stage3/report.md
> +* Попробовать редиректить клиента напрямую на ноду в кластере с нужными данными, чтобы не тратить время нашего сервера на ожидание ответа и его отправку.
вот бы попробовать и посмотреть результаты )

2024-03-30 12:38 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/reports/stage3/report.md
> +* Попробовать редиректить клиента напрямую на ноду в кластере с нужными данными, чтобы не тратить время нашего сервера на ожидание ответа и его отправку.
Думаю будет быстрее, т.к. мы не будем занимать наш сервер синхронным ожидаем ответа от другого сервера, стоит еще отметить, что профит будет, если и ноды будут на разных физических машинах, т.к. сейчас даже редиректнув запрос на другую ноду мы все равно утилизируем ресурсы одной машины

2024-03-30 12:38 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/workers/WorkerPool.java
> +            pool.awaitTermination(SOFT_SHUT_DOWN_TIME, TimeUnit.SECONDS);
Спасибо, забыл убрать

2024-03-30 12:43 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/failure_limiter/FailureLimiter.java
> +                    Integer nodeIndex = nodeToIndex.get(nodeUrl);
Согласен и сбрасывать нужно как-то постепенно как в том же Circuit Breaker, когда добавляется промежуточная фаза, чтобы проверить, что нода жива перед тем как разрешить снова слать на нее запросы. 
Кажется, что совсем уж неудачной вышла моя попытка добавить такую защиту от перегруза упавших нод.

2024-03-30 12:44 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/failure_limiter/FailureLimiter.java
> +            resettingNodes[i] = new AtomicBoolean(false);
Поправил, не заметил, т.к. особо не профилировал сценарий со сломанными нодами

2024-03-30 13:17 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/sharding/ConsistentHashing.java
> +                virtualNodeMapping.put(hash, nodeUrl);
Так как работаем с виртуальными нодами, то, скорее всего, будут другие виртуальные узлы, обслуживающие этот физический узел, но ситуация неприятная, поправил

2024-03-30 13:38 UTC, atimofeyev approved these changes

2024-03-30 13:41 UTC, GonarchX commented on src/main/java/ru/vk/itmo/test/proninvalentin/failure_limiter/FailureLimiter.java
> +        for (int i = 0; i < nodesNumber; ++i) {
Но у нас же инициализация в конструкторе, поэтому проблем с тем, что несколько потоков меняют состояние полей у объекты быть не должно, если я правильно понял замечание

2024-03-30 13:46 UTC, merged